# -*- coding: utf-8 -*-

"""
/***************************************************************************
 APRIORA
                                 A QGIS plugin
 Collection of APRIORA Plugins
 Generated by Plugin Builder: http://g-sherman.github.io/Qgis-Plugin-Builder/
                              -------------------
        begin                : 2024-06-13
        copyright            : (C) 2024 by Universität Rostock
        email                : cristiano.guidi2@uni-rostock.de
 ***************************************************************************/

/***************************************************************************
 *                                                                         *
 *   This program is free software; you can redistribute it and/or modify  *
 *   it under the terms of the GNU General Public License as published by  *
 *   the Free Software Foundation; either version 2 of the License, or     *
 *   (at your option) any later version.                                   *
 *                                                                         *
 ***************************************************************************/
"""

__author__ = 'Cristiano Guidi'
__date__ = '2024-06-13'
__copyright__ = '(C) 2024 by Universität Rostock'

# This will get replaced with a git SHA1 when you do a git archive

__revision__ = '$Format:%H$'

import processing
import string   # not sure if this library is in PyQgis
import numpy as np
from PyQt5.QtCore import QVariant
from qgis.PyQt.QtCore import QCoreApplication, Qt, QDir, QVariant
from qgis.core import (Qgis,
                       QgsProcessingAlgorithm,
                       QgsProcessing,
                       QgsProcessingException,
                       QgsFeature,
                       QgsField,
                       QgsFields,
                       QgsFeatureRequest,
                       QgsFeatureSink,
                       QgsGeometry,
                       QgsPointXY,
                       QgsProject,
                       QgsProcessingAlgorithm,
                       QgsProcessingParameterDefinition,
                       QgsProcessingParameterEnum,
                       QgsProcessingParameterFeatureSource,
                       QgsProcessingParameterFeatureSink,
                       QgsProcessingParameterField,
                       QgsProcessingParameterNumber,
                       QgsField,
                       QgsSpatialIndex,
                       QgsVectorLayer,
                       QgsWkbTypes,
                       edit)


class Accumulation(QgsProcessingAlgorithm):

    # Constants used to refer to parameters and outputs. They will be
    # used when calling the algorithm from another algorithm, or when
    # calling from the QGIS console.

    APIload = 'APIload'
    selectedAPI = 'selectedAPI'
    riverNetwork = 'RiverNetwork'
    fieldID = "fieldID"
    fieldNext = "fieldNext"
    meanFlow = "MeanFlow"
    MNQ = "MNQ"
    accmeanFlow = "AccMeanFlow"
    accMNQ = "AccMNQ"
    monPoint = "MonPoint"
    OUTPUT = 'OUTPUT'
    OUTPUT_mon = 'OUTPUT_mon'

    def shortHelpString(self):
        return self.tr(
            """ 
            This tool combines the output of '4 - Flow Estimation' with the output of '6 - Emission Loads'. In this part, the load of the \
            selected APIs is transferred to the river network and the concentration for mean flow and mean low flow condition is calculated.
            
            The tool supports two types of river network inputs:
            - **Line geometry**: Standard river network (e.g., output of '4 - Flow Estimation'). The tool will split river sections at emission points and create sub-sections.
            - **Polygon geometry**: Subcatchment-based flow data (e.g., Finnish hydrological model output). Emission points are connected to the closest polygon without splitting. Points can be inside or near polygons (within 500m).
            
            Workflow:
            1. Choose 'emission_loads.shp' as input for 'API load'
            2. Select the fields contanining APIs to accumulate. This selection should include only columns containing load of APIs in kg/a.
            3. Choose 'river_level.shp' (lines) or polygon-based flow data as input for 'River network'.
            4. Select the correct field of the river network. In case is the output of '4 - Flow Estimation', fill as follow:
                - ID Field -> NET_ID
                - Next Field -> NET_TO
                - Acc. Mean Flow -> calc_Mean_
                - Acc. Mean Low Flow -> calc_M_Low
            5. Click on 'Run'
            
            Note for polygon networks: The polygon layer must have NET_ID and NET_TO fields defining the connectivity between subcatchments.
            
            """)

    #Init tool
    def initAlgorithm(self, config):
        """
        Here we define the inputs and output of the algorithm, along
        with some other properties.
        """
        self.addParameter(
            QgsProcessingParameterFeatureSource(
                self.APIload,
                self.tr('API Load'),
                [QgsProcessing.TypeVectorPoint],
                defaultValue = QgsProject.instance().mapLayersByName("Emission Loads")[0].id() if QgsProject.instance().mapLayersByName("Emission Loads") else None
            )
        )

        self.addParameter(
            QgsProcessingParameterField(
                self.selectedAPI,
                self.tr('Select APIs to accumulate'),
                parentLayerParameterName = self.APIload,
                allowMultiple = True,
                type=QgsProcessingParameterField.Any,
                defaultValue=[
                    f.name() for f in QgsProject.instance().mapLayersByName("Emission Loads")[0].fields() if f.name().endswith("[kg/a]")
                ] if QgsProject.instance().mapLayersByName("Emission Loads") else []
            )
        )

        self.addParameter(
            QgsProcessingParameterFeatureSource(
                self.riverNetwork,
                self.tr('River network'),
                [QgsProcessing.TypeVectorLine, QgsProcessing.TypeVectorPolygon],
                defaultValue = QgsProject.instance().mapLayersByName("River level")[0].id() if QgsProject.instance().mapLayersByName("River level") else None
            )
        )

        self.addParameter(
            QgsProcessingParameterField(
                self.fieldID,
                self.tr("ID Field"),
                parentLayerParameterName = self.riverNetwork,
                defaultValue = 'NET_ID',   
                type = QgsProcessingParameterField.Any,
            )
        )

        self.addParameter(
            QgsProcessingParameterField(
                self.fieldNext,
                self.tr("Next Field"),
                parentLayerParameterName = self.riverNetwork,
                defaultValue = 'NET_TO',
                type = QgsProcessingParameterField.Any,
            )
        )

        # Note: `Mean Flow` input removed. Using accumulated mean flow to compute section mean flow.

        self.addParameter(
            QgsProcessingParameterField(
                self.accmeanFlow,
                self.tr("Acc. Mean Flow"),
                parentLayerParameterName = self.riverNetwork,
                defaultValue = 'calc_Mean_',
                type = QgsProcessingParameterField.Any,
            )
        )

        # Note: `Mean Low Flow` input removed. Using accumulated low flow to compute section low flow.
        self.addParameter(
            QgsProcessingParameterField(
                self.accMNQ,
                self.tr("Acc. Mean Low Flow"),
                parentLayerParameterName = self.riverNetwork,
                defaultValue = 'calc_M_Low',
                type = QgsProcessingParameterField.Any,
            )
        )

        self.addParameter(
            QgsProcessingParameterFeatureSource(
                self.monPoint,
                self.tr('Monitoring Point'),
                [QgsProcessing.TypeVectorPoint],
                optional=True
            )
        )


        # We add a feature sink in which to store our processed features (this
        # usually takes the form of a newly created vector layer when the
        # algorithm is run in QGIS).
        self.addParameter(
            QgsProcessingParameterFeatureSink(
                self.OUTPUT,
                self.tr('River accumulation'),
                QgsProcessing.TypeVectorAnyGeometry
            )
        )

        self.addParameter(
            QgsProcessingParameterFeatureSink(
                self.OUTPUT_mon,
                self.tr('Monitoring station with modelled values'),
                QgsProcessing.TypeVectorPoint,
                optional=True,
                createByDefault=False
            )
        )

    def processAlgorithm(self, parameters, context, feedback):
        """
        Here is where the processing itself takes place.
        """
        try:
            selected_api_fields = self.parameterAsStrings(parameters, self.selectedAPI, context)
        except AttributeError:
            selected_api_fields = self.parameterAsFields(parameters, self.selectedAPI, context)
        load_original = self.parameterAsVectorLayer(parameters, self.APIload, context)
        river_layer = self.parameterAsVectorLayer(parameters, self.riverNetwork, context)
        id_field = self.parameterAsString(parameters, self.fieldID, context)
        to_field = self.parameterAsString(parameters, self.fieldNext, context)
        acc_MQ_field = self.parameterAsString(parameters, self.accmeanFlow, context)
        acc_MNQ_field = self.parameterAsString(parameters, self.accMNQ, context)
        mon_point = self.parameterAsVectorLayer(parameters, self.monPoint, context)

        # Detect geometry type of river network
        river_geom_type = river_layer.geometryType()
        is_polygon_network = (river_geom_type == QgsWkbTypes.PolygonGeometry)
        
        if is_polygon_network:
            feedback.pushInfo("\n=== POLYGON RIVER NETWORK DETECTED ===")
            feedback.pushInfo("Using simplified polygon-based accumulation workflow.\n")
            return self.processPolygonNetwork(
                parameters, context, feedback,
                selected_api_fields, load_original, river_layer,
                id_field, to_field, acc_MQ_field, acc_MNQ_field, mon_point
            )
        else:
            feedback.pushInfo("\n=== LINE RIVER NETWORK DETECTED ===")
            feedback.pushInfo("Using standard line-based accumulation workflow.\n")
            return self.processLineNetwork(
                parameters, context, feedback,
                selected_api_fields, load_original, river_layer,
                id_field, to_field, acc_MQ_field, acc_MNQ_field, mon_point
            )

    def processPolygonNetwork(self, parameters, context, feedback,
                               selected_api_fields, load_original, river_layer,
                               id_field, to_field, acc_MQ_field, acc_MNQ_field, mon_point):
        """
        Process accumulation for polygon-based river networks (e.g., Finnish subcatchments).
        No splitting of polygons, simplified point-to-polygon connection.
        """
        tolerance = 500  # 500m distance limit
        
        # check if there are monitoring station points
        mon_field_names = []
        if mon_point is not None and mon_point.featureCount() > 0:
            load_crs = load_original.crs()
            load_field_names = set(f.name() for f in load_original.fields())
            mon_field_names = [f.name() for f in mon_point.fields() if f.name() not in load_field_names]
            load_file = processing.run("native:mergevectorlayers", {
                'LAYERS': [load_original, mon_point],
                'CRS': load_crs,
                'OUTPUT': 'TEMPORARY_OUTPUT'})['OUTPUT']
        else:
            load_file = load_original
            if mon_point is not None:
                feedback.pushWarning("Monitoring point layer provided but has no features, ignoring it...")

        # Create a working copy of the river layer (polygon network)
        feedback.pushInfo("Creating working copy of polygon network...")
        crs = river_layer.crs().authid()
        geom_type = QgsWkbTypes.displayString(river_layer.wkbType())
        waternet = QgsVectorLayer(f"{geom_type}?crs={crs}", "polygon_network", "memory")
        provider = waternet.dataProvider()
        provider.addAttributes(river_layer.fields())
        waternet.updateFields()
        features = []
        for feat in river_layer.getFeatures():
            new_feat = QgsFeature(feat)
            features.append(new_feat)
        provider.addFeatures(features)
        waternet.updateExtents()

        # Build spatial index for polygon network
        feedback.pushInfo(f"\nConnecting emission points to the closest polygon within {tolerance} m...")
        polygon_index = QgsSpatialIndex(waternet.getFeatures())
        polygon_feat_dict = {feat.id(): feat for feat in waternet.getFeatures()}

        # Dictionary to store which polygons receive which loads
        polygon_to_loads = {}  # polygon NET_ID -> list of (point_feat, api_values)
        too_far_points = []

        # Connect each emission point to the closest polygon
        for point_feat in load_file.getFeatures():
            point_geom = point_feat.geometry()
            if point_geom is None:
                continue

            # First check if point is inside any polygon
            search_rect = point_geom.boundingBox().buffered(tolerance)
            candidate_ids = polygon_index.intersects(search_rect)

            nearest_polygon = None
            min_distance = float('inf')
            is_inside = False

            for fid in candidate_ids:
                polygon_feat = polygon_feat_dict[fid]
                polygon_geom = polygon_feat.geometry()
                
                # Check if point is inside the polygon
                if polygon_geom.contains(point_geom):
                    nearest_polygon = polygon_feat
                    min_distance = 0
                    is_inside = True
                    break
                
                # Otherwise calculate distance
                dist = polygon_geom.distance(point_geom)
                if dist < min_distance:
                    min_distance = dist
                    nearest_polygon = polygon_feat

            # If no candidates from bounding box, try nearest neighbor
            if nearest_polygon is None:
                try:
                    nn_ids = polygon_index.nearestNeighbor(point_geom.asPoint(), 1)
                    if nn_ids:
                        polygon_feat = polygon_feat_dict.get(nn_ids[0])
                        if polygon_feat:
                            dist = polygon_feat.geometry().distance(point_geom)
                            if dist <= tolerance:
                                nearest_polygon = polygon_feat
                                min_distance = dist
                except Exception:
                    pass

            # Validate distance
            if nearest_polygon is None or (min_distance > tolerance and not is_inside):
                point_id = point_feat[0]
                if mon_field_names:
                    for field_name in mon_field_names:
                        val = point_feat[field_name]
                        if val is not None and str(val).strip():
                            point_id = f"{field_name}: {val}"
                            break
                too_far_points.append(point_id)
                feedback.pushWarning(f"Warning: no polygon found within {tolerance}m for point {point_id}")
                continue

            # Store the connection
            polygon_net_id = nearest_polygon[id_field]
            if is_inside:
                feedback.pushInfo(f"Point {point_feat[0]} is INSIDE polygon {polygon_net_id}")
            else:
                feedback.pushInfo(f"Point {point_feat[0]} is {min_distance:.2f}m from polygon {polygon_net_id}")

            if polygon_net_id not in polygon_to_loads:
                polygon_to_loads[polygon_net_id] = []
            polygon_to_loads[polygon_net_id].append(point_feat)

        # Report unconnected points
        if too_far_points:
            error_message = f"The following emission points are too far from the closest polygon: \n"
            for point_id in too_far_points:
                error_message += f"- Point {point_id}\n"
            error_message += f"Please edit the emission point to be within a distance of {tolerance} m."
            raise QgsProcessingException(error_message)

        # Add API load fields to the polygon layer
        feedback.pushInfo("\nAdding API load fields to polygon layer...")
        existing_fields = [field.name() for field in waternet.fields()]
        fields_to_add = []
        for field_name in selected_api_fields:
            if field_name not in existing_fields:
                fields_to_add.append(QgsField(field_name, QVariant.Double))
        if fields_to_add:
            waternet.dataProvider().addAttributes(fields_to_add)
            waternet.updateFields()

        # Transfer API loads to polygons (sum if multiple points connect to same polygon)
        feedback.pushInfo("\nTransferring API loads to polygons...")
        waternet.startEditing()
        for feat in waternet.getFeatures():
            net_id = feat[id_field]
            if net_id in polygon_to_loads:
                # Sum up all loads for this polygon
                for field_name in selected_api_fields:
                    total_load = 0
                    for point_feat in polygon_to_loads[net_id]:
                        val = point_feat[field_name]
                        if val is not None:
                            total_load += val
                    if total_load > 0:
                        feat.setAttribute(field_name, total_load)
                waternet.updateFeature(feat)
        waternet.commitChanges()

        """POLYGON ACCUMULATION FUNCTION"""
        feedback.setProgressText("\n=== Starting Polygon Accumulation ===\n")
        
        # Load network data
        idxId = waternet.fields().indexFromName(id_field)
        idxNext = waternet.fields().indexFromName(to_field)

        # Build data structure for accumulation
        # For polygons, we rely solely on NET_ID -> NET_TO relationships
        feedback.setProgressText("Loading polygon network data...\n")
        Data = [[
            str(f.attribute(idxId)),
            str(f.attribute(idxId)),  # prev_field = id_field for polygons
            str(f.attribute(idxNext)),
            f.id()
        ] for f in waternet.getFeatures()]
        DataArr_static = np.array(Data, dtype='object')
        feedback.setProgressText("Data loaded. Calculating flow paths...\n")

        # Function to find next features (downstream) in the network
        def nextFtsCalcPolygon(marker):
            """Find downstream features: those whose NET_TO matches the marker's NET_TO target"""
            vtx_to = DataArr[np.where(DataArr[:, 0] == marker)[0].tolist(), 2][0]  # NET_TO of actual segment
            rows_to = np.where(DataArr[:, 0] == vtx_to)[0].tolist()  # Find rows where NET_ID matches vtx_to
            return rows_to

        # Flow path function for polygons
        def FlowPathPolygon(start_row, fp_amount):
            """Calculate flow path for polygon network"""
            marker = DataArr[start_row, 0]
            weg = [start_row]
            i = 0
            while i != len(DataArr):
                next_rows = nextFtsCalcPolygon(marker)
                if len(next_rows) > 1:  # Dividing flow path
                    calc_column[start_row] = 0
                    calc_column[next_rows] = calc_column[next_rows] + fp_amount / len(next_rows)
                    out = [weg, next_rows]
                    break
                if len(next_rows) == 1:  # Continuing flow path
                    weg = weg + next_rows
                    marker = DataArr[next_rows[0], 0]
                if len(next_rows) == 0:  # End point (outlet)
                    out = [weg]
                    break
                i = i + 1
            return out

        # Loop through all selected substances
        for calc_field in selected_api_fields:
            idxCalc = waternet.fields().indexFromName(calc_field)
            if idxCalc == -1:
                feedback.reportError(f"Field {calc_field} not found")
                continue

            feedback.setProgressText(f"\nProcessing {calc_field}...")

            # Create working copy of DataArr and add load values
            DataArr = np.insert(DataArr_static.copy(), 3, 0.0, axis=1)
            for f in waternet.getFeatures():
                val = f.attribute(idxCalc)
                if val is not None:
                    fid = f.id()
                    row_idx = np.where(DataArr[:, 4] == fid)[0]
                    if row_idx.size > 0:
                        DataArr[row_idx[0], 3] = val
            DataArr[np.where(DataArr[:, 3] == None), 3] = 0
            calc_column = np.copy(DataArr[:, 3]).astype(float)
            DataArr[:, 3] = 0.0

            calc_segm = np.where(calc_column != 0)[0].tolist()

            total2 = len(calc_segm)
            feedback.pushInfo(f"Found {total2} polygons with load for {calc_field}")

            iteration = 0
            max_iterations = 10000
            max_iterations_flag = False
            last_segments = []

            while len(calc_segm) > 0 and iteration < max_iterations:
                iteration += 1
                if feedback.isCanceled():
                    break

                if len(last_segments) > 100:
                    last_segments.pop(0)
                last_segments.append(calc_segm[0] if calc_segm else None)

                if len(set(last_segments)) < 10 and len(last_segments) == 100:
                    feedback.reportError(f"Stuck loop detected! Repeated segments: {set(last_segments)}")
                    net_ids_debug = []
                    for feature_id in set(last_segments):
                        net_id_debug = DataArr[feature_id, 0]
                        net_ids_debug.append(net_id_debug)
                    feedback.reportError(f"Corresponding NET_IDs: {net_ids_debug}")
                    break

                StartRow = calc_segm[0]
                amount = calc_column[StartRow]
                calc_column[StartRow] = 0
                Fl_pth = FlowPathPolygon(StartRow, amount)
                if len(Fl_pth) == 2:
                    calc_segm = calc_segm + Fl_pth[1]
                DataArr[Fl_pth[0], 3] = DataArr[Fl_pth[0], 3] + amount
                calc_segm = calc_segm[1:]
                calc_segm = list(set(calc_segm))
                feedback.setProgress((1 - (len(calc_segm) / max(total2, 1))) * 100)

            if iteration >= max_iterations:
                max_iterations_flag = True

            # Add accumulated field
            api_short = calc_field[:4]
            new_field_name = f'acc_{api_short}'
            if new_field_name not in [f.name() for f in waternet.fields()]:
                waternet.dataProvider().addAttributes([QgsField(new_field_name, QVariant.Double)])
                waternet.updateFields()

            field_idx = waternet.fields().indexOf(new_field_name)
            if field_idx == -1:
                feedback.reportError(f"Error: field {new_field_name} not found")
                continue

            waternet.startEditing()
            for i, feature in enumerate(waternet.getFeatures()):
                if feedback.isCanceled():
                    break
                value_to_set = float(DataArr[i, 3])
                feature.setAttribute(field_idx, value_to_set)
                waternet.updateFeature(feature)
            waternet.commitChanges()
            feedback.setProgressText(f"{new_field_name} written successfully")

        if max_iterations_flag:
            feedback.reportError(f"Emergency break: exceeded {max_iterations} iterations")

        """Calculate concentration in each polygon"""
        feedback.setProgressText("\n=== Calculating Concentrations ===\n")

        conversion_flow = 1000 * 31_536_000
        conversion_load = 1_000_000_000_000
        conversion_factor = conversion_load / conversion_flow

        idx_mean_flow = waternet.fields().indexOf(acc_MQ_field)
        idx_low_flow = waternet.fields().indexOf(acc_MNQ_field)

        new_fields = []
        for api_field in selected_api_fields:
            api_short = api_field[:4]
            conc_field_mean = f"conc_{api_short}"
            conc_field_low = f"conL_{api_short}"
            if conc_field_mean not in waternet.fields().names():
                new_fields.append(QgsField(conc_field_mean, QVariant.Double))
            if conc_field_low not in waternet.fields().names():
                new_fields.append(QgsField(conc_field_low, QVariant.Double))

        if new_fields:
            waternet.dataProvider().addAttributes(new_fields)
            waternet.updateFields()

        waternet.startEditing()
        for feature in waternet.getFeatures():
            flow_mean = feature[idx_mean_flow] if idx_mean_flow != -1 else None
            flow_low = feature[idx_low_flow] if idx_low_flow != -1 else None

            for api_field in selected_api_fields:
                api_short = api_field[:4]
                acc_field = f"acc_{api_short}"
                acc_value = feature[acc_field]

                if acc_value is None:
                    continue

                conc_field_mean = f"conc_{api_short}"
                conc_field_low = f"conL_{api_short}"

                if flow_mean is not None and flow_mean != 0:
                    conc_mean = (acc_value * conversion_factor) / flow_mean
                    feature.setAttribute(conc_field_mean, conc_mean)

                if flow_low is not None and flow_low != 0:
                    conc_low = (acc_value * conversion_factor) / flow_low
                    feature.setAttribute(conc_field_low, conc_low)

            waternet.updateFeature(feature)
        waternet.commitChanges()

        # Prepare output sink for polygons
        (sink, dest_id) = self.parameterAsSink(
            parameters,
            self.OUTPUT,
            context,
            waternet.fields(),
            waternet.wkbType(),
            waternet.sourceCrs()
        )

        for feature in waternet.getFeatures():
            sink.addFeature(feature)

        # Handle monitoring points for polygon network
        if mon_point is not None and mon_point.featureCount() > 0:
            feedback.pushInfo("\n=== Processing Monitoring Points (Polygon Network) ===\n")
            load_crs = load_original.crs()

            if mon_point.crs().authid() != load_crs.authid():
                mon_point_copy = processing.run("native:reprojectlayer", {
                    'INPUT': mon_point,
                    'TARGET_CRS': load_crs,
                    'CONVERT_CURVED_GEOMETRIES': False,
                    'OPERATION': '+proj=noop',
                    'OUTPUT': 'TEMPORARY_OUTPUT'})['OUTPUT']
            else:
                crs = mon_point.crs().authid()
                geom_type = QgsWkbTypes.displayString(mon_point.wkbType())
                mon_point_copy = QgsVectorLayer(f"{geom_type}?crs={crs}", "mon_point_copy", "memory")
                mon_provider = mon_point_copy.dataProvider()
                mon_provider.addAttributes(mon_point.fields())
                mon_point_copy.updateFields()
                features = []
                for feat in mon_point.getFeatures():
                    new_feat = QgsFeature(feat)
                    features.append(new_feat)
                mon_provider.addFeatures(features)
                mon_point_copy.updateExtents()

            # Add concentration and accumulated load fields
            mon_provider = mon_point_copy.dataProvider()
            existing_mon_fields = [f.name() for f in mon_point_copy.fields()]
            new_mon_fields = []
            for api_field in selected_api_fields:
                api_short = api_field[:4]
                conc_mean = f"conc_{api_short}"
                conc_low = f"conL_{api_short}"
                acc_load = f"acc_{api_short}"
                if conc_mean not in existing_mon_fields:
                    new_mon_fields.append(QgsField(conc_mean, QVariant.Double))
                if conc_low not in existing_mon_fields:
                    new_mon_fields.append(QgsField(conc_low, QVariant.Double))
                if acc_load not in existing_mon_fields:
                    new_mon_fields.append(QgsField(acc_load, QVariant.Double))
            if new_mon_fields:
                mon_provider.addAttributes(new_mon_fields)
                mon_point_copy.updateFields()

            # Build spatial index on polygon network
            water_index = QgsSpatialIndex(waternet.getFeatures())
            waternet_feat_dict = {feat.id(): feat for feat in waternet.getFeatures()}

            mon_point_copy.startEditing()
            for mon_feat in mon_point_copy.getFeatures():
                if mon_feat.geometry() is None:
                    continue
                mon_geom = mon_feat.geometry()

                # Find closest polygon (including if point is inside)
                search_rect = mon_geom.boundingBox().buffered(tolerance)
                candidate_ids = water_index.intersects(search_rect)

                chosen_feat = None
                min_distance = float('inf')

                for fid in candidate_ids:
                    wfeat = waternet_feat_dict.get(fid)
                    if wfeat is None:
                        continue
                    wgeom = wfeat.geometry()
                    
                    # Check if inside polygon
                    if wgeom.contains(mon_geom):
                        chosen_feat = wfeat
                        min_distance = 0
                        break
                    
                    dist = wgeom.distance(mon_geom)
                    if dist < min_distance and dist <= tolerance:
                        min_distance = dist
                        chosen_feat = wfeat

                # Try nearest neighbor if no candidates
                if chosen_feat is None:
                    try:
                        nn_ids = water_index.nearestNeighbor(mon_geom.asPoint(), 1)
                        if nn_ids:
                            wfeat = waternet_feat_dict.get(nn_ids[0])
                            if wfeat:
                                dist = wfeat.geometry().distance(mon_geom)
                                if dist <= tolerance:
                                    chosen_feat = wfeat
                    except Exception:
                        pass

                if chosen_feat is None:
                    feedback.pushWarning(f"No polygon found within {tolerance}m for monitoring point")
                    continue

                # Copy concentration and accumulated load values
                for api_field in selected_api_fields:
                    api_short = api_field[:4]
                    conc_mean = f"conc_{api_short}"
                    conc_low = f"conL_{api_short}"
                    acc_load = f"acc_{api_short}"

                    if conc_mean in [f.name() for f in waternet.fields()] and conc_mean in [f.name() for f in mon_point_copy.fields()]:
                        mon_feat.setAttribute(mon_point_copy.fields().indexFromName(conc_mean), chosen_feat[conc_mean])
                    if conc_low in [f.name() for f in waternet.fields()] and conc_low in [f.name() for f in mon_point_copy.fields()]:
                        mon_feat.setAttribute(mon_point_copy.fields().indexFromName(conc_low), chosen_feat[conc_low])
                    if acc_load in [f.name() for f in waternet.fields()] and acc_load in [f.name() for f in mon_point_copy.fields()]:
                        mon_feat.setAttribute(mon_point_copy.fields().indexFromName(acc_load), chosen_feat[acc_load])

                mon_point_copy.updateFeature(mon_feat)
            mon_point_copy.commitChanges()

            # Output monitoring points
            (mon_sink, mon_dest_id) = self.parameterAsSink(
                parameters,
                self.OUTPUT_mon,
                context,
                mon_point_copy.fields(),
                mon_point_copy.wkbType(),
                mon_point_copy.sourceCrs()
            )

            if mon_sink is None:
                feedback.pushWarning(
                    "\nMonitoring output is set to 'Skip output'. Monitoring point results will not be saved.\n"
                )
                return {self.OUTPUT: dest_id}
            else:
                for feature in mon_point_copy.getFeatures():
                    mon_sink.addFeature(feature)
                return {self.OUTPUT_mon: mon_dest_id, self.OUTPUT: dest_id}

        return {self.OUTPUT: dest_id}

    def processLineNetwork(self, parameters, context, feedback,
                            selected_api_fields, load_original, river_layer,
                            id_field, to_field, acc_MQ_field, acc_MNQ_field, mon_point):
        """
        Original processing logic for line-based river networks.
        """


        # check if there are monitoring station points
        # if there are, they are merged with emission load points and snapped together to the river section
        mon_field_names = []  # store monitoring-specific field names for later identification
        if mon_point is not None and mon_point.featureCount() > 0:  # be sure layer exist and is not null
            # get the CRS from load_original layer
            load_crs = load_original.crs()
            # capture monitoring field names (those unique to monitoring layer)
            load_field_names = set(f.name() for f in load_original.fields())
            mon_field_names = [f.name() for f in mon_point.fields() if f.name() not in load_field_names]
            # merge the shapefiles
            load_file = processing.run("native:mergevectorlayers", {
                'LAYERS':[load_original, mon_point],
                'CRS':load_crs,
                'OUTPUT':'TEMPORARY_OUTPUT'})['OUTPUT']
            
        else:
            load_file = load_original
            if mon_point is not None: # layer exists but is empty
                feedback.pushWarning("Monitoring point layer provided but has no features, ignoring it...")
        
        # snapping function that connects the emission load points to the river section
        tolerance = 500 # 500m
        feedback.pushInfo(f"\nSnapping the emission point to the closest river section within {tolerance} m.")
        load = processing.run("native:snapgeometries", {
            'INPUT':load_file,
            'REFERENCE_LAYER':river_layer,
            'TOLERANCE':tolerance,
            'BEHAVIOR':1,
            'OUTPUT':'TEMPORARY_OUTPUT'})["OUTPUT"]
        
        # find the closest river section for each emission point
        # create a spatial index for river sections
        river_index = QgsSpatialIndex(river_layer.getFeatures())
        river_feat_dict = {}

        for feat in river_layer.getFeatures():
            river_index.addFeature(feat)
            river_feat_dict[feat.id()] = feat

        # dictionary to store
        section_to_points = {}
        # list to store not connected points
        too_far_points = []
        
        feedback.pushInfo("\nChecking if snapping was successfull for all emission points.")
        
        # go through each emission point
        for point_feat in load.getFeatures():
            point_geom = point_feat.geometry()

            # # find the nearest river section
            # nearest_ids = river_index.nearestNeighbor(point_geom.asPoint(),1)
            # if not nearest_ids:
            #     continue # skip if no match found

            # river_feat = next(river_layer.getFeatures(QgsFeatureRequest(nearest_ids[0])))
            # river_geom = river_feat.geometry()

            # # debug: print the actual distance for troubleshooting
            # feedback.pushInfo(f"DEBUG: point ID {point_feat.id()} is at a distance {river_geom.distance(point_geom): .6f} from river section {river_feat[id_field]}")

            # create bounding box
            search_rect = point_geom.boundingBox().buffered(tolerance)

            # use spatial index to get candidate IDs
            candidate_ids = river_index.intersects(search_rect)
            
            nearest_river = None
            min_distance = float('inf')

            for fid in candidate_ids:
                river_feat = river_feat_dict[fid]
                river_geom = river_feat.geometry()
                dist = river_geom.distance(point_geom)

                if dist < min_distance:
                    min_distance = dist
                    nearest_river = river_feat
            
            # check if a river is found
            if not nearest_river:
                # try to identify if it's a monitoring point by checking first non-NULL monitoring field
                point_id = point_feat[0]
                if mon_field_names:
                    for field_name in mon_field_names:
                        val = point_feat[field_name]
                        if val is not None and str(val).strip():
                            point_id = f"{field_name}: {val}"
                            break
                too_far_points.append(point_id)
                feedback.pushWarning(f"Warning: no river section found within {tolerance}m for point {point_id}")
                continue

            river_geom = nearest_river.geometry()
            feedback.pushInfo("\nChecking if the snapping process was successfull and each emission point is assigned to the closest river section.")
            feedback.pushInfo(f"DEBUG: point ID {point_feat[0]} is at a distance {river_geom.distance(point_geom): .6f} from river section {nearest_river[id_field]}")

            # double check intersection or proximity
            if river_geom.intersects(point_geom) or river_geom.distance(point_geom) < 1e-6:
                section_id = nearest_river[id_field]
                section_to_points.setdefault(section_id, []).append((point_feat, river_geom))
            else:
                # raise error if point too far after the snapping
                # try to identify if it's a monitoring point
                point_id = point_feat[0]
                if mon_field_names:
                    for field_name in mon_field_names:
                        val = point_feat[field_name]
                        if val is not None and str(val).strip():
                            point_id = f"{field_name}: {val}"
                            break
                raise QgsProcessingException(
                    f"Point {point_id} is too far from the closest river section.\n"
                    f"Please edit this point to be within a distance of {tolerance} m."
                )
        
        # report unconnected points
        if too_far_points:
            error_message = f"The following emission points are too far from the closest river section: \n"
            for point_id in too_far_points:
                error_message += f"- Point {point_id}\n"
            error_message += f"Please edit the emission point to be within a distance of {tolerance} m."

            raise QgsProcessingException(error_message)
            

        # simple version to print
        for section_id, features in section_to_points.items():
            emission_ids = [f[0].id() for f in features]
            feedback.pushInfo(f"River section {section_id} --> {emission_ids}")

        # final result
        sorted_distances = {}

        for section_id, point_data in section_to_points.items():
            feedback.pushInfo(f"\nProcessing river section: {section_id}")

            # all point_data contain the same river_geom for a section so we take only the first one
            river_geom = point_data[0][1]

            # extract the line geometry as a polyline
            if river_geom.type() == QgsWkbTypes.LineGeometry:
                if QgsWkbTypes.isMultiType(river_geom.wkbType()):
                    river_line = river_geom.asMultiPolyline()[0]
                else:
                    river_line = river_geom.asPolyline()
            else:
                feedback.pushInfo(f"Skipping section {section_id}: not a line geometry")
                continue
                

            results = []

            for point_feat, _ in point_data:  # the _ ignores the second variable, the river geometry
                point_geom = point_feat.geometry()

                # snap point to the closest segment on the river
                snapped_point = river_geom.closestSegmentWithContext(point_geom.asPoint())[1]
                snapped_geom = QgsGeometry.fromPointXY(snapped_point)

                # distance along river (from its start)
                river_distance = river_geom.lineLocatePoint(snapped_geom)

                results.append((point_feat.id(), river_distance))

            # sort all points in this section by river distance
            sorted_results = sorted(results, key=lambda x:x[1])
            sorted_distances[section_id] = sorted_results

            # print results
            feedback.pushInfo(f"River section {section_id} sorted emission points:")
            for emission_id, distance in sorted_results:
                feedback.pushInfo(f"Emission {emission_id} -> {distance:.2f} meters")


        # splitting river network at lines by creating buffer at vertices
        buffer = processing.run("native:buffer", {
            'INPUT': load,
            'DISTANCE':0.02,    # buffer of 2 cm
            'SEGMENTS':5,
            'END_CAP_STYLE':0,
            'JOIN_STYLE':0,
            'MITER_LIMIT':2,
            'DISSOLVE':False,
            'SEPARATE_DISJOINT':False,
            'OUTPUT':'TEMPORARY_OUTPUT'})["OUTPUT"]
        
        feedback.pushInfo(f"Number of feature buffer: {buffer.featureCount()}")

        # split with the buffer
        split_with_errors = processing.run("native:splitwithlines", {
            'INPUT':river_layer,
            'LINES':buffer,
            'OUTPUT':'TEMPORARY_OUTPUT'})["OUTPUT"]
        
        feedback.pushInfo(f"Number of feature split_with_errors: {split_with_errors.featureCount()}")

        # remove the segments within the buffer from the river layer
        difference = processing.run("native:difference", {
            'INPUT':split_with_errors,
            'OVERLAY':buffer,
            'OUTPUT':'TEMPORARY_OUTPUT',
            'GRID_SIZE':None})["OUTPUT"]
        
        feedback.pushInfo(f"Number of feature difference: {difference.featureCount()}")

        # snap the river line back together
        split_river_layer = processing.run("native:snapgeometries", {
            'INPUT': difference,
            'REFERENCE_LAYER': load,
            'TOLERANCE':0.05,   # snapping within 5cm
            'BEHAVIOR':0,
            'OUTPUT':'TEMPORARY_OUTPUT'})["OUTPUT"]
        
        feedback.pushInfo(f"Number of feature split_river_layer: {split_river_layer.featureCount()}")

        # the file has geometries that need to be fixed
        # with MAC, method [1] gives problem so we add method [0] as well
        # check GEOS version and choose method
        geos_version_str = Qgis.geosVersion()
        version_parts = geos_version_str.split('.')[:2] # extract first two numbers, e.g., "3" and "10"
        major = int(version_parts[0]) #e.g., "3"
        minor = int(version_parts[1]) #e.g., "10"
        if major > 3 or (major == 3 and minor >= 10):
            method = 1
        else:
            method = 0
        feedback.pushInfo(f"GEOS version: {geos_version_str}")
        feedback.setProgressText(f"\nFixing the geometries of the file with method [{method}]...")

        fixed_layer = processing.run("native:fixgeometries", {
            'INPUT':split_river_layer,
            'METHOD':method,
            'OUTPUT':'TEMPORARY_OUTPUT'},
            context=context, feedback=feedback)["OUTPUT"]
        
        feedback.pushInfo(f"Number of feature fixed_layer: {fixed_layer.featureCount()}")

        # remove null geometries from the layer
        feedback.setProgressText("\nRemoving the null geometries...")
        non_null_geom_layer = processing.run("native:removenullgeometries", {
            'INPUT':fixed_layer,
            'REMOVE_EMPTY':True,
            'OUTPUT':'TEMPORARY_OUTPUT'},
            context=context, feedback=feedback)["OUTPUT"]
        
        feedback.pushInfo(f"Number of feature non_null_geom_layer: {non_null_geom_layer.featureCount()}")

        # # dissolving the layer because after "split with lines" some features are separated
        # non_null_geom_layer = processing.run("native:dissolve", {
        #     'INPUT': non_null_geom_layer_no_dissolved,
        #     'FIELD':['CATCH_ID'],
        #     'SEPARATE_DISJOINT':False,
        #     'OUTPUT':'TEMPORARY_OUTPUT'})["OUTPUT"]
        
        # feedback.pushInfo(f"Number of feature non_null_geom_layer: {non_null_geom_layer.featureCount()}")
        
        # We create new river sections at each emission point. We need to update the name of the section (NET_ID) and 
        # the relationship with the other river sections (NET_TO). We create a new naming system where if section 1001
        # has multiple emission points, it is divided and renamed in 1001A, 1001B, 1001C, ...
        
        new_ids_by_feature = {} # store new NET_ID
        used_emission_ids = set()
        emission_to_letter = {} # assign letter to emission points

        for section_id, sorted_results in sorted_distances.items():
            if not sorted_results:
                continue

            # get all features split from this river section
            section_feats = [f for f in non_null_geom_layer.getFeatures() if f[id_field] == section_id]

            # assign a letter based on which emission points is closest to its downstream vertex
            for feat in section_feats:
                geom = feat.geometry()

                # get end point
                if geom.isMultipart():
                    line = geom.asMultiPolyline()[0]
                else:
                    line = geom.asPolyline()

                if not line:
                    continue

                end_point = line[-1]
                end_geom = QgsGeometry.fromPointXY(end_point)

                assigned = False
                for i, (em_id, _) in enumerate(sorted_results):
                    if em_id in used_emission_ids:
                        continue

                    # find geometry of emission point
                    em_feat = next(load.getFeatures(QgsFeatureRequest(em_id)))
                    em_point = em_feat.geometry().asPoint()
                    em_geom = QgsGeometry.fromPointXY(em_point)

                    dist = end_geom.distance(em_geom)
                    if dist < 5: # 5 meters tolerance
                        letter = string.ascii_uppercase[i] #A, B, C..
                        new_ids_by_feature[feat.id()] = f"{section_id}{letter}"
                        emission_to_letter[em_id] = (str(section_id), string.ascii_uppercase[i+1])
                        used_emission_ids.add(em_id)
                        assigned = True
                        break

                if not assigned:
                    # assign final (n+1)th letter if no match found
                    letter = string.ascii_uppercase[len(sorted_results)]
                    new_ids_by_feature[feat.id()] = f"{section_id}{letter}"
        
        # 1. update NET_ID
        non_null_geom_layer.startEditing()
        
        for feat in non_null_geom_layer.getFeatures():
            if feat.id() in new_ids_by_feature:
                feat.setAttribute(id_field, new_ids_by_feature[feat.id()])
                non_null_geom_layer.updateFeature(feat)
                    
        # 2. create a mapping with original NET_ID, feature and new NET_ID
        grouped = {}

        for feat in non_null_geom_layer.getFeatures():
            fid = feat.id()
            if fid in new_ids_by_feature:
                new_id = new_ids_by_feature[fid]
                base_id =''.join(filter(str.isdigit, new_id)) #e.g., from '1001A'-->'1001'

                if base_id not in grouped:
                    grouped[base_id] = []

                grouped[base_id].append((feat, new_id))
        
        # 3. update NET_TO fields
        for base_id in grouped:
            # sort by the new_id
            sorted_feats = sorted(grouped[base_id], key=lambda x: x[1])

            for i, (feat, new_id) in enumerate(sorted_feats):
                if i < len(sorted_feats) -1:
                    next_id = sorted_feats[i+1][1]
                    feat.setAttribute(to_field, next_id)
                # last one keep its original NET_TO
                non_null_geom_layer.updateFeature(feat)

        # 4. update NET_TO, set NET_FROM = NET_ID
        section_id_to_first_new_id = {}
        for new_id in new_ids_by_feature.values():
            base_id = ''.join(filter(str.isdigit, new_id))
            if base_id not in section_id_to_first_new_id:
                section_id_to_first_new_id[base_id] = new_id

        for feat in non_null_geom_layer.getFeatures():
            net_id = feat[id_field]
            net_to = feat[to_field]

            # update NET_TO
            if net_to.strip() in section_id_to_first_new_id:
                feat.setAttribute(to_field, section_id_to_first_new_id[net_to])

            # # set NET_FROM to NET_ID
            # feat.setAttribute('NET_FROM', net_id)
            non_null_geom_layer.updateFeature(feat)
        

        # 5. after building the correct river section relationships, we need to update the flow estimation and scale it
        # based on the section_length/total_section_length
        # Compute per-section (non-accumulated) mean and low flows from accumulated fields.
        # For a section: mean_flow = acc_mean_flow(section) - sum(acc_mean_flow(children whose NET_TO == section))
        # This avoids requiring the user to provide single-section flow values.

        # Build mapping NET_TO -> list of feature objects for fast lookup
        children_map = {}
        for f in non_null_geom_layer.getFeatures():
            to_val = str(f[to_field]) if f[to_field] is not None else ''
            children_map.setdefault(to_val, []).append(f)

        # compute per-feature mean (non-accumulated) flows
        computed_mean = {}
        computed_low = {}
        for f in non_null_geom_layer.getFeatures():
            net_id_val = str(f[id_field])
            acc_mean_val = f[acc_MQ_field] if f[acc_MQ_field] is not None else 0.0
            acc_low_val = f[acc_MNQ_field] if f[acc_MNQ_field] is not None else 0.0
            upstream_children = children_map.get(net_id_val, [])
            sum_up_acc = sum([c[acc_MQ_field] if c[acc_MQ_field] is not None else 0.0 for c in upstream_children])
            sum_up_low = sum([c[acc_MNQ_field] if c[acc_MNQ_field] is not None else 0.0 for c in upstream_children])
            # computed mean for this exact NET_ID string
            computed_mean[net_id_val] = acc_mean_val - sum_up_acc
            computed_low[net_id_val] = acc_low_val - sum_up_low
        # group split features by base section ID
        # define per-section (non-accumulated) field names and ensure they exist
        MQ_field = 'Mean_Flow'
        MNQ_field = 'M_Low_Flow'

        provider = non_null_geom_layer.dataProvider()
        existing_field_names = [f.name() for f in non_null_geom_layer.fields()]
        fields_to_add = []
        if MQ_field not in existing_field_names:
            fields_to_add.append(QgsField(MQ_field, QVariant.Double))
        if MNQ_field not in existing_field_names:
            fields_to_add.append(QgsField(MNQ_field, QVariant.Double))
        if fields_to_add:
            provider.addAttributes(fields_to_add)
            non_null_geom_layer.updateFields()

        split_groups = {}       # it is collecting ALL the features instead of only the ones that have been split, change it
        original_flows = {}

        for feat in non_null_geom_layer.getFeatures():
            net_id = str(feat[id_field])
            base_id = ''.join(filter(str.isdigit, net_id))

            if base_id not in split_groups:
                split_groups[base_id] = []

            geom = feat.geometry()
            length = geom.length()
            split_groups[base_id].append((feat.id(), length, net_id))

            # save the original (computed) flow values using accumulated inputs
            if base_id not in original_flows:
                # prefer computed per-NET_ID values; fallback to feature attribute if missing
                # QgsFeature doesn't have .get(); use item access which returns attribute by name
                mean_fallback = feat[acc_MQ_field] if feat[acc_MQ_field] is not None else 0.0
                low_fallback = feat[acc_MNQ_field] if feat[acc_MNQ_field] is not None else 0.0
                mean_val = computed_mean.get(net_id, mean_fallback)
                low_val = computed_low.get(net_id, low_fallback)
                original_flows[base_id] = {
                    'mean_flow': mean_val,
                    'acc_mean_flow': feat[acc_MQ_field] if feat[acc_MQ_field] is not None else 0.0,
                    'mean_low_flow': low_val,
                    'acc_mean_low_flow': feat[acc_MNQ_field] if feat[acc_MNQ_field] is not None else 0.0
                }
        
        # update flow using proportional length
        for base_id, parts in split_groups.items():
            # skip if not split
            if len(parts) == 1:
                continue
            
            # sort by NET_ID
            parts = sorted(parts, key=lambda x: x[2])

            total_length = sum(length for _, length, _ in parts)
            if total_length == 0:
                continue

            # get mean flow values from first feature
            acc_end = original_flows[base_id]['acc_mean_flow']
            mean_total = original_flows[base_id]['mean_flow']
            acc_start = acc_end - mean_total

            # get mean low flow values from first feature
            acc_low_end = original_flows[base_id]["acc_mean_low_flow"]
            mean_low_total = original_flows[base_id]["mean_low_flow"]
            acc_low_start = acc_low_end - mean_low_total

            # cumulative length to distribute flow
            cumulative = 0
            cumulative_low = 0
            for feat_id, part_length, net_id in parts:
                feat = non_null_geom_layer.getFeature(feat_id)
                cumulative += part_length
                ratio = cumulative/total_length
                percentage = part_length/total_length

                # new flow values
                feat[MQ_field] = percentage * mean_total
                feat[acc_MQ_field] = acc_start + (mean_total * ratio)
                # feat["Mean_Flow"] = percentage * mean_total
                # feat["calc_Mean_"] = acc_start + (mean_total * ratio)

                non_null_geom_layer.updateFeature(feat)

                # same process for low flow values
                cumulative_low += part_length
                ratio_low = cumulative_low/total_length
                percentage_low = part_length/total_length

                # new flow values
                feat[MNQ_field] = percentage_low * mean_low_total
                feat[acc_MNQ_field] = acc_low_start + (mean_low_total * ratio_low)
                # feat["M_Low_Flow"] = percentage_low * mean_low_total
                # feat["calc_M_Low"] = acc_low_start + (mean_low_total * ratio_low)
                non_null_geom_layer.updateFeature(feat)

        # 6. transfer the API load to the river section
        # first add the selected_api_fields to the layer
        provider = non_null_geom_layer.dataProvider()
        existing_fields = [field.name() for field in non_null_geom_layer.fields()]

        for field_name in selected_api_fields:
            if field_name not in existing_fields:
                provider.addAttributes([QgsField(field_name, QVariant.Double)])
        non_null_geom_layer.updateFields()

        # build a emission feature map
        base_letter_to_emission = {}
        for em_id, (base_id, letter) in emission_to_letter.items():
            em_feat = load.getFeature(em_id)
            base_letter_to_emission[(base_id, letter)] = em_feat

        # assign the API load values using the mapping
        for feat in non_null_geom_layer.getFeatures():
            net_id = feat[id_field]
            base_id = ''.join(filter(str.isdigit, str(net_id)))
            letter = net_id.replace(base_id, "")

            em_feat = base_letter_to_emission.get((base_id, letter))
            if em_feat:
                for field in selected_api_fields:
                    feat[field] = em_feat[field]
                non_null_geom_layer.updateFeature(feat)
    
        non_null_geom_layer.commitChanges()
        
        #QgsProject.instance().addMapLayer(non_null_geom_layer)

        """ACCUMULATION FUNCTION"""
        '''loading the network'''
        waternet = non_null_geom_layer

        '''names of fields for id,next segment, previous segment'''
        id_field = id_field
        next_field = to_field
        prev_field = id_field

        '''field index for id,next segment, previous segment'''
        idxId = waternet.fields().indexFromName(id_field) 
        idxPrev = waternet.fields().indexFromName(prev_field)
        idxNext = waternet.fields().indexFromName(next_field)

        '''load data from layer'''
        feedback.setProgressText(self.tr("Loading network layer\n "))
        Data = [[
            str(f.attribute(idxId)),
            str(f.attribute(idxPrev)),
            str(f.attribute(idxNext)),
            f.id()
        ] for f in waternet.getFeatures()]
        DataArr_static = np.array(Data, dtype='object')
        feedback.setProgressText(self.tr("Data loaded \n Calculating flow paths \n"))

        '''function to find next features in the net'''
        def nextFtsCalc (MARKER2):
            vtx_to = DataArr[np.where(DataArr[:,0] == MARKER2)[0].tolist(),2][0] # "to"-vertex of actual segment
            rows_to = np.where(DataArr[:,1] == vtx_to)[0].tolist() # find rows in DataArr with matching "from"-vertices to vtx_to
            unconnected_errors = [DataArr[x, 4] for x in rows_to if DataArr[x, 2]=='unconnected']  # this can only happen after manual editing
            if len(unconnected_errors) > 0:
                waternet.removeSelection()
                waternet.selectByIds(unconnected_errors, waternet.SelectBehavior(1))
                raise QgsProcessingException(
                    'The selected features in the flow are marked as \'unconnected\' '
                    + '(most likely because of manual editing). Please delete the columns with the network information ('
                    + next_field
                    + ', '
                    + prev_field
                    + ') and run tool 1 \"Water Network Constructor\" again.'
                )
            return(rows_to)

        '''function to find flow path'''
        def FlowPath (Start_Row, fp_amount):
            MARKER=DataArr[Start_Row,0] #set MARKER to ID of the first segment
            Weg = [Start_Row]    
            i=0
            while i!=len(DataArr):
                next_rows = nextFtsCalc(MARKER)
                if len(next_rows) > 1: # deviding flow path
                    calc_column[StartRow] = 0
                    calc_column[next_rows] = calc_column[next_rows]+fp_amount/len(next_rows) # this can be changed to weightet separation later
                    out = [Weg, next_rows]
                    break
                if len(next_rows) == 1: # continuing flow path
                    Weg = Weg + next_rows
                    MARKER=DataArr[next_rows[0],0] # change MARKER to Id of next segment 
                if len(next_rows) == 0: # end point
                    out = [Weg]
                    break
                i=i+1
            return (out)

        # loop through all selected substances
        for calc_field in selected_api_fields:
            idxCalc = waternet.fields().indexFromName(calc_field)
            if idxCalc == -1:
                feedback.reportError(f"Field {calc_field} not found")
                continue

            feedback.setProgressText(f"\nProcessing {calc_field}...")

            # create full working copy of DataArr and add flow values
            DataArr = np.insert(DataArr_static.copy(), 3, 0.0, axis=1)
            for f in waternet.getFeatures():
                val = f.attribute(idxCalc)
                if val is not None:
                    fid = f.id()
                    row_idx = np.where(DataArr[:,4] == fid)[0]
                    if row_idx.size > 0:
                        DataArr[row_idx[0], 3] = val
            DataArr[np.where(DataArr[:,3] == None), 3] = 0
            calc_column = np.copy(DataArr[:, 3]).astype(float)
            DataArr[:, 3] = 0.0

            calc_segm = np.where(calc_column != 0)[0].tolist()
            calc_segm = [i for i in calc_segm if (DataArr[i, 1] != 'unconnected' and DataArr[i,2] != 'unconnected')]

            total2 = len(calc_segm)
            feedback.pushInfo("Checkpoint A")

            ####
            # adding some trouble shooting line here
            ####
            iteration = 0
            max_iterations = 10000 #safety limit
            max_iterations_flag = False
            last_segments = [] #track recent segments to detect stuck loops

            while len(calc_segm) > 0 and iteration < max_iterations:
                iteration += 1
                if feedback.isCanceled():
                    break

                # detection if it is stuck, if it is processing the same segment repeatedly
                if len(last_segments) > 100:    # keep last 100 segments
                    last_segments.pop(0)
                last_segments.append(calc_segm[0] if calc_segm else None)

                # check if it stuck on the same segment
                if len(set(last_segments)) < 10 and len(last_segments) == 100:
                    feedback.reportError(f"Stuck loop detected! Repeated segments: {set(last_segments)}")
                    # convert feature IDs to NET_IDs for selection
                    net_ids_debug = []
                    for feature_id in set(last_segments):
                        net_id_debug = DataArr[feature_id, 0]
                        net_ids_debug.append(net_id_debug)
                    feedback.reportError(f"Corresponding NET_IDs to select: {net_ids_debug}")
                    break

                StartRow = calc_segm[0]
                amount = calc_column[StartRow] # amount to add to flow path
                calc_column[StartRow] = 0 #"delete" calculated amount from list (set 0)
                Fl_pth = FlowPath(StartRow, amount) # get flow path of StartRow 
                if len(Fl_pth)== 2:
                    calc_segm = calc_segm + Fl_pth[1] # if flow path devides add new segments to calc_segm
                DataArr[Fl_pth[0],3] = DataArr[Fl_pth[0],3]+amount # Add the amount to the calculated flow path
                calc_segm = calc_segm[1:] # delete used segment
                calc_segm = list(set(calc_segm)) #delete duplicate values
                feedback.setProgress((1-(len(calc_segm)/total2))*100)

            if iteration >= max_iterations:
                max_iterations_flag = True

            feedback.pushInfo("Checkpoint B")
            # add output field
            # get API name for renaming the field
            api_short = calc_field[:4]
            new_field_name = f'acc_{api_short}'
            if new_field_name not in [f.name() for f in waternet.fields()]:
                waternet.dataProvider().addAttributes([QgsField(new_field_name, QVariant.Double)])
                waternet.updateFields()
            
            field_idx = waternet.fields().indexOf(new_field_name)
            if field_idx == -1:
                feedback.reportError(f"Error: field {new_field_name} not found in waternet")
                continue

            feedback.pushInfo("Checkpoint C")
            waternet.startEditing()
            for i, feature in enumerate(waternet.getFeatures()):
                # Stop the algorithm if cancel button has been clicked
                if feedback.isCanceled():
                    break
                # set the value for the new field
                value_to_set = float(DataArr[i, 3])
                # set the new field
                feature.setAttribute(field_idx, value_to_set)
                waternet.updateFeature(feature)
            waternet.commitChanges()
            feedback.setProgressText(self.tr(f"{new_field_name} written successfully"))

        if max_iterations_flag:
            feedback.reportError(f"Emergency break: exceeded {max_iterations} iterations")

            # check for duplicate NET_ID values that might be causing the loop
            feedback.reportError(f"Checking for duplicate {id_field} that might cause infinite loops...")

            # collect all NET_ID values
            values = {}
            for f in waternet.getFeatures():
                cid = f[id_field]
                if cid in values:
                    values[cid].append(f.id())
                else:
                    values[cid] = [f.id()]
            
            # report duplicates
            for cid, fids in values.items():
                if len(fids) > 1:
                    feedback.reportError(f"Duplicate NET_ID {cid} found in features {fids}")
                    

        """
        Calculate concentration in each river section
        """

        # conversion factor: from kg/year and m^3/s to ng/L
        # convert m^3/s in L/a
        conversion_flow = 1000*31_536_000 # L in 1 m^3 and second in a year
        # convert kg/a in ng/a
        conversion_load = 1_000_000_000_000
        # total conversion
        conversion_factor = conversion_load / conversion_flow 

        # prepare indices
        idx_mean_flow = waternet.fields().indexOf(acc_MQ_field)
        idx_low_flow = waternet.fields().indexOf(acc_MNQ_field)
        # idx_mean_flow = waternet.fields().indexOf("calc_Mean_")
        # idx_low_flow = waternet.fields().indexOf("calc_M_Low")

        # add new concentration fields if they don't exist
        new_fields = []
        for api_field in selected_api_fields:
            api_short = api_field[:4]
            acc_field = f"acc_{api_short}"
            conc_field_mean = f"conc_{api_short}"
            conc_field_low = f"conL_{api_short}"

            if conc_field_mean not in waternet.fields().names():
                new_fields.append(QgsField(conc_field_mean, QVariant.Double))
            if conc_field_low not in waternet.fields().names():
                new_fields.append(QgsField(conc_field_low, QVariant.Double))

        if new_fields:
            waternet.dataProvider().addAttributes(new_fields)
            waternet.updateFields()

        # calculate concentration values
        waternet.startEditing()
        for feature in waternet.getFeatures():
            flow_mean = feature[idx_mean_flow]
            flow_low = feature[idx_low_flow]

            for api_field in selected_api_fields:
                api_short = api_field[:4]
                acc_field = f"acc_{api_short}"
                acc_value = feature[acc_field]
                
                if acc_value is None:
                    continue

                conc_field_mean = f"conc_{api_short}"
                conc_field_low = f"conL_{api_short}"

                # Calculate mean concentration only if flow_mean is non-zero
                if flow_mean != 0:
                    conc_mean = (acc_value * conversion_factor)/flow_mean
                    feature.setAttribute(conc_field_mean, conc_mean)
                
                # Calculate low concentration only if flow_low is non-zero
                if flow_low != 0:
                    conc_low = (acc_value * conversion_factor)/flow_low
                    feature.setAttribute(conc_field_low, conc_low)

            waternet.updateFeature(feature)
        waternet.commitChanges()

        # prepare the output sink
        # exclude internal per-section fields (MQ_field, MNQ_field) from final output
        export_field_names = [f.name() for f in waternet.fields() if f.name() not in (MQ_field, MNQ_field)]
        export_fields = QgsFields()
        for f in waternet.fields():
            if f.name() in export_field_names:
                export_fields.append(f)

        (sink, dest_id) = self.parameterAsSink(
            parameters,
            self.OUTPUT,
            context,
            export_fields,
            waternet.wkbType(),
            waternet.sourceCrs()
        )

        # add to the sink: copy only export fields
        for feature in waternet.getFeatures():
            out_feat = QgsFeature()
            out_feat.setGeometry(feature.geometry())
            out_feat.setFields(export_fields)
            for fname in export_field_names:
                # get value from original feature
                src_idx = waternet.fields().indexFromName(fname)
                dst_idx = export_fields.indexFromName(fname)
                if src_idx != -1 and dst_idx != -1:
                    out_feat.setAttribute(dst_idx, feature[src_idx])
            sink.addFeature(out_feat)


        if mon_point is not None and mon_point.featureCount() > 0:  # be sure layer exist and is not null
            # get the CRS from load_original layer
            load_crs = load_original.crs()
            # create a new layer, copy of the monitoring station points
            
            if mon_point.crs().authid() != load_crs.authid:
                mon_point_copy = processing.run("native:reprojectlayer", {
                    'INPUT':mon_point,
                    'TARGET_CRS':load_crs,
                    'CONVERT_CURVED_GEOMETRIES':False,
                    'OPERATION':'+proj=noop',
                    'OUTPUT':'TEMPORARY_OUTPUT'})['OUTPUT']
                
            else:
                # get CRS and geometry type
                crs = mon_point.crs().authid()
                geom_type = QgsWkbTypes.displayString(mon_point.wkbType())
                # create memory layer
                mon_point_copy = QgsVectorLayer(f"{geom_type}?crs={crs}", "mon_point_copy", "memory")
                provider = mon_point_copy.dataProvider()
                # copy all fields
                provider.addAttributes(mon_point.fields())
                mon_point_copy.updateFields()
                # copy all features
                features = []
                for feat in mon_point.getFeatures():
                    new_feat = QgsFeature(feat)
                    features.append(new_feat)
                provider.addFeatures(features)
                mon_point_copy.updateExtents()

            # --- Copy concentration values from nearest waternet segments ---
            # Ensure the monitoring layer has concentration and accumulated load fields
            mon_provider = mon_point_copy.dataProvider()
            existing_mon_fields = [f.name() for f in mon_point_copy.fields()]
            new_mon_fields = []
            for api_field in selected_api_fields:
                api_short = api_field[:4]
                conc_mean = f"conc_{api_short}"
                conc_low = f"conL_{api_short}"
                acc_load = f"acc_{api_short}"
                if conc_mean not in existing_mon_fields:
                    new_mon_fields.append(QgsField(conc_mean, QVariant.Double))
                if conc_low not in existing_mon_fields:
                    new_mon_fields.append(QgsField(conc_low, QVariant.Double))
                if acc_load not in existing_mon_fields:
                    new_mon_fields.append(QgsField(acc_load, QVariant.Double))
            if new_mon_fields:
                mon_provider.addAttributes(new_mon_fields)
                mon_point_copy.updateFields()

            # Build spatial index on the (final) river network with concentrations
            tolerance = 500  # meters
            water_index = QgsSpatialIndex(waternet.getFeatures())

            mon_point_copy.startEditing()
            for mon_feat in mon_point_copy.getFeatures():
                if mon_feat.geometry() is None:
                    continue
                mon_geom = mon_feat.geometry()

                # Search candidates within buffered bbox first
                search_rect = mon_geom.boundingBox().buffered(tolerance)
                candidate_ids = water_index.intersects(search_rect)

                # If not enough candidates, ask for nearest neighbors (max 2)
                if len(candidate_ids) < 2:
                    try:
                        pt = mon_geom.asPoint()
                        nn = water_index.nearestNeighbor(pt, 2)
                    except Exception:
                        nn = []
                    # keep order but avoid duplicates
                    for x in nn:
                        if x not in candidate_ids:
                            candidate_ids.append(x)

                # compute distances and pick the closest two (if present)
                candidates = []
                for fid in candidate_ids:
                    try:
                        wfeat = waternet.getFeature(fid)
                    except Exception:
                        wfeat = None
                    if wfeat is None:
                        continue
                    try:
                        dist = wfeat.geometry().distance(mon_geom)
                    except Exception:
                        dist = float('inf')
                    candidates.append((fid, dist))

                if not candidates:
                    continue

                candidates = sorted(candidates, key=lambda x: x[1])

                # Choose the correct river section:
                # - if only one candidate -> pick it
                # - if two and they share the same numeric base NET_ID -> pick the one with the smaller suffix letter
                # - otherwise pick the closest
                chosen_fid = None
                if len(candidates) == 1:
                    chosen_fid = candidates[0][0]
                else:
                    fid1 = candidates[0][0]
                    fid2 = candidates[1][0]
                    f1 = waternet.getFeature(fid1)
                    f2 = waternet.getFeature(fid2)
                    id1 = str(f1[id_field])
                    id2 = str(f2[id_field])
                    base1 = ''.join(filter(str.isdigit, id1))
                    base2 = ''.join(filter(str.isdigit, id2))
                    if base1 == base2:
                        suf1 = id1.replace(base1, "")
                        suf2 = id2.replace(base2, "")
                        # lexicographic compare (empty suffix sorts before letters)
                        if suf1 <= suf2:
                            chosen_fid = fid1
                        else:
                            chosen_fid = fid2
                    else:
                        chosen_fid = candidates[0][0]

                if chosen_fid is None:
                    continue

                chosen_feat = waternet.getFeature(chosen_fid)

                # Copy concentration and accumulated load attributes for each selected API
                for api_field in selected_api_fields:
                    api_short = api_field[:4]
                    conc_mean = f"conc_{api_short}"
                    conc_low = f"conL_{api_short}"
                    acc_load = f"acc_{api_short}"

                    # only set if both source and dest fields exist
                    if conc_mean in [f.name() for f in waternet.fields()] and conc_mean in [f.name() for f in mon_point_copy.fields()]:
                        mon_feat.setAttribute(mon_point_copy.fields().indexFromName(conc_mean), chosen_feat[conc_mean])
                    if conc_low in [f.name() for f in waternet.fields()] and conc_low in [f.name() for f in mon_point_copy.fields()]:
                        mon_feat.setAttribute(mon_point_copy.fields().indexFromName(conc_low), chosen_feat[conc_low])
                    if acc_load in [f.name() for f in waternet.fields()] and acc_load in [f.name() for f in mon_point_copy.fields()]:
                        mon_feat.setAttribute(mon_point_copy.fields().indexFromName(acc_load), chosen_feat[acc_load])

                mon_point_copy.updateFeature(mon_feat)
            mon_point_copy.commitChanges()

            # prepare the output sink for monitoring points
            (mon_sink, mon_dest_id) = self.parameterAsSink(
                parameters,
                self.OUTPUT_mon,
                context,
                mon_point_copy.fields(),
                mon_point_copy.wkbType(),
                mon_point_copy.sourceCrs()
            )

            # add to the sink if a sink was created; otherwise warn the user
            if mon_sink is None:
                feedback.pushWarning(
                    "\nMonitoring output is set to 'Skip output'. Monitoring point results will not be saved. "
                    "Choose 'Save to temporary layer' or provide a file to store monitoring results.\n"
                )
                # return only the river output
                return {self.OUTPUT: dest_id}
            else:
                for feature in mon_point_copy.getFeatures():
                    mon_sink.addFeature(feature)

                return {self.OUTPUT_mon: mon_dest_id,
                        self.OUTPUT: dest_id}
            
        else:
            if mon_point is not None: # layer exists but is empty
                feedback.pushWarning("\nMonitoring point layer provided but has no features, ignoring it...\n")

        return {self.OUTPUT: dest_id}

    
    
    def name(self):
        """
        Returns the algorithm name, used for identifying the algorithm. This
        string should be fixed for the algorithm, and must not be localised.
        The name should be unique within each provider. Names should contain
        lowercase alphanumeric characters only and no spaces or other
        formatting characters.
        """
        return '7 - Accumulation'

    def displayName(self):
        """
        Returns the translated algorithm name, which should be used for any
        user-visible display of the algorithm name.
        """
        return self.tr(self.name())

    def group(self):
        """
        Returns the name of the group this algorithm belongs to. This string
        should be localised.
        """
        return self.tr(self.groupId())

    def groupId(self):
        """
        Returns the unique ID of the group this algorithm belongs to. This
        string should be fixed for the algorithm, and must not be localised.
        The group id should be unique within each provider. Group id should
        contain lowercase alphanumeric characters only and no spaces or other
        formatting characters.
        """
        return 'API emission'
    
    def helpUrl(self):
        # Return a URL or local file path to your documentation
        return "https://hosting-apriora-manual.readthedocs.io/en/latest/Accumulation.html"

    def tr(self, string):
        return QCoreApplication.translate('Processing', string)

    def createInstance(self):
        return Accumulation()