# -*- coding: utf-8 -*-

"""
/***************************************************************************
 APRIORA
                                 A QGIS plugin
 Collection of APRIORA Plugins
 Generated by Plugin Builder: http://g-sherman.github.io/Qgis-Plugin-Builder/
                              -------------------
        begin                : 2024-06-13
        copyright            : (C) 2024 by Universität Rostock
        email                : cristiano.guidi2@uni-rostock.de
 ***************************************************************************/

/***************************************************************************
 *                                                                         *
 *   This program is free software; you can redistribute it and/or modify  *
 *   it under the terms of the GNU General Public License as published by  *
 *   the Free Software Foundation; either version 2 of the License, or     *
 *   (at your option) any later version.                                   *
 *                                                                         *
 ***************************************************************************/
"""

__author__ = 'Cristiano Guidi'
__date__ = '2024-06-13'
__copyright__ = '(C) 2024 by Universität Rostock'

# This will get replaced with a git SHA1 when you do a git archive

__revision__ = '$Format:%H$'

import processing
from PyQt5.QtCore import QVariant
from qgis.PyQt.QtCore import QCoreApplication, Qt, QDir, QVariant
from qgis.core import (QgsProcessingAlgorithm,
                       QgsProcessing,
                       QgsProcessingException,
                       QgsFeature,
                       QgsField,
                       QgsFields,
                       QgsFeatureSink,
                       QgsGeometry,
                       QgsProject,
                       QgsProcessingAlgorithm,
                       QgsProcessingParameterDefinition,
                       QgsProcessingParameterEnum,
                       QgsProcessingParameterFeatureSource,
                       QgsProcessingParameterFeatureSink,
                       QgsProcessingParameterField,
                       QgsProcessingParameterNumber,
                       QgsField,
                       QgsSpatialIndex,
                       QgsVectorLayer,
                       edit)


class Accumulation(QgsProcessingAlgorithm):

    # Constants used to refer to parameters and outputs. They will be
    # used when calling the algorithm from another algorithm, or when
    # calling from the QGIS console.

    APIload = 'APIload'
    selectedAPI = 'selectedAPI'
    riverNetwork = 'RiverNetwork'
    OUTPUT = 'OUTPUT'

    def shortHelpString(self):
        return self.tr(""" This tool calculates the concentration of certain APIs (Active Pharmaceutical Ingredients) at the emission points and how they accumulate in a river network.
        """)

    #Init tool
    def initAlgorithm(self, config):
        """
        Here we define the inputs and output of the algorithm, along
        with some other properties.
        """
        self.addParameter(
            QgsProcessingParameterFeatureSource(
                self.APIload,
                self.tr('API Load'),
                [QgsProcessing.TypeVectorPoint]
            )
        )

        self.addParameter(
            QgsProcessingParameterField(
                self.selectedAPI,
                self.tr('Select APIs to accumulate'),
                parentLayerParameterName = self.APIload,
                allowMultiple = True,
                type=QgsProcessingParameterField.Any
            )
        )

        self.addParameter(
            QgsProcessingParameterFeatureSource(
                self.riverNetwork,
                self.tr('River network'),
                [QgsProcessing.TypeVectorLine]
            )
        )


        # add as input to specify Mean Flow and Mean Low Flow


        # We add a feature sink in which to store our processed features (this
        # usually takes the form of a newly created vector layer when the
        # algorithm is run in QGIS).
        self.addParameter(
            QgsProcessingParameterFeatureSink(
                self.OUTPUT,
                self.tr('River accumulation'),
                QgsProcessing.TypeVectorLine
            )
        )

    def processAlgorithm(self, parameters, context, feedback):
        """
        Here is where the processing itself takes place.
        """
        selected_api_fields = self.parameterAsFields(parameters, self.selectedAPI, context)
        river_layer = self.parameterAsVectorLayer(parameters, self.riverNetwork, context)
        load = self.parameterAsVectorLayer(parameters, self.APIload, context)

        '''loading the network'''
        feedback.setProgressText(self.tr("Loading network..\n "))
        waternet = river_layer
        waterFt = waternet.getFeatures()

        
        
        
        def find_closest_river_section(emission_point, spatial_index, river_map, feedback):
            """
            Find closest river section to emission point
            """
            emission_point_geometry = QgsGeometry.fromPointXY(emission_point)
            nearest_ids = spatial_index.nearestNeighbor(emission_point_geometry, 5)
            closest_section = None
            min_distance = float("inf")

            # iterate through the closest matches and find the closest section
            for fid in nearest_ids:
                feature = river_map[fid]
                section_geom = feature.geometry()
                distance = section_geom.distance(emission_point_geometry)

                if distance < min_distance:
                    min_distance = distance
                    closest_section = feature

            if closest_section:
                feedback.pushInfo(f"\nClosest section found: [CATCH_ID]: {closest_section['CATCH_ID']} \n Distance: {min_distance}")
            else:
                feedback.pushInfo("\nNo closest section found.")

            return closest_section


        # build a spatial index
        spatial_index = QgsSpatialIndex()
        river_map = {}

        for feature in waternet.getFeatures():
            fid = feature.id()
            river_map[fid] = QgsFeature(feature)
            spatial_index.insertFeature(feature)

        # prepare data storage for accumulation
        for f in river_map.values():
            for api in selected_api_fields:
                f.setAttribute(api, 0.0)

        # process each emission point
        for point_feat in load.getFeatures():
            closest_river = find_closest_river_section(point_feat, spatial_index, river_map, feedback)
            
            if closest_river:
                rid = closest_river.id()
                target_feat = river_map[rid]
                for api in selected_api_fields:
                    value = point_feat[api]
                    current_value = target_feat[api] or 0.0
                    target_feat.setAttribute(api, current_value + value)

        







        # prepare the output sink
        (sink, dest_id) = self.parameterAsSink(
            parameters,
            self.OUTPUT,
            context,
            list(waternet.fields()),
            waternet.wkbType(),
            waternet.sourceCrs()
        )

        for feat in river_map.values():
            sink.addFeature(feat, QgsFeatureSink.FastInsert)

        return {self.OUTPUT: dest_id}

    
    
    def name(self):
        """
        Returns the algorithm name, used for identifying the algorithm. This
        string should be fixed for the algorithm, and must not be localised.
        The name should be unique within each provider. Names should contain
        lowercase alphanumeric characters only and no spaces or other
        formatting characters.
        """
        return '6 - Accumulation'

    def displayName(self):
        """
        Returns the translated algorithm name, which should be used for any
        user-visible display of the algorithm name.
        """
        return self.tr(self.name())

    def group(self):
        """
        Returns the name of the group this algorithm belongs to. This string
        should be localised.
        """
        return self.tr(self.groupId())

    def groupId(self):
        """
        Returns the unique ID of the group this algorithm belongs to. This
        string should be fixed for the algorithm, and must not be localised.
        The group id should be unique within each provider. Group id should
        contain lowercase alphanumeric characters only and no spaces or other
        formatting characters.
        """
        return 'API emission'

    def tr(self, string):
        return QCoreApplication.translate('Processing', string)

    def createInstance(self):
        return Accumulation()