# -*- coding: utf-8 -*-

"""
/***************************************************************************
 APRIORA
                                 A QGIS plugin
 Collection of APRIORA Plugins
 Generated by Plugin Builder: http://g-sherman.github.io/Qgis-Plugin-Builder/
                              -------------------
        begin                : 2024-06-13
        copyright            : (C) 2024 by Cristiano Guidi
        email                : cristiano.guidi2@uni-rostock.de
 ***************************************************************************/

/***************************************************************************
 *                                                                         *
 *   This program is free software; you can redistribute it and/or modify  *
 *   it under the terms of the GNU General Public License as published by  *
 *   the Free Software Foundation; either version 2 of the License, or     *
 *   (at your option) any later version.                                   *
 *                                                                         *
 ***************************************************************************/
"""

__author__ = 'Cristiano Guidi'
__date__ = '2024-06-13'
__copyright__ = '(C) 2024 by Cristiano Guidi'

__revision__ = '$Format:%H$'

import os
import pandas as pd

from qgis.PyQt.QtCore import QCoreApplication, Qt, QUrl
from qgis.PyQt.QtWidgets import QMessageBox
from qgis.PyQt import uic, QtWidgets
from qgis.core import (
    QgsProcessingAlgorithm,
    QgsProject, 
    QgsMapLayer, 
    QgsVectorLayer,
    QgsWkbTypes
)
from PyQt5.QtWidgets import QStyle, QAbstractItemView, QMenu, QAction
from PyQt5.QtGui import QStandardItemModel, QStandardItem, QDesktopServices

# This loads your .ui file so that PyQt can populate your plugin with the elements from Qt Designer
FORM_CLASS, _ = uic.loadUiType(os.path.join(
    os.path.dirname(__file__), 'api_parameter_selection_base.ui'))


class APIParameterSelectionAlgorithm(QgsProcessingAlgorithm):
    """
    Processing algorithm that opens the Consumption Selection Dialog.
    This allows Tool 5 to be accessed from the Processing Toolbox.
    """

    def name(self):
        return '5 - API parameter selection'

    def displayName(self):
        return self.tr(self.name())

    def group(self):
        return self.tr(self.groupId())

    def groupId(self):
        return 'API emission'

    def shortHelpString(self):
        return self.tr("""
            This tool allows you to configure and select Active Pharmaceutical Ingredients (APIs) \
            to be used in the emission load calculations.
            
            Features:
            - Select APIs and their associated parameters from the consumption database
            - Customize consumption data, removal rates, and PNEC values
            - Create custom datasets specific to your study area
            - Configure a custom WWTP table for emission load calculations
            
            Tabs:
            1. Consumption Data - Select APIs and their consumption rates
            2. Removal Rates - Configure technical class-specific removal rates
            3. PNEC Values - Set Predicted No Effect Concentrations for risk assessment
            4. WWTP locations - Create a custom WWTP table with your selected APIs
            
            
            IMPORTANT: This tool must be run BEFORE using the '6 - Emission Loads' tool. \
            The selections made here will be used by the emission loads calculation.
        """)

    def initAlgorithm(self, config):
        """
        No parameters needed - this is a pure UI tool.
        """
        pass

    def processAlgorithm(self, parameters, context, feedback):
        """
        This method is called when the algorithm runs.
        We open the consumption dialog here.
        """
        try:
            # Get the main QGIS window
            from qgis.utils import iface
            
            # Create and show the dialog (now in same file)
            dialog = ConsumptionSelectionDialog(iface.mainWindow())
            result = dialog.exec_()
            
            feedback.pushInfo("API Parameter Selection tool opened and closed.")
            
        except Exception as e:
            feedback.reportError(f"Error opening API Parameter Selection: {str(e)}")
            import traceback
            traceback.print_exc()
        
        return {}

    def helpUrl(self):
        return "https://hosting-apriora-manual.readthedocs.io/en/latest/Consumption.html"

    def tr(self, string):
        return QCoreApplication.translate('Processing', string)

    def createInstance(self):
        return APIParameterSelectionAlgorithm()


# ============================================================================
# ConsumptionSelectionDialog - The main dialog for API parameter selection
# ============================================================================


class ConsumptionSelectionDialog(QtWidgets.QDialog, FORM_CLASS):

    def _get_selection_view(self):
        """
        Return the selection view widget from the UI.
        Supports both the new name (listView) and the previous one (selectionListWidget).
        """
        if hasattr(self, "listView"):
            return self.listView
        if hasattr(self, "selectionListWidget"):
            return self.selectionListWidget
        return None

    def _update_progress_by_tab(self):
        """
        Update progressBar according to the current tab and PNEC subtab.
        Progress steps: Consumption(20) -> Removal(40) -> PNEC ERA(50)/HH(60)/AMR(70) -> WWTP locations(80).
        100% is set after printing.
        """
        if not hasattr(self, "progressBar") or not hasattr(self, "tabWidget"):
            return

        current_idx = self.tabWidget.currentIndex()
        current_title = self.tabWidget.tabText(current_idx).strip().lower()

        if "consumption" in current_title:
            value = 20
        elif "removal" in current_title:
            value = 40
        elif "pnec" in current_title:
            # Sub-progress based on PNEC subtab
            if hasattr(self, "tabWidget_2"):
                sub_idx = self.tabWidget_2.currentIndex()
                value = 50 + sub_idx * 10  # ERA=50, HH=60, AMR=70
            else:
                value = 60
        elif "wwtp" in current_title:
            value = 80
        else:
            value = 0

        self.progressBar.setValue(value)

    def _update_navigation_buttons(self):
        """
        Enable/disable back and next buttons at tab boundaries,
        and PNEC subtab back/next buttons.
        """
        if not hasattr(self, "tabWidget"):
            return

        current_idx = self.tabWidget.currentIndex()
        last_idx = self.tabWidget.count() - 1

        if hasattr(self, "backButton"):
            self.backButton.setEnabled(current_idx > 0)
        if hasattr(self, "nextButton"):
            self.nextButton.setEnabled(current_idx < last_idx)

        # PNEC subtab navigation buttons
        self._update_pnec_navigation_buttons()

    def _on_tab_changed(self, new_idx):
        """
        Called whenever the main tab changes (click, back/next).
        Saves the tab we are *leaving*, then updates progress.
        """
        self._save_tab_by_index(self._previous_tab_idx)
        self._previous_tab_idx = new_idx
        self._update_progress_by_tab()

    def _save_tab_by_index(self, idx):
        """Save a specific tab by its index."""
        if idx == 0:
            self.handle_save_consumption()
        elif idx == 1:
            self.handle_save_rr()
        elif idx == 2:
            self.handle_save_pnec()
        elif idx == 3 and hasattr(self, "wwtpTableView"):
            if self.wwtpTableView.model() is not None:
                self.save_wwtp_table_to_csv()

    def go_to_next_tab(self):
        """
        Move user to the next tab and refresh progress.
        """
        if not hasattr(self, "tabWidget"):
            return

        current_idx = self.tabWidget.currentIndex()
        if current_idx < self.tabWidget.count() - 1:
            self.tabWidget.setCurrentIndex(current_idx + 1)
        self._update_progress_by_tab()
        self._update_navigation_buttons()

    def go_to_previous_tab(self):
        """
        Move user to the previous tab and refresh progress.
        """
        if not hasattr(self, "tabWidget"):
            return

        current_idx = self.tabWidget.currentIndex()
        if current_idx > 0:
            self.tabWidget.setCurrentIndex(current_idx - 1)
        self._update_progress_by_tab()
        self._update_navigation_buttons()

    def _update_pnec_navigation_buttons(self):
        """
        Enable/disable PNEC subtab back/next buttons.
        Back disabled on ERA (index 0), Next disabled on AMR (last index).
        """
        if not hasattr(self, "tabWidget_2"):
            return
        sub_idx = self.tabWidget_2.currentIndex()
        last_sub = self.tabWidget_2.count() - 1
        if hasattr(self, "backButton_PNEC"):
            self.backButton_PNEC.setEnabled(sub_idx > 0)
        if hasattr(self, "nextButton_PNEC"):
            self.nextButton_PNEC.setEnabled(sub_idx < last_sub)

    def go_to_next_pnec_tab(self):
        if not hasattr(self, "tabWidget_2"):
            return
        sub_idx = self.tabWidget_2.currentIndex()
        if sub_idx < self.tabWidget_2.count() - 1:
            self.tabWidget_2.setCurrentIndex(sub_idx + 1)
        self._update_pnec_navigation_buttons()
        self._update_progress_by_tab()

    def go_to_previous_pnec_tab(self):
        if not hasattr(self, "tabWidget_2"):
            return
        sub_idx = self.tabWidget_2.currentIndex()
        if sub_idx > 0:
            self.tabWidget_2.setCurrentIndex(sub_idx - 1)
        self._update_pnec_navigation_buttons()
        self._update_progress_by_tab()

    def clear_selection(self):
        """
        Remove all substances from the selection list.
        """
        self.selection_model.clear()
        self.save_selection_to_file()

    def save_current_tab(self):
        """
        Save the currently active tab before switching to another one.
        """
        if not hasattr(self, "tabWidget"):
            return
        self._save_tab_by_index(self.tabWidget.currentIndex())

    def handle_save_pnec(self):
        """
        Save all three PNEC sub-tables to their custom CSV files.
        """
        self.save_temp_table(self.ERATableView, "PNEC_ERA_")
        self.save_temp_table(self.HHTableView, "PNEC_HH_")
        self.save_temp_table(self.AMRTableView, "PNEC_AMR_")
        # Keep in-memory dataframes in sync
        era_path = os.path.join(os.path.dirname(__file__), "datasets/custom_dataset/PNEC_ERA_.csv")
        hh_path = os.path.join(os.path.dirname(__file__), "datasets/custom_dataset/PNEC_HH_.csv")
        amr_path = os.path.join(os.path.dirname(__file__), "datasets/custom_dataset/PNEC_AMR_.csv")
        if os.path.exists(era_path):
            self.df_ERA = pd.read_csv(era_path, sep=",")
        if os.path.exists(hh_path):
            self.df_HH = pd.read_csv(hh_path, sep=",")
        if os.path.exists(amr_path):
            self.df_AMR = pd.read_csv(amr_path, sep=",")

        # Auto-propagate substances across the three PNEC sub-tables
        self._propagate_pnec_substances()
        self.pnec_modified = False
    
    def _propagate_pnec_substances(self):
        """
        Ensure every API name that appears in any PNEC sub-table also
        appears in the other two (with empty values).  Does NOT touch
        Removal Rates or Consumption.
        """
        era_apis = set(self.df_ERA["API name"].unique())
        hh_apis = set(self.df_HH["API name"].unique())
        amr_apis = set(self.df_AMR["API name"].unique())
        all_apis = era_apis | hh_apis | amr_apis

        changed = False
        for df_attr, current_apis in [("df_ERA", era_apis),
                                       ("df_HH", hh_apis),
                                       ("df_AMR", amr_apis)]:
            missing = all_apis - current_apis
            if not missing:
                continue
            df = getattr(self, df_attr)
            for api_name in missing:
                new_row = {col: "" for col in df.columns}
                new_row["API name"] = api_name
                df = pd.concat([df, pd.DataFrame([new_row])], ignore_index=True)
            setattr(self, df_attr, df)
            changed = True

        if changed:
            self.load_table(self.df_ERA, self.ERATableView)
            self.save_temp_table(self.ERATableView, "PNEC_ERA_")
            self.load_table(self.df_HH, self.HHTableView)
            self.save_temp_table(self.HHTableView, "PNEC_HH_")
            self.load_table(self.df_AMR, self.AMRTableView)
            self.save_temp_table(self.AMRTableView, "PNEC_AMR_")

    def close_with_save(self):
        """
        Save the current tab before closing the dialog.
        """
        self.save_current_tab()
        self.save_field_selection()
        self.close()
    
    def get_dataset_path(self, original_filename, custom_filename):
        """
        Return the path to the dataset
        If a custom file exists, return that.
        Otherwise return the original file.
        """
        plugin_dir = os.path.dirname(__file__)
        custom_path = os.path.join(plugin_dir, "datasets/custom_dataset", custom_filename)
        original_path = os.path.join(plugin_dir, "datasets/original_dataset", original_filename)

        if os.path.exists(custom_path):
            return custom_path, True    # True = custom file is being used
        else:
            return original_path, False
        
    def load_selection_from_file(self):
        plugin_dir = os.path.dirname(__file__)
        file_path = os.path.join(plugin_dir, "user_selection.txt")

        if os.path.exists(file_path):
            with open(file_path, "r") as file:
                for line in file:
                    line = line.strip()
                    if line:
                        self.selection_model.appendRow(QStandardItem(line))

    def save_field_selection(self):
        """Persist the WWTP layer name and field combo selections to a text file."""
        plugin_dir = os.path.dirname(__file__)
        path = os.path.join(plugin_dir, "field_selection.txt")
        with open(path, "w") as f:
            f.write(f"layer={self.WWTPcomboBox.currentText()}\n")
            f.write(f"id_field={self.IDcomboBox.currentText()}\n")
            f.write(f"name_field={self.NamecomboBox.currentText()}\n")
            f.write(f"tc_field={self.TCcomboBox.currentText()}\n")

    def load_field_selection(self):
        """Restore saved WWTP layer and field combo selections from text file."""
        plugin_dir = os.path.dirname(__file__)
        path = os.path.join(plugin_dir, "field_selection.txt")
        if not os.path.exists(path):
            return
        try:
            data = {}
            with open(path, "r") as f:
                for line in f:
                    line = line.strip()
                    if "=" in line:
                        key, value = line.split("=", 1)
                        data[key] = value
        except OSError:
            return

        # Restore layer selection
        layer_name = data.get("layer", "")
        idx = self.WWTPcomboBox.findText(layer_name)
        if idx >= 0:
            self.WWTPcomboBox.setCurrentIndex(idx)
            self.update_field_combos()

            # Restore field selections
            for combo, key in [
                (self.IDcomboBox, "id_field"),
                (self.NamecomboBox, "name_field"),
                (self.TCcomboBox, "tc_field"),
            ]:
                val = data.get(key, "")
                fi = combo.findText(val)
                if fi >= 0:
                    combo.setCurrentIndex(fi)

    def load_table(self, df, table_view):
        """
        Load dataframe to specified table view
        
        df: pandas DataFrame
        table_view: Target QTableView object
        """
        try:
            model = QStandardItemModel()
            model.setHorizontalHeaderLabels(df.columns.astype(str).tolist())

            for row in df.itertuples(index=False):
                items = []
                for val in row:
                    item = QStandardItem(str(val))
                    items.append(item)
                model.appendRow(items)
            
            # set the table model
            table_view.setModel(model)

        except Exception as e:
            QMessageBox.critical(self, "Error", f"Could not load CSV data: {e}")
    
    
    def __init__(self, parent=None):
        """Constructor."""
        super(ConsumptionSelectionDialog, self).__init__(parent)
        self.setupUi(self)
        # set a reload icon
        self.reloadButton_3.setIcon(self.style().standardIcon(QStyle.SP_BrowserReload))
        # Modification tracking flags for each table
        self.consumption_modified = False
        self.removal_modified = False
        self.pnec_modified = False

        # Selection view model (QListView)
        self.selection_model = QStandardItemModel()
        self.selection_view = self._get_selection_view()
        if self.selection_view is None:
            QMessageBox.critical(self, "Error", "Selection view not found in UI.")
            return
        self.selection_view.setModel(self.selection_model)
        self.selection_view.setSelectionMode(QAbstractItemView.ExtendedSelection)

        # Progress bar setup
        if hasattr(self, "progressBar"):
            self.progressBar.setMinimum(0)
            self.progressBar.setMaximum(100)
            self.progressBar.setValue(0)
        # directory of the databases
        csv_file, self.temp_cons = self.get_dataset_path("consumption_dataset.csv", "consumption_.csv")
        RR_file, self.temp_rr = self.get_dataset_path("removal_rates.csv", "removal_.csv")
        ERA_file, self.temp_era = self.get_dataset_path("PNEC ERA.csv", "PNEC_ERA_.csv")
        HH_file, self.temp_hh = self.get_dataset_path("PNEC HHRA.csv", "PNEC_HH_.csv")
        AMR_file, self.temp_amr = self.get_dataset_path("PNEC AMR-RA.csv", "PNEC_AMR_.csv")

        try:
            # consumption data
            self.df = pd.read_csv(csv_file, sep=",")
            self.load_table(self.df, self.excelTableView)
            # Strip (*) mandatory markers from DataFrame columns for clean code access
            self.df.columns = [c.replace(' (*)', '') for c in self.df.columns]
            # enable full-row selection so the user can highlight rows to add
            self.excelTableView.setSelectionBehavior(QAbstractItemView.SelectRows)
            self.excelTableView.setSelectionMode(QAbstractItemView.ExtendedSelection)
            # removal rate
            self.df_RR = pd.read_csv(RR_file, sep=",")
            self.load_table(self.df_RR, self.RRTableView)
            # PNEC tables
            self.df_ERA = pd.read_csv(ERA_file, sep=",")
            self.load_table(self.df_ERA, self.ERATableView)
            self.df_HH = pd.read_csv(HH_file, sep=",")
            self.load_table(self.df_HH, self.HHTableView)
            self.df_AMR = pd.read_csv(AMR_file, sep=",")
            self.load_table(self.df_AMR, self.AMRTableView)
            # populate country combo from HHRA columns (skip 'API name')
            if hasattr(self, "CountrycomboBox"):
                self.CountrycomboBox.clear()
                self.CountrycomboBox.addItems([c.strip() for c in self.df_HH.columns[1:]])

        except Exception as e:
            QMessageBox.critical(self, "Error", f"Could not read Excel file: {e}")
            return

        # Connect signals
        # tab 1 - Consumption
        self.load_selection_from_file()
        self.addSelectionButton.clicked.connect(self.add_selection)
        self.removeSelectionButton.clicked.connect(self.remove_selected_item)
        self.ClearpushButton.clicked.connect(self.clear_selection)
        self.closeButton.clicked.connect(self.close_with_save)
        if hasattr(self, "backButton"):
            self.backButton.clicked.connect(self.go_to_previous_tab)
        if hasattr(self, "nextButton"):
            self.nextButton.clicked.connect(self.go_to_next_tab)
        self.addButton_tab1.clicked.connect(lambda: self.add_row_to_table(self.excelTableView))
        self.removeButton_tab1.clicked.connect(lambda: self.remove_selected_row(self.excelTableView))
        self.restoreButton_1.clicked.connect(
            lambda: self.restore_original(
                "consumption_dataset.csv", "consumption_.csv", self.load_table, self.excelTableView
            )
        )
        self.help_tab1.clicked.connect(
            lambda: QDesktopServices.openUrl(
                QUrl("https://hosting-apriora-manual.readthedocs.io/en/latest/api_emission/API_param_selection.html#consumption-data")
                )
            )
        
        # tab 2 - Removal rate
        self.addButton_tab2.clicked.connect(lambda: self.add_row_to_table(self.RRTableView))
        self.removeButton_tab2.clicked.connect(lambda: self.remove_selected_row(self.RRTableView))
        self.restoreButton_2.clicked.connect(
            lambda: self.restore_original(
                "removal_rates.csv", "removal_.csv", self.load_table, self.RRTableView
            )
        )
        self.help_tab2.clicked.connect(
            lambda: QDesktopServices.openUrl(
                QUrl("https://hosting-apriora-manual.readthedocs.io/en/latest/api_emission/API_param_selection.html#removal-rate")
                )
            )

        # tab 3 - PNEC subtabs (ERA, HH, AMR)
        self.addButton_ERA.clicked.connect(lambda: self.add_row_to_table(self.ERATableView))
        self.removeButton_ERA.clicked.connect(lambda: self.remove_selected_row(self.ERATableView))
        self.restoreButton_ERA.clicked.connect(
            lambda: self.restore_original(
                "PNEC ERA.csv", "PNEC_ERA_.csv", self.load_table, self.ERATableView
            )
        )
        self.help_ERA.clicked.connect(
            lambda: QDesktopServices.openUrl(
                QUrl("https://hosting-apriora-manual.readthedocs.io/en/latest/api_emission/API_param_selection.html#pnec-values")
                )
            )

        self.addButton_HH.clicked.connect(lambda: self.add_row_to_table(self.HHTableView))
        self.removeButton_HH.clicked.connect(lambda: self.remove_selected_row(self.HHTableView))
        self.restoreButton_HH.clicked.connect(
            lambda: self.restore_original(
                "PNEC HHRA.csv", "PNEC_HH_.csv", self.load_table, self.HHTableView
            )
        )
        self.help_HH.clicked.connect(
            lambda: QDesktopServices.openUrl(
                QUrl("https://hosting-apriora-manual.readthedocs.io/en/latest/api_emission/API_param_selection.html#pnec-values")
                )
            )

        self.addButton_AMR.clicked.connect(lambda: self.add_row_to_table(self.AMRTableView))
        self.removeButton_AMR.clicked.connect(lambda: self.remove_selected_row(self.AMRTableView))
        self.restoreButton_AMR.clicked.connect(
            lambda: self.restore_original(
                "PNEC AMR-RA.csv", "PNEC_AMR_.csv", self.load_table, self.AMRTableView
            )
        )
        self.help_AMR.clicked.connect(
            lambda: QDesktopServices.openUrl(
                QUrl("https://hosting-apriora-manual.readthedocs.io/en/latest/api_emission/API_param_selection.html#pnec-values")
                )
            )

        if hasattr(self, "backButton_PNEC"):
            self.backButton_PNEC.clicked.connect(self.go_to_previous_pnec_tab)
        if hasattr(self, "nextButton_PNEC"):
            self.nextButton_PNEC.clicked.connect(self.go_to_next_pnec_tab)

        # tab 4 - WWTP locations
        self.WWTPcomboBox.currentIndexChanged.connect(self.update_field_combos)
        self.loadButton.clicked.connect(self.load_wwtp_table)
        self.populate_layer_combo()
        self.reloadButton_3.clicked.connect(self.populate_layer_combo)
        self.restoreButton_3.clicked.connect(self.load_wwtp_table)
        self.help_tab3.clicked.connect(
            lambda: QDesktopServices.openUrl(
                QUrl("https://hosting-apriora-manual.readthedocs.io/en/latest/api_emission/API_param_selection.html#wwtp-locations")
                )
            )
        if hasattr(self, "printButton"):
            self.printButton.clicked.connect(self.print_tables)

        # Tab 1 - Consumption export/import menu
        if hasattr(self, "exportMenuButton_tab1"):
            menu1 = QMenu(self)
            menu1.addAction(QAction("Export table (for sharing only)", self,
                triggered=lambda: self._export_table_for_sharing(
                    self.excelTableView, "consumption_sharing.csv")))
            menu1.addAction(QAction("Import external consumption table", self,
                triggered=self._import_external_consumption))
            self.exportMenuButton_tab1.setMenu(menu1)
            self.exportMenuButton_tab1.setPopupMode(
                self.exportMenuButton_tab1.InstantPopup
            )

        # Tab 2 - Removal rate export/import menu
        if hasattr(self, "exportMenuButton_tab2"):
            menu2 = QMenu(self)
            menu2.addAction(QAction("Export table (for sharing only)", self,
                triggered=lambda: self._export_table_for_sharing(
                    self.RRTableView, "removal_rates_sharing.csv")))
            menu2.addAction(QAction("Import external removal rate table", self,
                triggered=self._import_external_rr))
            self.exportMenuButton_tab2.setMenu(menu2)
            self.exportMenuButton_tab2.setPopupMode(
                self.exportMenuButton_tab2.InstantPopup
            )

        # Tab 3 - PNEC export button
        if hasattr(self, "exportPNECtable"):
            self.exportPNECtable.clicked.connect(self.export_pnec_table)

        # Keep progress synced with manual tab navigation
        self._previous_tab_idx = 0
        if hasattr(self, "tabWidget"):
            self.tabWidget.currentChanged.connect(self._on_tab_changed)
            self.tabWidget.currentChanged.connect(lambda _: self._update_navigation_buttons())
        if hasattr(self, "tabWidget_2"):
            self.tabWidget_2.currentChanged.connect(lambda _: self._update_progress_by_tab())
            self.tabWidget_2.currentChanged.connect(lambda _: self._update_pnec_navigation_buttons())
        self._update_progress_by_tab()
        self._update_navigation_buttons()

        # Restore saved field selections (layer + ID/Name/TC combos)
        self.load_field_selection()




    """
    Tab 1 - Consumption data
    """

    def add_selection(self):

        # save the consumption table first so self.df captures any edits
        self.temp_consumption_path = self.save_temp_table(self.excelTableView, "consumption_")
        self.df = pd.read_csv(self.temp_consumption_path, sep=",")
        self.df.columns = [c.replace(' (*)', '') for c in self.df.columns]
        self.propagate_substances_from_consumption()
        self.consumption_modified = False

        model = self.excelTableView.model()
        selection = self.excelTableView.selectionModel().selectedRows()

        if not selection:
            QMessageBox.warning(self, "No selection", "Please highlight one or more rows in the table before adding.")
            return

        # find column indices for the required fields
        headers = [model.headerData(col, Qt.Horizontal) for col in range(model.columnCount())]
        headers = [h.replace(' (*)', '') if h else h for h in headers]
        required = ["API name", "year", "country", "region", "Excreted emission (mg/inh./a)"]
        col_indices = {}
        for field in required:
            if field in headers:
                col_indices[field] = headers.index(field)
            else:
                QMessageBox.critical(self, "Error", f"Column '{field}' not found in the table.")
                return

        added = 0
        skipped_missing = []  # rows skipped due to missing fields
        skipped_duplicate = 0
        mandatory_keys = ["API name", "year", "country", "region"]

        for idx in selection:
            row = idx.row()
            values = {field: str(model.index(row, col_indices[field]).data() or "").strip()
                      for field in required}

            # check which mandatory fields are missing
            missing = [f for f in mandatory_keys if not values[f]]
            if missing:
                skipped_missing.append((row + 1, missing))
                continue

            text = (f"{values['API name']}, {values['year']}, {values['country']}, "
                    f"{values['region']}, {values['Excreted emission (mg/inh./a)']}")

            # avoid duplicates (compare on API name + year + country + region)
            key = f"{values['API name']}, {values['year']}, {values['country']}, {values['region']}"
            duplicate = False
            for i in range(self.selection_model.rowCount()):
                existing = self.selection_model.item(i).text()
                existing_key = ", ".join(existing.split(", ")[:4])
                if existing_key == key:
                    duplicate = True
                    break
            if duplicate:
                skipped_duplicate += 1
            else:
                self.selection_model.appendRow(QStandardItem(text))
                added += 1

        if added == 0 and not skipped_missing and skipped_duplicate > 0:
            QMessageBox.information(self, "No new items", "All highlighted rows are already in the selection.")
        elif skipped_missing:
            details = "\n".join(
                f"  Row {r}: missing {', '.join(fields)}" for r, fields in skipped_missing
            )
            QMessageBox.warning(
                self, "Missing fields",
                f"Some rows could not be added because mandatory fields are empty:\n\n{details}\n\n"
                f"Please fill in: API name, year, country, region."
            )
        if added > 0:
            self.save_selection_to_file()

    def remove_selected_item(self):
        selected_rows = self.selection_view.selectionModel().selectedRows()
        for idx in sorted(selected_rows, key=lambda x: x.row(), reverse=True):
            self.selection_model.removeRow(idx.row())
        self.save_selection_to_file()

    def add_row_to_table(self, table_view):
        model = table_view.model()
        if model:
            cols = model.columnCount()
            new_items = [QStandardItem("") for _ in range(cols)]
            for item in new_items:
                item.setFlags(item.flags() | Qt.ItemIsEditable)
            model.appendRow(new_items)
            # Set modification flag based on which table was modified
            if table_view == self.excelTableView:
                self.consumption_modified = True
            elif table_view == self.RRTableView:
                self.removal_modified = True
            elif table_view in (self.ERATableView, self.HHTableView, self.AMRTableView):
                self.pnec_modified = True

    def remove_selected_row(self, table_view):
        model = table_view.model()
        selection = table_view.selectionModel().selectedRows()
        for index in sorted(selection, reverse = True):
            model.removeRow(index.row())
        # Set modification flag based on which table was modified
        if table_view == self.excelTableView:
            self.consumption_modified = True
        elif table_view == self.RRTableView:
            self.removal_modified = True
        elif table_view in (self.ERATableView, self.HHTableView, self.AMRTableView):
            self.pnec_modified = True

    def save_temp_table(self, table_view, name):
        model = table_view.model()
        if model is None:
            return None

        headers = [model.headerData(col, Qt.Horizontal) for col in range(model.columnCount())]
        data = []
        for row in range(model.rowCount()):
            row_data = [model.index(row, col).data() for col in range(model.columnCount())]
            data.append(row_data)

        df = pd.DataFrame(data, columns = headers)

        # create a temp file and store path
        plugin_dir = os.path.dirname(__file__)
        custom_dir = os.path.join(plugin_dir, "datasets/custom_dataset")
        os.makedirs(custom_dir, exist_ok=True)
        
        temp_file = os.path.join(custom_dir, f"{name}.csv")
        df.to_csv(temp_file, index=False)
        return temp_file

    def propagate_substances_from_consumption(self):
        """
        Auto-propagate substances from consumption table to removal rates and PNEC tables.
        When a substance is added to consumption table:
        - Add it to removal rates table with all TC columns (empty values)
        - Add it to PNEC table with default empty structure
        When a substance is removed from consumption table:
        - Remove it from both removal rates and PNEC tables
        This ensures all three tables stay synchronized.
        """
        try:
            # Extract current API names from consumption table (from self.df)
            consumption_apis = set(self.df["API name"].unique())
            
            # Get API names from removal rates table
            removal_apis = set(self.df_RR["API name"].unique())
            
            # Get API names from PNEC tables
            era_apis = set(self.df_ERA["API name"].unique())
            hh_apis = set(self.df_HH["API name"].unique())
            amr_apis = set(self.df_AMR["API name"].unique())
            
            # APIs to add (in consumption but not in removal/PNEC)
            apis_to_add = consumption_apis - removal_apis
            
            # APIs to remove from removal rates (not in consumption anymore)
            apis_to_remove_removal = removal_apis - consumption_apis
            
            # Add missing APIs to removal rates table
            if apis_to_add:
                for api_name in apis_to_add:
                    # Create new row with all TC columns (TC1, TC2, TC3, ...)
                    new_row = {"API name": api_name}
                    # Add all TC columns from existing rows
                    if not self.df_RR.empty:
                        tc_columns = [col for col in self.df_RR.columns if col.startswith("TC") and "removal rate" in col]
                        for col in tc_columns:
                            new_row[col] = ""
                    # Add other columns that might exist
                    for col in self.df_RR.columns:
                        if col not in new_row:
                            new_row[col] = ""
                    # Append to dataframe
                    self.df_RR = pd.concat([self.df_RR, pd.DataFrame([new_row])], ignore_index=True)
            
            # Remove APIs from removal rates table
            if apis_to_remove_removal:
                self.df_RR = self.df_RR[~self.df_RR["API name"].isin(apis_to_remove_removal)].reset_index(drop=True)
            
            # Add only genuinely new APIs to all three PNEC tables
            # (use apis_to_add, not consumption - pnec, to avoid adding
            #  existing consumption substances that were never in a PNEC table)
            for df_attr, df_pnec in [("df_ERA", self.df_ERA), ("df_HH", self.df_HH), ("df_AMR", self.df_AMR)]:
                pnec_apis = set(df_pnec["API name"].unique())
                pnec_to_add = apis_to_add - pnec_apis
                if pnec_to_add:
                    for api_name in pnec_to_add:
                        new_row = {"API name": api_name}
                        for col in df_pnec.columns:
                            if col not in new_row:
                                new_row[col] = ""
                        df_pnec = pd.concat([df_pnec, pd.DataFrame([new_row])], ignore_index=True)
                    setattr(self, df_attr, df_pnec)
            
            # PNEC tables are NOT pruned — users may add PNEC-only substances
            # that don't appear in the consumption table.

            # Propagate new countries to HHRA table columns
            hh_changed = False
            if "country" in self.df.columns:
                consumption_countries = set(self.df["country"].dropna().unique())
                existing_hh_countries = set(c.strip() for c in self.df_HH.columns[1:])
                for country in consumption_countries:
                    country = country.strip()
                    if country and country not in existing_hh_countries:
                        self.df_HH[country] = ""
                        hh_changed = True
            
            # Reload tables and persist propagated changes to CSV
            if apis_to_add or apis_to_remove_removal:
                self.load_table(self.df_RR, self.RRTableView)
                self.save_temp_table(self.RRTableView, "removal_")
            if apis_to_add or hh_changed:
                self.load_table(self.df_ERA, self.ERATableView)
                self.save_temp_table(self.ERATableView, "PNEC_ERA_")
                self.load_table(self.df_HH, self.HHTableView)
                self.save_temp_table(self.HHTableView, "PNEC_HH_")
                self.load_table(self.df_AMR, self.AMRTableView)
                self.save_temp_table(self.AMRTableView, "PNEC_AMR_")
                # Refresh the country dropdown
                if hasattr(self, "CountrycomboBox"):
                    current = self.CountrycomboBox.currentText()
                    self.CountrycomboBox.clear()
                    self.CountrycomboBox.addItems([c.strip() for c in self.df_HH.columns[1:]])
                    idx = self.CountrycomboBox.findText(current)
                    if idx >= 0:
                        self.CountrycomboBox.setCurrentIndex(idx)
                
        except Exception as e:
            QMessageBox.warning(self, "Warning", f"Could not automatically propagate substances: {e}\nYou may need to manually add substances to Removal Rates and PNEC tables.")
    
    def handle_save_consumption(self):
        # Validate mandatory fields before saving
        model = self.excelTableView.model()
        if model is None:
            return
        headers = [model.headerData(col, Qt.Horizontal) for col in range(model.columnCount())]
        headers = [h.replace(' (*)', '') if h else h for h in headers]
        mandatory_fields = ["API name", "year", "country", "region", "Excreted emission (mg/inh./a)"]
        mandatory_indices = []
        for field in mandatory_fields:
            if field in headers:
                mandatory_indices.append((headers.index(field), field))

        for row in range(model.rowCount()):
            for col_idx, field_name in mandatory_indices:
                value = model.index(row, col_idx).data()
                if not value or str(value).strip() == "" or str(value).strip().lower() == "nan":
                    QMessageBox.warning(
                        self, "Missing Data",
                        f"Row {row + 1}: '{field_name}' is empty.\n\n"
                        f"Please fill in all mandatory fields\n"
                        f"(API name, year, country, region, Excreted emission)\n"
                        f"before saving."
                    )
                    return

        self.temp_consumption_path = self.save_temp_table(self.excelTableView, "consumption_")
        self.df = pd.read_csv(self.temp_consumption_path, sep=",")
        self.df.columns = [c.replace(' (*)', '') for c in self.df.columns]
        # Auto-propagate new substances to other tables
        self.propagate_substances_from_consumption()
        # Reset modification flag
        self.consumption_modified = False


    def restore_original(self, original_filename, custom_filename, loader_func, table_view):
        """
        Delete custom dataset (if it exists) and reload the original.
        """
        plugin_dir = os.path.dirname(__file__)
        custom_path = os.path.join(plugin_dir, "datasets/custom_dataset", custom_filename)
        original_path = os.path.join(plugin_dir, "datasets/original_dataset", original_filename)

        # delete custom file if it exists
        if os.path.exists(custom_path):
            os.remove(custom_path)

        # read dataframe
        temp_df = pd.read_csv(original_path, sep=",")

        # update the instance variable
        if "consumption" in original_filename.lower():
            self.df = temp_df
        elif "removal" in original_filename.lower():
            self.df_RR = temp_df
        elif original_filename == "PNEC ERA.csv":
            self.df_ERA = temp_df
        elif original_filename == "PNEC HHRA.csv":
            self.df_HH = temp_df
        elif original_filename == "PNEC AMR-RA.csv":
            self.df_AMR = temp_df

        # reload original
        loader_func(temp_df, table_view)

        QMessageBox.information(self, "Success", "Table restored to its original values.")

    
    def save_selection_to_file(self):
        # get the plugin's directory path
        plugin_dir = os.path.dirname(__file__)

        # define the file path in the plugin's directory
        file_path = os.path.join(plugin_dir, "user_selection.txt")

        # get the selected items
        selected_items = []
        for index in range(self.selection_model.rowCount()):
            item = self.selection_model.item(index)
            selected_items.append(item.text())

        # Create the text file and write the selections
        with open(file_path, "w") as file:
            for selection in selected_items:
                file.write(f"{selection}\n")


    """
    Tab 2 - Removal rate
    """
    def handle_save_rr(self):
        self.temp_rr_path = self.save_temp_table(self.RRTableView, "removal_")
        self.df_RR = pd.read_csv(self.temp_rr_path, sep=",")
        # Reset modification flag
        self.removal_modified = False

    
    """
    Tab 3 - PNEC values
    """
    # PNEC save logic is in handle_save_pnec() above.
    # ERA, HH, AMR table views are managed through the shared
    # add_row_to_table / remove_selected_row / restore_original methods.


    """
    Tab 4 - WWTP locations
    """
    
    def populate_layer_combo(self):
        self.WWTPcomboBox.clear()
        layers = [layer for layer in QgsProject.instance().mapLayers().values() if layer.type() == QgsMapLayer.VectorLayer and layer.geometryType() == QgsWkbTypes.PointGeometry]
        self.vector_layers = layers
        for layer in layers:
            self.WWTPcomboBox.addItem(layer.name())

    def update_field_combos(self):
        index = self.WWTPcomboBox.currentIndex()
        if index < 0 or index >= len(self.vector_layers):
            return

        layer = self.vector_layers[index]
        field_names = [field.name() for field in layer.fields()]

        self.IDcomboBox.clear()
        self.NamecomboBox.clear()
        self.TCcomboBox.clear()
        self.IDcomboBox.addItems(field_names)
        self.NamecomboBox.addItems(field_names)
        self.TCcomboBox.addItems(field_names)

    def load_wwtp_table(self):
        removal_df = self.df_RR

        try:
            index = self.WWTPcomboBox.currentIndex()
            if index == -1:
                QMessageBox.warning(self, "No Layer selected", "Please select a point shapefile layer.")
                return

            layer = self.vector_layers[index]
            id_field = self.IDcomboBox.currentText()
            name_field = self.NamecomboBox.currentText()
            tc_field = self.TCcomboBox.currentText()
            

            if not id_field or not name_field or not tc_field:
                QMessageBox.warning(self, "Missing Field", "Please select all fields.")
                return

            model = QStandardItemModel()
            
            # get all selected API combinations from the list widget in tab 1
            # format: "API name, year, country, region, Excreted emission value"
            selections = []
            for i in range(self.selection_model.rowCount()):
                parts = self.selection_model.item(i).text().split(", ")
                if len(parts) >= 5:
                    selections.append(parts[:5])
                elif len(parts) == 4:
                    selections.append(parts + [""])  # backwards compat

            api_names = [sel[0] for sel in selections]
            api_headers = [f"{api} [mg/inh./a]" for api in api_names]
            removal_names = [f"RR_{api}" for api in api_names]

            model.setHorizontalHeaderLabels([id_field, name_field, tc_field] + api_headers + removal_names)

            for feature in layer.getFeatures():
                api_items = []
                # id and name
                id_val = feature[id_field]
                id_item = QStandardItem(str(id_val))
                api_items.append(id_item)
                name_val = feature[name_field]
                name_item = QStandardItem(str(name_val))
                api_items.append(name_item)

                try:
                    tech_class = int(feature[tc_field])
                except (TypeError, ValueError, KeyError):
                    tech_class = None
                tech_item = QStandardItem(str(tech_class))
                api_items.append(tech_item)
                
                # add each API value from the stored selection
                for sel in selections:
                    api_value = sel[4] if len(sel) > 4 else ""
                    api_item = QStandardItem(str(api_value))
                    api_items.append(api_item)

                # add removal rates (RR) values
                for api in api_names:
                    removal_val = ""
                    removal_row = removal_df[removal_df["API name"] == api]
                    if not removal_row.empty and tech_class:
                        col_name = f"TC{tech_class} removal rate"

                        if col_name in removal_row.columns:
                            try:
                                removal_val = float(removal_row.iloc[0][col_name])
                            except Exception:
                                removal_val = ""
                    rr_item = QStandardItem(str(removal_val))
                    api_items.append(rr_item)
                
                for item in (id_item, name_item, tech_item):
                    item.setFlags(item.flags() & ~Qt.ItemIsEditable)
                model.appendRow(api_items)

            self.wwtpTableView.setModel(model)

        except Exception as e:
            QMessageBox.critical(self, "Error", f"Could not load WWTP data: {e}")

    def save_wwtp_table_to_csv(self):
        model = self.wwtpTableView.model()
        if model is None:
            QMessageBox.warning(self, "No Data", "There is no data to save.")
            return

        plugin_dir = os.path.dirname(__file__)
        save_path = os.path.join(plugin_dir, "datasets/custom_dataset/wwtp_consumption_table.csv")

        try:
            # extract header
            headers = [model.headerData(col, Qt.Horizontal) for col in range(model.columnCount())]

            # extract rows
            data = []
            for row in range(model.rowCount()):
                row_data = []
                for col in range(model.columnCount()):
                    index = model.index(row, col)
                    row_data.append(index.data())
                data.append(row_data)

            # save using pandas
            df_save = pd.DataFrame(data, columns=headers)
            df_save.to_csv(save_path, index=False)

        except Exception as e:
            QMessageBox.critical(self, "Error", f"Could not save file:\n{e}")

    def _table_view_to_df(self, table_view):
        """Extract a DataFrame from a QTableView model."""
        model = table_view.model()
        if model is None or model.rowCount() == 0:
            return None
        headers = [model.headerData(c, Qt.Horizontal) for c in range(model.columnCount())]
        data = []
        for r in range(model.rowCount()):
            data.append([model.index(r, c).data() for c in range(model.columnCount())])
        return pd.DataFrame(data, columns=headers)

    def print_tables(self):
        """
        Let the user pick a folder, write the API_parameters CSV there,
        and add it as a layer in the active QGIS project.
        """
        from PyQt5.QtWidgets import QFileDialog

        save_dir = QFileDialog.getExistingDirectory(self, "Select output folder")
        if not save_dir:
            return

        try:
            df_custom = self._table_view_to_df(self.wwtpTableView) if hasattr(self, "wwtpTableView") else None
            if df_custom is None:
                QMessageBox.warning(self, "No Data", "WWTP locations is empty. Load it first.")
                return
            path = os.path.join(save_dir, "API_parameters.csv")
            df_custom.to_csv(path, index=False)

            # Write .csvt type-hint file so QGIS reads correct column types
            n_cols = len(df_custom.columns)
            col_types = ["String", "String"]  # ID, Name
            if n_cols > 2:
                col_types.append("Integer")   # TC
            for i in range(3, n_cols):
                col_types.append("Real")       # API values and RR values
            csvt_path = path.replace(".csv", ".csvt")
            with open(csvt_path, "w") as f:
                f.write(",".join(f'"{t}"' for t in col_types) + "\n")

            layer = QgsVectorLayer(f"file:///{path}?delimiter=,", "API_parameters", "delimitedtext")
            if layer.isValid():
                QgsProject.instance().addMapLayer(layer)
            self.progressBar.setValue(100)
            QMessageBox.information(self, "Success", "API_parameters layer added to project.")
        except Exception as e:
            QMessageBox.critical(self, "Error", f"Could not export table:\n{e}")

    def _export_table_for_sharing(self, table_view, default_filename):
        """
        Export a table to a user-chosen CSV file and add it to the QGIS project.
        Intended for sharing consumption or removal rate tables with colleagues.
        """
        from PyQt5.QtWidgets import QFileDialog

        df = self._table_view_to_df(table_view)
        if df is None:
            QMessageBox.warning(self, "No Data", "The table is empty.")
            return
        save_path, _ = QFileDialog.getSaveFileName(
            self, "Export table", default_filename, "CSV files (*.csv)"
        )
        if not save_path:
            return
        df.to_csv(save_path, index=False)
        layer_name = os.path.splitext(os.path.basename(save_path))[0]
        layer = QgsVectorLayer(
            f"file:///{save_path}?delimiter=,", layer_name, "delimitedtext"
        )
        if layer.isValid():
            QgsProject.instance().addMapLayer(layer)
        QMessageBox.information(self, "Exported", f"Table saved and added to project:\n{save_path}")

    def export_pnec_table(self):
        """
        Export the merged PNEC table (ERA, HH, AMR) to a user-chosen folder
        and add it as a layer in the active QGIS project.
        """
        from PyQt5.QtWidgets import QFileDialog

        save_dir = QFileDialog.getExistingDirectory(self, "Select output folder")
        if not save_dir:
            return

        try:
            df_era = self._table_view_to_df(self.ERATableView)
            df_hh = self._table_view_to_df(self.HHTableView)
            df_amr = self._table_view_to_df(self.AMRTableView)

            merged = pd.DataFrame()
            if df_era is not None:
                merged = df_era[["API name"]].copy()
                merged["ERA_PNEC"] = df_era.iloc[:, 1].values

            if df_hh is not None:
                country = self.CountrycomboBox.currentText().strip() if hasattr(self, "CountrycomboBox") else ""
                if country and country in df_hh.columns:
                    hh_sub = df_hh[["API name", country]].rename(columns={country: "HH_PNEC"})
                else:
                    hh_sub = df_hh[["API name"]].copy()
                    hh_sub["HH_PNEC"] = ""
                merged = merged.merge(hh_sub, on="API name", how="outer") if not merged.empty else hh_sub

            if df_amr is not None:
                amr_sub = df_amr[["API name"]].copy()
                amr_sub["AMR_PNEC"] = df_amr.iloc[:, 1].values
                merged = merged.merge(amr_sub, on="API name", how="outer") if not merged.empty else amr_sub

            if merged.empty:
                QMessageBox.warning(self, "No Data", "PNEC tables are empty.")
                return
            path = os.path.join(save_dir, "PNEC.csv")
            merged.to_csv(path, index=False)
            layer = QgsVectorLayer(f"file:///{path}?delimiter=,", "PNEC", "delimitedtext")
            if layer.isValid():
                QgsProject.instance().addMapLayer(layer)
            QMessageBox.information(self, "Success", "PNEC layer added to project.")
        except Exception as e:
            QMessageBox.critical(self, "Error", f"Could not export PNEC table:\n{e}")


    def _validate_csv_columns(self, df, required_cols, context_name):
        """Return (True, '') if df has all required_cols, else (False, error message)."""
        missing = [c for c in required_cols if c not in df.columns]
        if missing:
            return False, (
                f"The imported {context_name} CSV is missing required columns:\n"
                + "\n".join(f"  \u2022 {c}" for c in missing)
            )
        return True, ""

    def _import_external_consumption(self):
        """Import an external consumption CSV and replace the current dataset."""
        from PyQt5.QtWidgets import QFileDialog
        path, _ = QFileDialog.getOpenFileName(
            self, "Import consumption table", "", "CSV files (*.csv)"
        )
        if not path:
            return False
        try:
            df = pd.read_csv(path, sep=",")
            df.columns = [c.replace(' (*)', '') for c in df.columns]
            required = ["API name", "year", "country", "region",
                        "Excreted emission (mg/inh./a)"]
            ok, err = self._validate_csv_columns(df, required, "consumption")
            if not ok:
                QMessageBox.critical(self, "Invalid file", err)
                return False

            self.df = df
            plugin_dir = os.path.dirname(__file__)
            custom_dir = os.path.join(plugin_dir, "datasets/custom_dataset")
            os.makedirs(custom_dir, exist_ok=True)
            self.df.to_csv(os.path.join(custom_dir, "consumption_.csv"), index=False)

            self.load_table(self.df, self.excelTableView)

            self.propagate_substances_from_consumption()

            QMessageBox.information(
                self, "Imported",
                "Consumption table imported successfully.\n"
                "All rows have been added to the selection in Tab 1.\n"
                "Review the selection before loading the WWTP table."
            )
            return True
        except Exception as e:
            QMessageBox.critical(self, "Error", f"Could not import consumption table:\n{e}")
            return False

    def _import_external_rr(self):
        """Import an external removal rates CSV and replace the current dataset."""
        import re
        from PyQt5.QtWidgets import QFileDialog
        path, _ = QFileDialog.getOpenFileName(
            self, "Import removal rate table", "", "CSV files (*.csv)"
        )
        if not path:
            return False
        try:
            df = pd.read_csv(path, sep=",")
            ok, err = self._validate_csv_columns(df, ["API name"], "removal rate")
            if not ok:
                QMessageBox.critical(self, "Invalid file", err)
                return False
            tc_cols = [c for c in df.columns
                       if re.match(r"TC\d+\s+removal rate", c, re.IGNORECASE)]
            if not tc_cols:
                QMessageBox.critical(
                    self, "Invalid file",
                    "The imported removal rate CSV must contain at least one column "
                    "matching the pattern 'TC<number> removal rate'\n"
                    "(e.g. 'TC1 removal rate', 'TC2 removal rate')."
                )
                return False

            self.df_RR = df
            plugin_dir = os.path.dirname(__file__)
            custom_dir = os.path.join(plugin_dir, "datasets/custom_dataset")
            os.makedirs(custom_dir, exist_ok=True)
            self.df_RR.to_csv(os.path.join(custom_dir, "removal_.csv"), index=False)

            self.load_table(self.df_RR, self.RRTableView)

            QMessageBox.information(
                self, "Imported",
                "Removal rate table imported successfully.\n"
                "The WWTP table will now use these removal rates."
            )
            return True
        except Exception as e:
            QMessageBox.critical(self, "Error", f"Could not import removal rate table:\n{e}")
            return False

    def closeEvent(self, event):
        """
        Override close event to prompt user to save unsaved changes before closing.
        This prevents users from accidentally losing their modifications.
        """
        modified_tabs = []
        
        # Check which tabs have unsaved changes
        if self.consumption_modified:
            modified_tabs.append(("Consumption Data (Tab 1)", self.handle_save_consumption))
        if self.removal_modified:
            modified_tabs.append(("Removal Rates (Tab 2)", self.handle_save_rr))
        if self.pnec_modified:
            modified_tabs.append(("PNEC Values (Tab 3)", self.handle_save_pnec))
        
        # If there are unsaved changes, prompt user for each tab
        if modified_tabs:
            tabs_list = "\n".join([f"  \u2022 {tab[0]}" for tab in modified_tabs])
            msg_box = QMessageBox(self)
            msg_box.setIcon(QMessageBox.Warning)
            msg_box.setWindowTitle("Unsaved Changes")
            msg_box.setText("You have unsaved changes. Do you want to save before closing?")
            msg_box.setInformativeText(tabs_list)
            msg_box.setStandardButtons(QMessageBox.Save | QMessageBox.Discard | QMessageBox.Cancel)
            msg_box.setDefaultButton(QMessageBox.Save)
            reply = msg_box.exec_()
            
            if reply == QMessageBox.Cancel:
                # Cancel close event
                event.ignore()
                return
            elif reply == QMessageBox.Save:
                # Save all modified tabs
                for tab_name, save_func in modified_tabs:
                    try:
                        save_func()
                    except Exception as e:
                        error_reply = QMessageBox.critical(
                            self,
                            "Save Error",
                            f"Failed to save {tab_name}:\n{e}\n\nDo you want to close anyway?",
                            QMessageBox.Yes | QMessageBox.No
                        )
                        if error_reply == QMessageBox.No:
                            event.ignore()
                            return
        
        # Persist field combo selections
        self.save_field_selection()
        # Allow close event to proceed
        event.accept()

