# -*- coding: utf-8 -*-

"""
/***************************************************************************
 APRIORA
                                 A QGIS plugin
 Collection of APRIORA Plugins
 Generated by Plugin Builder: http://g-sherman.github.io/Qgis-Plugin-Builder/
                              -------------------
        begin                : 2024-06-13
        copyright            : (C) 2024 by Universität Rostock
        email                : cristiano.guidi2@uni-rostock.de
 ***************************************************************************/

/***************************************************************************
 *                                                                         *
 *   This program is free software; you can redistribute it and/or modify  *
 *   it under the terms of the GNU General Public License as published by  *
 *   the Free Software Foundation; either version 2 of the License, or     *
 *   (at your option) any later version.                                   *
 *                                                                         *
 ***************************************************************************/
"""

__author__ = 'Universität Rostock'
__date__ = '2024-06-13'
__copyright__ = '(C) 2024 by Universität Rostock'

# This will get replaced with a git SHA1 when you do a git archive

__revision__ = '$Format:%H$'

import os
import sys
import inspect

from qgis.core import QgsProcessingAlgorithm, QgsApplication
from .APRIORA_provider import APRIORAProvider
from .consumption_selection import ConsumptionSelection

cmd_folder = os.path.split(inspect.getfile(inspect.currentframe()))[0]

if cmd_folder not in sys.path:
    sys.path.insert(0, cmd_folder)


class APRIORAPlugin(object):

    def __init__(self, iface):
        self.provider = None
        self.iface = iface
        self.consumption_dialog = None

    def initProcessing(self):
        """Init Processing provider for QGIS >= 3.8."""
        self.provider = APRIORAProvider()
        QgsApplication.processingRegistry().addProvider(self.provider)

    def initGui(self):
        self.initProcessing()
        
        # Init and show the ConsumptionSelection plugin in the menu
        self.consumption_plugin = ConsumptionSelection(self.iface)
        self.consumption_plugin.initGui()  # This shows the menu entry

        # # Example of adding a custom toolbar button to open the dialog
        # action = self.iface.addToolBarIcon(self.consumption_dialog.addSelectionButton)
        # self.iface.addToolBar("Consumption Selection").addAction(action)

    def unload(self):
        if self.provider:
            try:
                QgsApplication.processingRegistry().removeProvider(self.provider)
            except RuntimeError:
                # The provider was already deleted
                pass
            self.provider = None  # Clear the reference 

        if self.consumption_plugin:
            self.consumption_plugin.unload()  # Remove its UI elements
