# -*- coding: utf-8 -*-

"""
/***************************************************************************
 APRIORA
                                 A QGIS plugin
 Collection of APRIORA Plugins
 Generated by Plugin Builder: http://g-sherman.github.io/Qgis-Plugin-Builder/
                              -------------------
        begin                : 2024-06-13
        copyright            : (C) 2024 by Universität Rostock
        email                : cristiano.guidi2@uni-rostock.de
 ***************************************************************************/

/***************************************************************************
 *                                                                         *
 *   This program is free software; you can redistribute it and/or modify  *
 *   it under the terms of the GNU General Public License as published by  *
 *   the Free Software Foundation; either version 2 of the License, or     *
 *   (at your option) any later version.                                   *
 *                                                                         *
 ***************************************************************************/
"""

__author__ = 'Universität Rostock'
__date__ = '2024-06-13'
__copyright__ = '(C) 2024 by Universität Rostock'

# This will get replaced with a git SHA1 when you do a git archive

__revision__ = '$Format:%H$'

import os
import math
import processing
import numpy as np
from osgeo import gdal
from PyQt5.QtCore import QVariant
from qgis.PyQt.QtCore import QCoreApplication, Qt, QDir, QVariant
from qgis.core import (QgsProcessingAlgorithm,
                       QgsProcessing,
                       QgsField,
                       QgsProcessingAlgorithm,
                       QgsProcessingParameterFile,
                       QgsProcessingParameterFeatureSource,
                       QgsProcessingParameterFeatureSink,
                       QgsProcessingParameterMatrix,
                       QgsProcessingParameterRasterLayer,
                       QgsField,
                       QgsRasterLayer)


class CalculateGeofactors(QgsProcessingAlgorithm):

    # Constants used to refer to parameters and outputs. They will be
    # used when calling the algorithm from another algorithm, or when
    # calling from the QGIS console.

    OUTPUT = 'OUTPUT'
    catchmentAreas = 'CatchmentAreas'
    DGM = 'DGM'
    slopeRaster = 'SlopeRaster'
    chosenGeofactors = 'ChosenGeofactors'
    waterArea  = 'WaterArea'
    riverNetwork = 'RiverNetwork'
    forestArea = 'ForestArea'
    settlementArea = 'SettlementArea'
    precipitationData = 'PrecipitationData'
    

    #Init tool
    def initAlgorithm(self, config):
        """
        Here we define the inputs and output of the algorithm, along
        with some other properties.
        """
        self.addParameter(
            QgsProcessingParameterFeatureSource(
                self.catchmentAreas,
                self.tr('Catchment areas'),
                [QgsProcessing.TypeVectorPolygon]
            )
        )
        
        self.addParameter(
            QgsProcessingParameterRasterLayer(
                self.DGM,
                self.tr('Digital surface model'),
                [QgsProcessing.TypeRaster]
            )
        )
        
        self.addParameter(
            QgsProcessingParameterRasterLayer(
                self.slopeRaster,
                self.tr('Slope raster'),
                [QgsProcessing.TypeRaster] 
            )
        )
        
        self.addParameter(
            QgsProcessingParameterFeatureSource(
                self.riverNetwork,
                self.tr('River network'),
                [QgsProcessing.TypeVectorLine]
            )
        )
        
        self.addParameter(
            QgsProcessingParameterFeatureSource(
                self.waterArea,
                self.tr('Water area'),
                [QgsProcessing.TypeVectorPolygon]
            )
        )
        
        self.addParameter(
            QgsProcessingParameterFeatureSource(
                self.forestArea,
                self.tr('Forest area'),
                [QgsProcessing.TypeVectorPolygon]
            )
        )
        
        self.addParameter(
            QgsProcessingParameterFeatureSource(
                self.settlementArea,
                self.tr('Settlement area'),
                [QgsProcessing.TypeVectorPolygon]
            )
        )

                
        self.addParameter(
            QgsProcessingParameterFile(
                self.precipitationData,
                self.tr('Precipitation data (folder)'),
                behavior=QgsProcessingParameterFile.Folder
            )
        )
        
        
        """
        file_param = QgsProcessingParameterMatrix(self.chosenGeofactors, 'Select geofactor')
        file_param.setMetadata({'widget_wrapper': {'class': PickOptionWidget}})
        self.addParameter(file_param)
        """
        
        # We add a feature sink in which to store our processed features (this
        # usually takes the form of a newly created vector layer when the
        # algorithm is run in QGIS).
        self.addParameter(
            QgsProcessingParameterFeatureSink(
                self.OUTPUT,
                self.tr('Output layer'),
                QgsProcessing.TypeVectorPolygon
            )
        )
    
    def createRaster(self, parameters, context, feedback, outfn, xmax, xmin, xres, ymax, ymin, yres, spatref, raster):
        #create Raster
        driver = gdal.GetDriverByName('GTiff')
        wkt = spatref.toWkt()
        nbands = 1
        nodata = -999
        dtype = gdal.GDT_Float32
        xsize = abs(int((xmax - xmin) / xres))
        ysize = abs(int((ymax - ymin) / yres))
        ds = driver.Create(outfn, xsize, ysize, nbands, dtype)
        ds.GetRasterBand(1).WriteArray(raster)
        ds.SetProjection(wkt)
        ds.SetGeoTransform([xmin, xres, 0, ymax, 0, -yres])
        ds.GetRasterBand(1).SetNoDataValue(nodata)
        ds.FlushCache()
        ds = None    
        
    def processPropotions(self, parameters, context, feedback, catchments, outputDir, fileName, fieldName, target, calcOption):
        #Calculates intersection of subcatchments and area/length
        feedback.setProgressText("\nCalculate statistics based on "+ fileName +"...")
        algresultIntersection = processing.run("native:intersection",
            {'INPUT': target,
             'OVERLAY':catchments,
             'OVERLAY_FIELDS': 'ID_SC',
             'OVERLAY_FIELDS_PREFIX': "",
             'OUTPUT': 'TEMPORARY_OUTPUT'},
            context=context, feedback=feedback)
        intersections = algresultIntersection['OUTPUT']

        #Calculates area/length of target parts
        provider = intersections.dataProvider()
        field = QgsField(fieldName+"_SC", QVariant.Double, 'double', 20, 3)
        provider.addAttributes([field])
        intersections.updateFields() 
        idx = provider.fieldNameIndex(fieldName+"_SC")
        for feature in intersections.getFeatures():
            if calcOption == 0: #0=area; 1=length/perimeter
                geom = feature.geometry().area()
            else:
                geom = feature.geometry().length()
            attrs = {idx : geom}
            intersections.dataProvider().changeAttributeValues({feature.id() : attrs})

        
        #Summarizes the target field based on the ID_SC field
        algresultSummarize = processing.run("qgis:statisticsbycategories",
            {'INPUT': intersections,
             'VALUES_FIELD_NAME':fieldName+"_SC",
             'CATEGORIES_FIELD_NAME': 'ID_SC',
             'OUTPUT': 'TEMPORARY_OUTPUT'},
            context=context, feedback=feedback)
        Summarize = algresultSummarize['OUTPUT']
        
        #Joins the sum of area information to catchments
        algresultJoinCatchmentsSummarize = processing.run("qgis:joinattributestable",
            {'INPUT': catchments,
             'FIELD':'ID_SC',
             'INPUT_2': Summarize,
             'FIELD_2': 'ID_SC',
             'FIELDS_TO_COPY': 'sum',
             'METHOD': 1,
             'DISCARD_NONMATCHING': False,
             'PREFIX': fieldName+'_',
             'OUTPUT': 'TEMPORARY_OUTPUT'},
            context=context, feedback=feedback)
        JoinCatchmentsSummarize = algresultJoinCatchmentsSummarize['OUTPUT']
        del intersections
        return JoinCatchmentsSummarize

    def processAlgorithm(self, parameters, context, feedback):
        """
        Here is where the processing itself takes place.
        """
        #Get data
        #parameterList = self.parameterAsMatrix(parameters, self.chosenGeofactors, context)
        catchmentSource = self.parameterAsVectorLayer(parameters, 'CatchmentAreas', context)
        catchmentSourceName = catchmentSource.name()
        
        #Get virtual output directory and output sink
        outputDir = "/vsimem/"
        


        #List of Outputs
        results = []
        #Start chosen calculations (parallelize if necessary)
        
        #Calculates zonal statistics based on DEM
        feedback.setProgressText("\nCalculate Zonal statistics...")
        algresultZonalStats = processing.run("native:zonalstatisticsfb",
            {'INPUT_RASTER': parameters[self.DGM],
             'RASTER_BAND':1,
             'INPUT': parameters[self.catchmentAreas],
             'COLUMN_PREFIX': "H_",
             'STATISTICS': [3, 4, 5],
             'OUTPUT': 'TEMPORARY_OUTPUT'},
            context=context, feedback=feedback)
        catchments = algresultZonalStats['OUTPUT']

        #Set area and perimeter field to layer
        provider = catchments.dataProvider()
        id_field = QgsField("ID_SC", QVariant.Int, 'int')
        area_field = QgsField("AREA_SC", QVariant.Double, 'double', 20, 3)
        perimeter_field = QgsField("PERI_SC", QVariant.Double, 'double', 20, 3)
        shapeFactor_field = QgsField("SHAPE_SC", QVariant.Double, 'double', 20, 3)
        provider.addAttributes([id_field, area_field, perimeter_field, shapeFactor_field])
        catchments.updateFields() 
        #Calculate area and perimeter
        idxID = provider.fieldNameIndex('ID_SC')
        idxArea = provider.fieldNameIndex('AREA_SC')
        idxPerimeter = provider.fieldNameIndex('PERI_SC')
        idxShapeFactor = provider.fieldNameIndex('SHAPE_SC')
        for feature in catchments.getFeatures():
            attrsID = {idxID : feature.id()}
            catchments.dataProvider().changeAttributeValues({feature.id() : attrsID})
            geomArea = feature.geometry().area()
            attrsArea = {idxArea : geomArea}
            catchments.dataProvider().changeAttributeValues({feature.id() : attrsArea})
            geomPeri = feature.geometry().length()
            attrsPerimeter = {idxPerimeter : geomPeri}
            catchments.dataProvider().changeAttributeValues({feature.id() : attrsPerimeter})
            geomShapeFactor =  math.pow(geomPeri, 2)/(2*math.pi*geomArea)
            attrsShapeFactor = {idxShapeFactor : geomShapeFactor}
            catchments.dataProvider().changeAttributeValues({feature.id() : attrsShapeFactor})

        slope = parameters[self.slopeRaster]

        #Calculates zonal statistics based on the slope raster 
        feedback.setProgressText("\nCalculate slope statistics...")
        processing.run("native:zonalstatistics",
            {'INPUT_RASTER': slope,
             'RASTER_BAND':1,
             'INPUT_VECTOR': catchments,
             'COLUMN_PREFIX': "S_",
             'STATISTICS': [3, 4]},
            context=context, feedback=feedback)
        results.extend([slope, catchments])

        #Calculates statistics based on river network
        JoinCatchmentsRiverSummarize = self.processPropotions(parameters, context, feedback, catchments, outputDir, "RiverNetwork", "RN", parameters[self.riverNetwork],1)

        #Calculates statistics based on water area
        JoinCatchmentsWaterAreaSummarize = self.processPropotions(parameters, context, feedback, JoinCatchmentsRiverSummarize, outputDir, "WaterArea", "WA", parameters[self.waterArea],0)
        
        #Calculates statistics based on forest area
        JoinCatchmentsForestAreaSummarize = self.processPropotions(parameters, context, feedback, JoinCatchmentsWaterAreaSummarize, outputDir, "ForestArea", "FA", parameters[self.forestArea],0)
        
        #Calculates statistics based on settlement area
        JoinCatchmentsSetttlementAreaSummarize = self.processPropotions(parameters, context, feedback, JoinCatchmentsForestAreaSummarize, outputDir, "SetttlementArea", "SA", parameters[self.settlementArea],0)
        
         #Calculates river network density (rnd), proportion of water area (pwa), forest share and settlemet share
        feedback.setProgressText("\nCalculate river network density (rnd) and Proportion of water area (pwa)...")
        provider = JoinCatchmentsSetttlementAreaSummarize.dataProvider()
        rnd_field = QgsField("RND", QVariant.Double, 'double', 20, 3)
        pwa_field = QgsField("PWA", QVariant.Double, 'double', 20, 3)
        fs_field = QgsField("FS", QVariant.Double, 'double', 20, 3)
        ss_field = QgsField("SS", QVariant.Double, 'double', 20, 3)
        provider.addAttributes([rnd_field, pwa_field, fs_field, ss_field])
        JoinCatchmentsSetttlementAreaSummarize.updateFields() 
        idxRND = provider.fieldNameIndex('RND')
        idxPWA = provider.fieldNameIndex('PWA')
        idxFS = provider.fieldNameIndex('FS')
        idxSS = provider.fieldNameIndex('SS')
        idxRN_Sum = provider.fieldNameIndex('RN_sum')
        idxWA_Sum = provider.fieldNameIndex('WA_sum')
        idxFA_Sum = provider.fieldNameIndex('FA_sum')
        idxSA_Sum = provider.fieldNameIndex('SA_sum')
        for feature in JoinCatchmentsSetttlementAreaSummarize.getFeatures():
            if feature["RN_sum"] != None:
                calcRND = (feature["RN_sum"] / feature["AREA_SC"]) *100
                RNsum = feature["RN_sum"]
            else:
                calcRND = 0
                RNsum = 0
            if feature["WA_sum"] != None:
                calcPWA = (feature["WA_sum"] / feature["AREA_SC"]) *100
                WAsum = feature["WA_sum"]
            else:
                calcPWA = 0
                WAsum = 0
            if feature["FA_sum"] != None:
                calcFS = (feature["FA_sum"] / feature["AREA_SC"]) *100
                FAsum = feature["FA_sum"]
            else:
                calcFS = 0
                FAsum = 0
            if feature["SA_sum"] != None:
                calcSS = (feature["SA_sum"] / feature["AREA_SC"]) *100
                SAsum = feature["SA_sum"] 
            else:
                calcSS = 0
                SAsum = 0
            attrs = {idxRND : calcRND, idxPWA : calcPWA, idxFS : calcFS, idxSS : calcSS, idxRN_Sum : RNsum, idxWA_Sum : WAsum, idxFA_Sum : FAsum, idxSA_Sum : SAsum}
            JoinCatchmentsSetttlementAreaSummarize.dataProvider().changeAttributeValues({feature.id() : attrs})
            
        #Calculation of precipitation
        feedback.setProgressText("\nCalculate precipitation")
        netcdf_dir = self.parameterAsString(parameters, self.precipitationData, context)
        # list of all .nc file in the directory
        netcdf_files = QDir(netcdf_dir).entryList(["*.nc"], QDir.Files)

        # Variables
        yearlyMeanRaster = None
        augustMeanRaster =  None
        firstRound=True
        firstFile=True

        spatref = None
        xres = None
        yres = None
        xmin = None
        xmax = None
        ymin = None
        ymax = None

        for filename in netcdf_files:
            i=1
            netcdf_file = os.path.join(netcdf_dir, filename)
            subdataset_path = 'NETCDF:"{}":pr'.format(netcdf_file)
            raster_layer_unc = QgsRasterLayer(subdataset_path, "Annual precipitation")
            rasterDataSource = gdal.Open(str(raster_layer_unc.source()))
            yearlyTemp = None
            if firstFile:
                spatref = raster_layer_unc.crs()
                xres = raster_layer_unc.rasterUnitsPerPixelX()
                yres = raster_layer_unc.rasterUnitsPerPixelY()
                ext = raster_layer_unc.extent()
                xmin = ext.xMinimum()
                xmax = ext.xMaximum()
                ymin = ext.yMinimum()
                ymax = ext.yMaximum()
            while i <= rasterDataSource.RasterCount:
                if i == 1:
                    yearlyTemp = np.array([rasterDataSource.GetRasterBand(i).ReadAsArray()])
                else:
                    yearlyTemp= np.append(yearlyTemp, [rasterDataSource.GetRasterBand(i).ReadAsArray()], axis=0)
                i+=1
                
            yearlyMean = np.sum(yearlyTemp, axis=0)
            augustMean = rasterDataSource.GetRasterBand(8).ReadAsArray()
            
            if firstRound:
                yearlyMeanRaster = np.array([yearlyMean])
                augustMeanRaster = np.array([augustMean])
                firstRound = False
            else:
                yearlyMeanRaster= np.append(yearlyMeanRaster, [yearlyMean], axis=0)
                augustMeanRaster= np.append(augustMeanRaster, [augustMean], axis=0)
            

        finalYearlyMeanRaster = np.mean(yearlyMeanRaster, axis=0)
        finalAugustMeanRaster = np.mean(augustMeanRaster, axis=0)

        outfnYearly = outputDir+catchmentSourceName+'_yearlyPrecipitation.tif'
        outfnAugust = outputDir+catchmentSourceName+'_augustPrecipitation.tif'
        self.createRaster(parameters, context, feedback, outfnYearly, xmax, xmin, xres, ymax, ymin, yres, spatref, finalYearlyMeanRaster)
        self.createRaster(parameters, context, feedback, outfnAugust, xmax, xmin, xres, ymax, ymin, yres, spatref, finalAugustMeanRaster)
        precipitationYearlyLayer = QgsRasterLayer(outfnYearly, "precipitationYearly")
        precipitationAugustLayer = QgsRasterLayer(outfnAugust, "precipitationAugust")
        processing.run("native:zonalstatistics",
            {'INPUT_RASTER': precipitationYearlyLayer,
             'RASTER_BAND':1,
             'INPUT_VECTOR': JoinCatchmentsSetttlementAreaSummarize,
             'COLUMN_PREFIX': "PreYearly_",         # this part need to be fix because the output column is "PreYearly_MEAN", remove the "MEAN"
             'STATISTICS': [2]},
            context=context, feedback=feedback)

        finalLayer = processing.run("native:zonalstatisticsfb",
            {'INPUT_RASTER': precipitationAugustLayer,
             'RASTER_BAND':1,
             'INPUT': JoinCatchmentsSetttlementAreaSummarize,
             'COLUMN_PREFIX': "PreAugust_",         # this part need to be fix because the output column is "PreYearly_MEAN", remove the "MEAN"
             'STATISTICS': [2],
             'OUTPUT': 'TEMPORARY_OUTPUT'},
            context=context, feedback=feedback)['OUTPUT']

        (sink, dest_id) = self.parameterAsSink(parameters, self.OUTPUT, context,
                                        finalLayer.fields(), finalLayer.wkbType(), finalLayer.sourceCrs())
        
        for feat in finalLayer.getFeatures():
            sink.addFeature(feat)
        
        

        """
        #Set progressbar
        features = catchmentAreaSource.getFeatures()
        total = 100.0 / catchmentAreaSource.featureCount() if catchmentAreaSource.featureCount() else 0
        for current, feature in enumerate(features):
            # Stop the algorithm if cancel button has been clicked
            if feedback.isCanceled():
                break
            # Update the progress bar
            feedback.setProgress(int(current * total))
        """
        return {self.OUTPUT: dest_id}
        

    def name(self):
        """
        Returns the algorithm name, used for identifying the algorithm. This
        string should be fixed for the algorithm, and must not be localised.
        The name should be unique within each provider. Names should contain
        lowercase alphanumeric characters only and no spaces or other
        formatting characters.
        """
        return '2 - Calculate geofactors'

    def displayName(self):
        """
        Returns the translated algorithm name, which should be used for any
        user-visible display of the algorithm name.
        """
        return self.tr(self.name())

    def group(self):
        """
        Returns the name of the group this algorithm belongs to. This string
        should be localised.
        """
        return self.tr(self.groupId())

    def groupId(self):
        """
        Returns the unique ID of the group this algorithm belongs to. This
        string should be fixed for the algorithm, and must not be localised.
        The group id should be unique within each provider. Group id should
        contain lowercase alphanumeric characters only and no spaces or other
        formatting characters.
        """
        return ''

    def tr(self, string):
        return QCoreApplication.translate('Processing', string)

    def createInstance(self):
        return CalculateGeofactors()