# -*- coding: utf-8 -*-

"""
/***************************************************************************
 APRIORA
                                 A QGIS plugin
 Collection of APRIORA Plugins
 Generated by Plugin Builder: http://g-sherman.github.io/Qgis-Plugin-Builder/
                              -------------------
        begin                : 2024-06-13
        copyright            : (C) 2024 by Cristiano Guidi
        email                : cristiano.guidi2@uni-rostock.de
 ***************************************************************************/

/***************************************************************************
 *                                                                         *
 *   This program is free software; you can redistribute it and/or modify  *
 *   it under the terms of the GNU General Public License as published by  *
 *   the Free Software Foundation; either version 2 of the License, or     *
 *   (at your option) any later version.                                   *
 *                                                                         *
 ***************************************************************************/
"""

__author__ = 'Cristiano Guidi'
__date__ = '2024-06-13'
__copyright__ = '(C) 2024 by Cristiano Guidi'

# This will get replaced with a git SHA1 when you do a git archive

__revision__ = '$Format:%H$'

import os
import math
import processing
import numpy as np
from osgeo import gdal
from PyQt5.QtCore import QVariant
from qgis.PyQt.QtCore import QCoreApplication, QDir
from qgis.core import (QgsProcessingAlgorithm,
                       QgsCoordinateReferenceSystem,
                       QgsProcessing,
                       QgsProject,
                       QgsField,
                       QgsProcessingParameterBoolean,
                       QgsProcessingParameterFile,
                       QgsProcessingParameterFeatureSource,
                       QgsProcessingParameterFeatureSink,
                       QgsProcessingParameterNumber,
                       QgsProcessingParameterRasterLayer,
                       QgsRasterLayer,
                       edit)
gdal.UseExceptions()


class CalculateGeofactors(QgsProcessingAlgorithm):

    # Constants used to refer to parameters and outputs. They will be
    # used when calling the algorithm from another algorithm, or when
    # calling from the QGIS console.

    OUTPUTungauged = 'OUTPUTungauged'
    OUTPUTgauged = 'OUTPUTgauged'
    ungaugedSubcatch = 'ungaugedSubcatch'
    gaugedSubcatch = 'gaugedSubcatch'
    DGM = 'DGM'
    chosenGeofactors = 'ChosenGeofactors'
    waterArea = 'WaterArea'
    riverNetwork = 'RiverNetwork'
    forestArea = 'ForestArea'
    settlementArea = 'SettlementArea'
    precipitationData = 'PrecipitationData'
    aggregated = 'Aggregated'
    dryMonth = 'DryMonth'

    def shortHelpString(self):
        return self.tr(
            """
            This tool calculates geofactors for each subcatchment, which are required by \
            Tool 4 (Flow Estimation) to estimate river discharge.

            Geofactors computed per subcatchment:
            - Elevation statistics (mean, min, max) from the digital surface model.
            - Slope statistics (mean, max) derived from the DSM.
            - Shape factor, area, and perimeter.
            - River network density and proportions of water, forest, and settlement area.
            - Mean yearly precipitation and mean dry-month precipitation.

            Inputs:
            - Ungauged subcatchments: output of Tool 2 ("Ungauged subcatch").
            - Gauged subcatchments: output of Tool 2 ("Gauged subcatch").
            - Digital surface model: raster DEM.
            - Fixed river network: output of Tool 1.
            - Water / Forest / Settlement area: polygon layers for land-use shares.
            - Precipitation data: select the folder containing your NetCDF (.nc) data. The tool accepts \
                multiple files (one .nc file per year) or single file (one aggregated .nc file containing the full time series).
            - Driest month: month index (1–12) used for the dry-month precipitation average.

            Outputs:
            - Ungauged subcatchments geofactors.
            - Gauged subcatchments geofactors.

            Workflow:
            1. Select the input layers and the precipitation folder.
            2. Choose whether the folder contains an aggregated file.
            3. Set the driest month (default: August = 8).
            4. Click Run.
            """)

    # Init tool
    def initAlgorithm(self, config):
        """
        Here we define the inputs and output of the algorithm, along
        with some other properties.
        """
        self.addParameter(
            QgsProcessingParameterFeatureSource(
                self.ungaugedSubcatch,
                self.tr('Ungauged subcatchments'),
                [QgsProcessing.TypeVectorPolygon],
                defaultValue=QgsProject.instance().mapLayersByName("Ungauged subcatch")[0].id() if QgsProject.instance().mapLayersByName("Ungauged subcatch") else None
            )
        )

        self.addParameter(
            QgsProcessingParameterFeatureSource(
                self.gaugedSubcatch,
                self.tr('Gauged subcatchments'),
                [QgsProcessing.TypeVectorPolygon],
                defaultValue=QgsProject.instance().mapLayersByName("Gauged subcatch")[0].id() if QgsProject.instance().mapLayersByName("Gauged subcatch") else None
            )
        )

        self.addParameter(
            QgsProcessingParameterRasterLayer(
                self.DGM,
                self.tr('Digital surface model'),
                [QgsProcessing.TypeRaster]
            )
        )

        self.addParameter(
            QgsProcessingParameterFeatureSource(
                self.riverNetwork,
                self.tr('Fixed river network'),
                [QgsProcessing.TypeVectorLine],
                defaultValue=QgsProject.instance().mapLayersByName("Fixed river network")[0].id() if QgsProject.instance().mapLayersByName("Fixed river network") else None
            )
        )

        self.addParameter(
            QgsProcessingParameterFeatureSource(
                self.waterArea,
                self.tr('Water area'),
                [QgsProcessing.TypeVectorPolygon]
            )
        )

        self.addParameter(
            QgsProcessingParameterFeatureSource(
                self.forestArea,
                self.tr('Forest area'),
                [QgsProcessing.TypeVectorPolygon]
            )
        )

        self.addParameter(
            QgsProcessingParameterFeatureSource(
                self.settlementArea,
                self.tr('Settlement area'),
                [QgsProcessing.TypeVectorPolygon]
            )
        )

        self.addParameter(
            QgsProcessingParameterFile(
                self.precipitationData,
                self.tr('Precipitation data (folder)'),
                behavior=QgsProcessingParameterFile.Folder
            )
        )

        self.addParameter(
            QgsProcessingParameterBoolean(
                self.aggregated,
                self.tr('The folder contains an aggregated file'),
                defaultValue=False
            )
        )

        self.addParameter(
            QgsProcessingParameterNumber(
                self.dryMonth,
                self.tr('Driest month (1=Jan, 2=Feb, ..., 12=Dec). This information is used for expected low flow conditions.'),
                type=QgsProcessingParameterNumber.Integer,
                defaultValue=8,
                minValue=1,
                maxValue=12
            )
        )

        # We add a feature sink in which to store our processed features (this
        # usually takes the form of a newly created vector layer when the
        # algorithm is run in QGIS).

        self.addParameter(
            QgsProcessingParameterFeatureSink(
                self.OUTPUTungauged,
                self.tr('Ungauged subcatch geofactors'),
                QgsProcessing.TypeVectorPolygon
            )
        )

        self.addParameter(
            QgsProcessingParameterFeatureSink(
                self.OUTPUTgauged,
                self.tr('Gauged subcatch geofactors'),
                QgsProcessing.TypeVectorPolygon
            )
        )

    def createRaster(self, parameters, context, feedback, outfn, xmax, xmin, xres, ymax, ymin, yres, spatref, raster):
        # create Raster
        driver = gdal.GetDriverByName('GTiff')
        wkt = spatref.toWkt()
        nbands = 1
        nodata = -999
        dtype = gdal.GDT_Float32
        xsize = abs(int((xmax - xmin) / xres))
        ysize = abs(int((ymax - ymin) / yres))
        ds = driver.Create(outfn, xsize, ysize, nbands, dtype)
        ds.GetRasterBand(1).WriteArray(raster)
        ds.SetProjection(wkt)
        ds.SetGeoTransform([xmin, xres, 0, ymax, 0, -yres])
        ds.GetRasterBand(1).SetNoDataValue(nodata)
        ds.FlushCache()
        ds = None
        feedback.setProgressText(f"Debug: Raster shape = {raster.shape}")

    def processProportions(self, parameters, context, feedback, catchments, outputDir, fileName, fieldName, target, calcOption):
        # Calculates intersection of subcatchments and area/length
        feedback.setProgressText("\nCalculate statistics based on " + fileName + "...")
        intersections = processing.run("native:intersection", {
            'INPUT': target,
            'OVERLAY': catchments,
            'OVERLAY_FIELDS': 'ID_SC',
            'OVERLAY_FIELDS_PREFIX': "",
            'OUTPUT': 'TEMPORARY_OUTPUT'
            }, context=context)["OUTPUT"]
        context.temporaryLayerStore().addMapLayer(intersections)

        # Calculates area/length of target parts
        provider = intersections.dataProvider()
        field = QgsField(fieldName+"_SC", QVariant.Double, 'double', 20, 3)
        provider.addAttributes([field])
        intersections.updateFields()
        idx = provider.fieldNameIndex(fieldName+"_SC")
        all_changes = {}
        for feature in intersections.getFeatures():
            if calcOption == 0:  # 0=area; 1=length/perimeter
                geom = feature.geometry().area()
            else:
                geom = feature.geometry().length()
            all_changes[feature.id()] = {idx: geom}
        intersections.dataProvider().changeAttributeValues(all_changes)

        # Summarizes the target field based on the ID_SC field
        Summarize = processing.run("qgis:statisticsbycategories", {
            'INPUT': intersections,
            'VALUES_FIELD_NAME': fieldName+"_SC",
            'CATEGORIES_FIELD_NAME': 'ID_SC',
            'OUTPUT': 'TEMPORARY_OUTPUT'
            }, context=context)["OUTPUT"]
        context.temporaryLayerStore().addMapLayer(Summarize)

        # Joins the sum of area information to catchments
        JoinCatchmentsSummarize = processing.run("qgis:joinattributestable", {
            'INPUT': catchments,
            'FIELD': 'ID_SC',
            'INPUT_2': Summarize,
            'FIELD_2': 'ID_SC',
            'FIELDS_TO_COPY': 'sum',
            'METHOD': 1,
            'DISCARD_NONMATCHING': False,
            'PREFIX': fieldName+'_',
            'OUTPUT': 'TEMPORARY_OUTPUT'
            }, context=context)['OUTPUT']
        context.temporaryLayerStore().addMapLayer(JoinCatchmentsSummarize)
        del intersections, Summarize
        return JoinCatchmentsSummarize

    def processAlgorithm(self, parameters, context, feedback):
        """
        Here is where the processing itself takes place.
        """

        """
        The process will be done twice, once with ungauged and once with gauged (maybe add a for loop?)
        """

        # Get data
        feedback.setProgressText("\nStart with ungauged subcatchments...")
        # ungauged subcatchments
        ungaugedSource = self.parameterAsVectorLayer(parameters, 'ungaugedSubcatch', context)
        ungaugedSourceName = ungaugedSource.name()

        # Get virtual output directory and output sink
        outputDir = "/vsimem/"

        # Calculates zonal statistics based on DEM
        feedback.setProgressText("\nCalculate Zonal statistics...")
        catchments_ungauged = processing.run("native:zonalstatisticsfb", {
            'INPUT_RASTER': parameters[self.DGM],
            'RASTER_BAND': 1,
            'INPUT': parameters[self.ungaugedSubcatch],
            'COLUMN_PREFIX': "H_",
            'STATISTICS': [2, 4, 5],
            'OUTPUT': 'TEMPORARY_OUTPUT'
            }, context=context)['OUTPUT']
        context.temporaryLayerStore().addMapLayer(catchments_ungauged)

        # Set area and perimeter field to layer
        provider = catchments_ungauged.dataProvider()
        id_field = QgsField("ID_SC", QVariant.Int, 'int')
        area_field = QgsField("AREA_SC", QVariant.Double, 'double', 20, 3)
        perimeter_field = QgsField("PERIM_SC", QVariant.Double, 'double', 20, 3)
        shapeFactor_field = QgsField("SHAPE_SC", QVariant.Double, 'double', 20, 3)
        provider.addAttributes([id_field, area_field, perimeter_field, shapeFactor_field])
        catchments_ungauged.updateFields()
        # Calculate area and perimeter
        idxID = provider.fieldNameIndex('ID_SC')
        idxArea = provider.fieldNameIndex('AREA_SC')
        idxPerimeter = provider.fieldNameIndex('PERIM_SC')
        idxShapeFactor = provider.fieldNameIndex('SHAPE_SC')
        all_changes = {}
        for feature in catchments_ungauged.getFeatures():
            geomArea = feature.geometry().area()
            geomPeri = feature.geometry().length()
            geomShapeFactor = geomPeri ** 2 / (2 * math.pi * geomArea)
            all_changes[feature.id()] = {
                idxID: feature.id(),
                idxArea: geomArea,
                idxPerimeter: geomPeri,
                idxShapeFactor: geomShapeFactor,
            }
        catchments_ungauged.dataProvider().changeAttributeValues(all_changes)

        # calculate slope
        slope = processing.run("native:slope", {
            'INPUT': parameters[self.DGM],
            'Z_FACTOR': 1,
            'OUTPUT': 'TEMPORARY_OUTPUT'})["OUTPUT"]
        context.temporaryLayerStore().addMapLayer(slope)

        # Calculates zonal statistics based on the slope raster
        feedback.setProgressText("\nCalculate slope statistics...")
        processing.run("native:zonalstatistics", {
            'INPUT_RASTER': slope,
            'RASTER_BAND': 1,
            'INPUT_VECTOR': catchments_ungauged,
            'COLUMN_PREFIX': "Slp_",
            'STATISTICS': [2, 4]
            }, context=context)

        # Calculates statistics based on river network
        JoinCatchmentsRiverSummarize = self.processProportions(parameters, context, feedback, catchments_ungauged, outputDir, "RiverNetwork", "RivNe", parameters[self.riverNetwork], 1)
        del catchments_ungauged

        # Calculates statistics based on water area
        JoinCatchmentsWaterAreaSummarize = self.processProportions(parameters, context, feedback, JoinCatchmentsRiverSummarize, outputDir, "WaterArea", "WatAr", parameters[self.waterArea], 0)
        del JoinCatchmentsRiverSummarize

        # Calculates statistics based on forest area
        JoinCatchmentsForestAreaSummarize = self.processProportions(parameters, context, feedback, JoinCatchmentsWaterAreaSummarize, outputDir, "ForestArea", "ForAr", parameters[self.forestArea], 0)
        del JoinCatchmentsWaterAreaSummarize

        # Calculates statistics based on settlement area
        JoinCatchmentsSettlementAreaSummarize = self.processProportions(parameters, context, feedback, JoinCatchmentsForestAreaSummarize, outputDir, "SettlementArea", "SettAr", parameters[self.settlementArea], 0)
        del JoinCatchmentsForestAreaSummarize

        # Calculates river network density (rnd), proportion of water area (pwa), forest share and settlemet share
        feedback.setProgressText("\nCalculate river network density (rnd) and proportion of water area (pwa)...")
        provider = JoinCatchmentsSettlementAreaSummarize.dataProvider()
        rnd_field = QgsField("RivNetDens", QVariant.Double, 'double', 20, 3)
        pwa_field = QgsField("PropWatAr", QVariant.Double, 'double', 20, 3)
        fs_field = QgsField("Forest %", QVariant.Double, 'double', 20, 3)
        ss_field = QgsField("Settl %", QVariant.Double, 'double', 20, 3)
        provider.addAttributes([rnd_field, pwa_field, fs_field, ss_field])
        JoinCatchmentsSettlementAreaSummarize.updateFields()
        idxRND = provider.fieldNameIndex('RivNetDens')
        idxPWA = provider.fieldNameIndex('PropWatAr')
        idxFS = provider.fieldNameIndex('Forest %')
        idxSS = provider.fieldNameIndex('Settl %')
        idxRN_Sum = provider.fieldNameIndex('RivNe_sum')
        idxWA_Sum = provider.fieldNameIndex('WatAr_sum')
        idxFA_Sum = provider.fieldNameIndex('ForAr_sum')
        idxSA_Sum = provider.fieldNameIndex('SettAr_sum')
        for feature in JoinCatchmentsSettlementAreaSummarize.getFeatures():
            area_sc = feature["AREA_SC"]
            if not area_sc or area_sc <= 0:
                feedback.pushWarning(f"Skipping feature {feature.id()}: AREA_SC is {area_sc}. Assigning 0 to derived fields.")
                attrs = {idxRND: 0, idxPWA: 0, idxFS: 0, idxSS: 0, idxRN_Sum: 0, idxWA_Sum: 0, idxFA_Sum: 0, idxSA_Sum: 0}
                JoinCatchmentsSettlementAreaSummarize.dataProvider().changeAttributeValues({feature.id(): attrs})
                continue
            if feature["RivNe_sum"] is not None:
                calcRND = (feature["RivNe_sum"] / area_sc) * 100
                RNsum = feature["RivNe_sum"]
            else:
                calcRND = 0
                RNsum = 0
            if feature["WatAr_sum"] is not None:
                calcPWA = (feature["WatAr_sum"] / area_sc) * 100
                WAsum = feature["WatAr_sum"]
            else:
                calcPWA = 0
                WAsum = 0
            if feature["ForAr_sum"] is not None:
                calcFS = (feature["ForAr_sum"] / area_sc) * 100
                FAsum = feature["ForAr_sum"]
            else:
                calcFS = 0
                FAsum = 0
            if feature["SettAr_sum"] is not None:
                calcSS = (feature["SettAr_sum"] / area_sc) * 100
                SAsum = feature["SettAr_sum"]
            else:
                calcSS = 0
                SAsum = 0
            attrs = {idxRND: calcRND, idxPWA: calcPWA, idxFS: calcFS, idxSS: calcSS, idxRN_Sum: RNsum, idxWA_Sum: WAsum, idxFA_Sum: FAsum, idxSA_Sum: SAsum}
            JoinCatchmentsSettlementAreaSummarize.dataProvider().changeAttributeValues({feature.id(): attrs})

        if not JoinCatchmentsSettlementAreaSummarize.isValid():
            feedback.reportError("Error: JoinCatchmentsSettlementAreaSummarize is not valid!", fatalError=True)

        # Calculation of precipitation
        feedback.setProgressText("\nCalculate precipitation")
        feedback.setProgress(80)    # set the progress to 80% because otherwise it is stuck at 100
        netcdf_dir = self.parameterAsString(parameters, self.precipitationData, context)
        aggregated_selection = self.parameterAsBoolean(parameters, self.aggregated, context)
        dry_month = self.parameterAsInt(parameters, self.dryMonth, context)
        days_per_month = (31, 28, 31, 30, 31, 30, 31, 31, 30, 31, 30, 31)
        days_in_dry_month = days_per_month[dry_month - 1]
        month_names = ('January', 'February', 'March', 'April', 'May', 'June', 'July', 'August', 'September', 'October', 'November', 'December')
        dry_month_name = month_names[dry_month - 1]
        feedback.pushInfo(f"Dry month: {dry_month_name} (month {dry_month}, {days_in_dry_month} days)")
        # list of all .nc file in the directory
        netcdf_files = QDir(netcdf_dir).entryList(["*.nc"], QDir.Files)

        # Variables
        firstFile = True
        spatref = None
        xres = None
        yres = None
        xmin = None
        xmax = None
        ymin = None
        ymax = None

        if aggregated_selection:
            if not netcdf_files:
                feedback.reportError("No NetCDF file found in the selected folder", fatalError=True)  # change in order to have only one .nc file in the folder
                return {}

            netcdf_file = os.path.join(netcdf_dir, netcdf_files[0])
            subset_path = 'NETCDF:"{}":tp'.format(netcdf_file)  # check if it is correct or if "tp" is the variable name
            raster_layer = QgsRasterLayer(subset_path, "Precipitation (all bands)")
            raster_ds = gdal.Open(raster_layer.source())

            if not raster_layer.isValid():
                feedback.reportError("The NetCDF raster layer is not valid.", fatalError=True)
                return {}

            # spatial metadata
            spatref = raster_layer.crs() if raster_layer.crs().isValid() else QgsCoordinateReferenceSystem('EPSG:4326')
            xres = raster_layer.rasterUnitsPerPixelX()
            yres = raster_layer.rasterUnitsPerPixelY()
            ext = raster_layer.extent()
            xmin = ext.xMinimum()
            xmax = ext.xMaximum()
            ymin = ext.yMinimum()
            ymax = ext.yMaximum()

            # number of bands
            raster_count = raster_ds.RasterCount
            feedback.pushInfo(f"Number of bands: {raster_count}")
            num_years = raster_count // 12

            # initialize arrays
            yearly_sum = None
            dry_sum = None

            # sum all bands
            for b in range(1, raster_count + 1):
                band_array = raster_ds.GetRasterBand(b).ReadAsArray()
                if yearly_sum is None:
                    yearly_sum = band_array
                else:
                    yearly_sum += band_array

            # final yearly average
            finalYearlyMeanRaster = yearly_sum*1000*30.4375 / num_years  # 30.4375 is the average number of days in a month over a 30 years time series with 7.5 leap years

            # dry month mean
            for i in range(num_years):
                dry_band_index = i * 12 + dry_month
                band_array = raster_ds.GetRasterBand(dry_band_index).ReadAsArray()

                if dry_sum is None:
                    dry_sum = band_array
                else:
                    dry_sum += band_array

            # final dry month average
            finalDryMeanRaster = dry_sum*1000*days_in_dry_month / num_years

        if not aggregated_selection:
            yearly_means = []
            dry_means = []
            for filename in netcdf_files:
                netcdf_file = os.path.join(netcdf_dir, filename)
                subdataset_path = 'NETCDF:"{}":pr'.format(netcdf_file)
                raster_layer_unc = QgsRasterLayer(subdataset_path, "Annual precipitation")
                rasterDataSource = gdal.Open(str(raster_layer_unc.source()))
                if firstFile:
                    spatref = raster_layer_unc.crs()
                    xres = raster_layer_unc.rasterUnitsPerPixelX()
                    yres = raster_layer_unc.rasterUnitsPerPixelY()
                    ext = raster_layer_unc.extent()
                    xmin = ext.xMinimum()
                    xmax = ext.xMaximum()
                    ymin = ext.yMinimum()
                    ymax = ext.yMaximum()
                    firstFile = False
                bands = [rasterDataSource.GetRasterBand(i).ReadAsArray()
                         for i in range(1, rasterDataSource.RasterCount + 1)]
                yearly_means.append(np.sum(np.stack(bands), axis=0))
                dry_means.append(rasterDataSource.GetRasterBand(dry_month).ReadAsArray())

            finalYearlyMeanRaster = np.mean(np.stack(yearly_means), axis=0)
            finalDryMeanRaster = np.mean(np.stack(dry_means), axis=0)

        outfnYearly = outputDir+ungaugedSourceName+'_yearlyPrecipitation.tif'
        outfnDry = outputDir+ungaugedSourceName+'_dryMonthPrecipitation.tif'

        # validate raster data before writing
        if finalYearlyMeanRaster is None:
            feedback.reportError("Error: finalYearlyMeanRaster is None!", fatalError=True)
            return {}
        if finalDryMeanRaster is None:
            feedback.reportError("Error: finalDryMeanRaster is None!", fatalError=True)
            return {}

        # create yearly precipitation raster
        self.createRaster(parameters, context, feedback, outfnYearly, xmax, xmin, xres, ymax, ymin, yres, spatref, finalYearlyMeanRaster)
        feedback.setProgressText(f"Debug: Output file path: {outfnYearly}")

        # create dry month precipitation raster
        self.createRaster(parameters, context, feedback, outfnDry, xmax, xmin, xres, ymax, ymin, yres, spatref, finalDryMeanRaster)
        feedback.setProgressText(f"Debug: Output file path: {outfnDry}")

        # save as raster layer
        precipitationYearlyLayer = QgsRasterLayer(outfnYearly, "precipitationYearly")
        if not precipitationYearlyLayer.isValid():
            feedback.reportError("Error: precipitationYearlyLayer is not valid!", fatalError=True)

        precipitationDryLayer = QgsRasterLayer(outfnDry, "precipitationDryMonth")
        if not precipitationDryLayer.isValid():
            feedback.reportError("Error: precipitationDryLayer is not valid!", fatalError=True)

        feedback.setProgressText("\nStart the zonal statistic of yearly precipitation")
        precipitation_yearly_ungauged = processing.run("native:zonalstatisticsfb", {
            'INPUT_RASTER': precipitationYearlyLayer,
            'RASTER_BAND': 1,
            'INPUT': JoinCatchmentsSettlementAreaSummarize,
            'COLUMN_PREFIX': "PrecYearly_",
            'STATISTICS': [2],  # mean
            'OUTPUT': 'TEMPORARY_OUTPUT'
            }, context=context)['OUTPUT']
        context.temporaryLayerStore().addMapLayer(precipitation_yearly_ungauged) = processing.run("native:zonalstatisticsfb", {
            'INPUT_RASTER': precipitationDryLayer,
            'RASTER_BAND': 1,
            'INPUT': precipitation_yearly_ungauged,
            'COLUMN_PREFIX': "PrecDry_",
            'STATISTICS': [2],  # mean
            'OUTPUT': 'TEMPORARY_OUTPUT'
            }, context=context)['OUTPUT']
        context.temporaryLayerStore().addMapLayer(finalLayer_ungauged)

        del JoinCatchmentsSettlementAreaSummarize, precipitation_yearly_ungauged

        # Remove "MEAN" from the column name if it exists
        if 'PrecYearly_mean' in [field.name() for field in finalLayer_ungauged.fields()]:
            with edit(finalLayer_ungauged):
                idx = finalLayer_ungauged.fields().indexOf('PrecYearly_mean')
                finalLayer_ungauged.renameAttribute(idx, 'PrecYearly')

        if 'PrecDry_mean' in [field.name() for field in finalLayer_ungauged.fields()]:
            with edit(finalLayer_ungauged):
                idx = finalLayer_ungauged.fields().indexOf('PrecDry_mean')
                finalLayer_ungauged.renameAttribute(idx, 'PrecDry')

        feedback.setProgressText("\nRemoving field")
        # remove unwanted fields
        fields_to_remove = ["RivNe_sum", "WatAr_sum", "ForAr_sum", "SettAr_sum", "ID_SC"]
        field_indices = [finalLayer_ungauged.fields().indexOf(field) for field in fields_to_remove]

        if field_indices:
            with edit(finalLayer_ungauged):
                finalLayer_ungauged.dataProvider().deleteAttributes(field_indices)
                finalLayer_ungauged.updateFields()
        else:
            feedback.pushInfo("No matching field found to delete")

        # define the output
        feedback.setProgressText("\nSaving the output")
        (sink_ungauged, dest_id_ungauged) = self.parameterAsSink(
            parameters, self.OUTPUTungauged, context, finalLayer_ungauged.fields(), finalLayer_ungauged.wkbType(), finalLayer_ungauged.sourceCrs()
            )

        for feat in finalLayer_ungauged.getFeatures():
            sink_ungauged.addFeature(feat)

        del finalLayer_ungauged
        feedback.setProgressText("\nSuccess: ungauged_subcatchments_geofactors.shp file was created successfully!")

        """
        Gauged subcatchments
        """
        feedback.setProgressText("\nStarting gauged subcatchments")

        # Calculates zonal statistics based on DEM
        feedback.setProgressText("\nCalculate Zonal statistics...")
        catchments_gauged = processing.run("native:zonalstatisticsfb", {
            'INPUT_RASTER': parameters[self.DGM],
            'RASTER_BAND': 1,
            'INPUT': parameters[self.gaugedSubcatch],
            'COLUMN_PREFIX': "H_",
            'STATISTICS': [2, 4, 5],
            'OUTPUT': 'TEMPORARY_OUTPUT'
            }, context=context)['OUTPUT']
        context.temporaryLayerStore().addMapLayer(catchments_gauged)

        # Set area and perimeter field to layer
        provider = catchments_gauged.dataProvider()
        provider.addAttributes([id_field, area_field, perimeter_field, shapeFactor_field])
        catchments_gauged.updateFields()
        # Calculate area and perimeter
        idxID = provider.fieldNameIndex('ID_SC')
        idxArea = provider.fieldNameIndex('AREA_SC')
        idxPerimeter = provider.fieldNameIndex('PERIM_SC')
        idxShapeFactor = provider.fieldNameIndex('SHAPE_SC')
        all_changes = {}
        for feature in catchments_gauged.getFeatures():
            geomArea = feature.geometry().area()
            geomPeri = feature.geometry().length()
            geomShapeFactor = geomPeri ** 2 / (2 * math.pi * geomArea)
            all_changes[feature.id()] = {
                idxID: feature.id(),
                idxArea: geomArea,
                idxPerimeter: geomPeri,
                idxShapeFactor: geomShapeFactor,
            }
        catchments_gauged.dataProvider().changeAttributeValues(all_changes)

        # Calculates zonal statistics based on the slope raster
        feedback.setProgressText("\nCalculate slope statistics...")
        processing.run("native:zonalstatistics", {
            'INPUT_RASTER': slope,
            'RASTER_BAND': 1,
            'INPUT_VECTOR': catchments_gauged,
            'COLUMN_PREFIX': "Slp_",
            'STATISTICS': [2, 4]
            }, context=context)

        # Calculates statistics based on river network
        JoinCatchmentsRiverSummarize = self.processProportions(parameters, context, feedback, catchments_gauged, outputDir, "RiverNetwork", "RivNe", parameters[self.riverNetwork], 1)
        del catchments_gauged, slope

        # Calculates statistics based on water area
        JoinCatchmentsWaterAreaSummarize = self.processProportions(parameters, context, feedback, JoinCatchmentsRiverSummarize, outputDir, "WaterArea", "WatAr", parameters[self.waterArea], 0)
        del JoinCatchmentsRiverSummarize

        # Calculates statistics based on forest area
        JoinCatchmentsForestAreaSummarize = self.processProportions(parameters, context, feedback, JoinCatchmentsWaterAreaSummarize, outputDir, "ForestArea", "ForAr", parameters[self.forestArea], 0)
        del JoinCatchmentsWaterAreaSummarize

        # Calculates statistics based on settlement area
        JoinCatchmentsSettlementAreaSummarize = self.processProportions(parameters, context, feedback, JoinCatchmentsForestAreaSummarize, outputDir, "SettlementArea", "SettAr", parameters[self.settlementArea], 0)
        del JoinCatchmentsForestAreaSummarize

        # Calculates river network density (rnd), proportion of water area (pwa), forest share and settlemet share
        feedback.setProgressText("\nCalculate river network density (rnd) and proportion of water area (pwa)...")
        provider = JoinCatchmentsSettlementAreaSummarize.dataProvider()
        rnd_field = QgsField("RivNetDens", QVariant.Double, 'double', 20, 3)
        pwa_field = QgsField("PropWatAr", QVariant.Double, 'double', 20, 3)
        fs_field = QgsField("Forest %", QVariant.Double, 'double', 20, 3)
        ss_field = QgsField("Settl %", QVariant.Double, 'double', 20, 3)
        provider.addAttributes([rnd_field, pwa_field, fs_field, ss_field])
        JoinCatchmentsSettlementAreaSummarize.updateFields()
        idxRND = provider.fieldNameIndex('RivNetDens')
        idxPWA = provider.fieldNameIndex('PropWatAr')
        idxFS = provider.fieldNameIndex('Forest %')
        idxSS = provider.fieldNameIndex('Settl %')
        idxRN_Sum = provider.fieldNameIndex('RivNe_sum')
        idxWA_Sum = provider.fieldNameIndex('WatAr_sum')
        idxFA_Sum = provider.fieldNameIndex('ForAr_sum')
        idxSA_Sum = provider.fieldNameIndex('SettAr_sum')
        for feature in JoinCatchmentsSettlementAreaSummarize.getFeatures():
            area_sc = feature["AREA_SC"]
            if not area_sc or area_sc <= 0:
                feedback.pushWarning(f"Skipping feature {feature.id()}: AREA_SC is {area_sc}. Assigning 0 to derived fields.")
                attrs = {idxRND: 0, idxPWA: 0, idxFS: 0, idxSS: 0, idxRN_Sum: 0, idxWA_Sum: 0, idxFA_Sum: 0, idxSA_Sum: 0}
                JoinCatchmentsSettlementAreaSummarize.dataProvider().changeAttributeValues({feature.id(): attrs})
                continue
            if feature["RivNe_sum"] is not None:
                calcRND = (feature["RivNe_sum"] / area_sc) * 100
                RNsum = feature["RivNe_sum"]
            else:
                calcRND = 0
                RNsum = 0
            if feature["WatAr_sum"] is not None:
                calcPWA = (feature["WatAr_sum"] / area_sc) * 100
                WAsum = feature["WatAr_sum"]
            else:
                calcPWA = 0
                WAsum = 0
            if feature["ForAr_sum"] is not None:
                calcFS = (feature["ForAr_sum"] / area_sc) * 100
                FAsum = feature["ForAr_sum"]
            else:
                calcFS = 0
                FAsum = 0
            if feature["SettAr_sum"] is not None:
                calcSS = (feature["SettAr_sum"] / area_sc) * 100
                SAsum = feature["SettAr_sum"]
            else:
                calcSS = 0
                SAsum = 0
            attrs = {idxRND: calcRND, idxPWA: calcPWA, idxFS: calcFS, idxSS: calcSS, idxRN_Sum: RNsum, idxWA_Sum: WAsum, idxFA_Sum: FAsum, idxSA_Sum: SAsum}
            JoinCatchmentsSettlementAreaSummarize.dataProvider().changeAttributeValues({feature.id(): attrs})

        if not JoinCatchmentsSettlementAreaSummarize.isValid():
            feedback.reportError("Error: JoinCatchmentsSettlementAreaSummarize is not valid!", fatalError=True)

        # Calculation of precipitation
        feedback.setProgressText("\nCalculate precipitation")
        feedback.setProgress(80)    # set the progress to 80% because otherwise it is stuck at 100

        # Reuse precipitation raster layers from ungauged section (identical data)

        # zonal statistics
        feedback.setProgressText("\nStart the zonal statistic of yearly precipitation")
        precipitation_yearly_gauged = processing.run("native:zonalstatisticsfb", {
            'INPUT_RASTER': precipitationYearlyLayer,
            'RASTER_BAND': 1,
            'INPUT': JoinCatchmentsSettlementAreaSummarize,
            'COLUMN_PREFIX': "PrecYearly_",
            'STATISTICS': [2],  # mean
            'OUTPUT': 'TEMPORARY_OUTPUT'
            }, context=context)['OUTPUT']
        context.temporaryLayerStore().addMapLayer(precipitation_yearly_gauged) = processing.run("native:zonalstatisticsfb", {
            'INPUT_RASTER': precipitationDryLayer,
            'RASTER_BAND': 1,
            'INPUT': precipitation_yearly_gauged,
            'COLUMN_PREFIX': "PrecDry_",
            'STATISTICS': [2],  # mean
            'OUTPUT': 'TEMPORARY_OUTPUT'
            }, context=context)['OUTPUT']
        context.temporaryLayerStore().addMapLayer(finalLayer_gauged)

        del JoinCatchmentsSettlementAreaSummarize, precipitation_yearly_gauged

        # Remove "mean" from the column name if it exists
        if 'PrecYearly_mean' in [field.name() for field in finalLayer_gauged.fields()]:
            with edit(finalLayer_gauged):
                idx = finalLayer_gauged.fields().indexOf('PrecYearly_mean')
                finalLayer_gauged.renameAttribute(idx, 'PrecYearly')

        if 'PrecDry_mean' in [field.name() for field in finalLayer_gauged.fields()]:
            with edit(finalLayer_gauged):
                idx = finalLayer_gauged.fields().indexOf('PrecDry_mean')
                finalLayer_gauged.renameAttribute(idx, 'PrecDry')

        # remove unwanted fields
        fields_to_remove = ["RivNe_sum", "WatAr_sum", "ForAr_sum", "SettAr_sum", "ID_SC"]
        field_indices = [finalLayer_gauged.fields().indexOf(field) for field in fields_to_remove]
        if field_indices:
            with edit(finalLayer_gauged):
                finalLayer_gauged.dataProvider().deleteAttributes(field_indices)
                finalLayer_gauged.updateFields()
        else:
            feedback.pushInfo("No matching field found to delete")

        # define the output
        (sink_gauged, dest_id_gauged) = self.parameterAsSink(parameters, self.OUTPUTgauged, context,
                                                             finalLayer_gauged.fields(), finalLayer_gauged.wkbType(), finalLayer_gauged.sourceCrs())

        for feat in finalLayer_gauged.getFeatures():
            sink_gauged.addFeature(feat)

        del finalLayer_gauged

        feedback.setProgressText("\nSuccess: gauged_subcatchments_geofactors.shp file was created successfully!")

        # return the result
        return {
            self.OUTPUTungauged: dest_id_ungauged,
            self.OUTPUTgauged: dest_id_gauged
            }

    def name(self):
        """
        Returns the algorithm name, used for identifying the algorithm. This
        string should be fixed for the algorithm, and must not be localised.
        The name should be unique within each provider. Names should contain
        lowercase alphanumeric characters only and no spaces or other
        formatting characters.
        """
        return '3 - Calculate geofactors'

    def displayName(self):
        """
        Returns the translated algorithm name, which should be used for any
        user-visible display of the algorithm name.
        """
        return self.tr(self.name())

    def group(self):
        """
        Returns the name of the group this algorithm belongs to. This string
        should be localised.
        """
        return self.tr(self.groupId())

    def groupId(self):
        """
        Returns the unique ID of the group this algorithm belongs to. This
        string should be fixed for the algorithm, and must not be localised.
        The group id should be unique within each provider. Group id should
        contain lowercase alphanumeric characters only and no spaces or other
        formatting characters.
        """
        return 'Hydro-Module'

    def helpUrl(self):
        # Return a URL or local file path to your documentation
        return "https://hosting-apriora-manual.readthedocs.io/en/latest/hydro_module/calculate_geofactors.html"

    def tr(self, string):
        return QCoreApplication.translate('Processing', string)

    def createInstance(self):
        return CalculateGeofactors()
