# -*- coding: utf-8 -*-

"""
/***************************************************************************
 APRIORA
                                 A QGIS plugin
 Collection of APRIORA Plugins
 Generated by Plugin Builder: http://g-sherman.github.io/Qgis-Plugin-Builder/
                              -------------------
        begin                : 2024-06-13
        copyright            : (C) 2024 by Cristiano Guidi
        email                : cristiano.guidi2@uni-rostock.de
 ***************************************************************************/

/***************************************************************************
 *                                                                         *
 *   This program is free software; you can redistribute it and/or modify  *
 *   it under the terms of the GNU General Public License as published by  *
 *   the Free Software Foundation; either version 2 of the License, or     *
 *   (at your option) any later version.                                   *
 *                                                                         *
 ***************************************************************************/
"""

__author__ = 'Cristiano Guidi'
__date__ = '2024-06-13'
__copyright__ = '(C) 2024 by Cristiano Guidi'

# This will get replaced with a git SHA1 when you do a git archive

__revision__ = '$Format:%H$'

from qgis.PyQt.QtCore import QCoreApplication
from PyQt5.QtCore import QVariant
from qgis.core import (QgsProcessingAlgorithm,
                       QgsProcessing,
                       QgsProcessingException,
                       QgsProcessingParameterFeatureSource,
                       QgsProcessingParameterFeatureSink,
                       QgsProcessingParameterField,
                       QgsProject,
                       QgsFields,
                       QgsField,
                       QgsFeature,
                       QgsGeometry,
                       QgsSpatialIndex,
                       Qgis)
import processing
import numpy as np

"""
* Part of this file is adapted from WaterNetAnalyzer QGIS plugin
* Copyright (C) 2020 by Jannik Schilling
* Licensed under the GNU General Public License v2.0
"""


class UpstreamDownstream(QgsProcessingAlgorithm):
    riverNetwork = "RiverNetwork"
    catchmentAreas = 'CatchmentAreas'
    gaugingStations = "GaugingStations"
    meanFlow = "MeanFlow"
    MNQ = "MNQ"
    OUTPUT_gauged = "OUTPUT_gauged"

    def shortHelpString(self):
        return self.tr(
            """
            This tool identifies the contributing (upstream) subcatchments for each \
            gauging station and produces a single dissolved polygon per station.

            Steps performed:
            1. Match each gauging station to the nearest river section (via NET_ID).
            2. Traverse the network upstream to find all contributing river segments.
            3. Collect the subcatchments associated with those segments (via CATCH_ID).
            4. Dissolve them into one polygon per gauging station.
            5. Attach Mean Flow and Mean Low Flow from the gauging-station layer.

            Inputs:
            - Ungauged subcatchments: output of Tool 1 ("Ungauged subcatch").
            - Fixed river network: output of Tool 1 ("Fixed river network").
            - Gauging stations: point layer with flow data columns.
            - Mean Flow / Mean Low Flow: select the corresponding fields.

            Output:
            - Gauged subcatchments: one dissolved polygon per gauging station, carrying Mean_Flow and M_Low_Flow attributes.

            Workflow:
            1. Select the layers and fields.
            2. Click Run.

            Note: The river network must contain NET_ID, NET_TO and CATCH_ID fields \
            (produced by Tool 1). Both layers must share the same CRS (reprojection \
            is attempted automatically for gauging stations if needed).
            """)

    def initAlgorithm(self, config):
        self.addParameter(
            QgsProcessingParameterFeatureSource(
                self.catchmentAreas,
                self.tr('Ungauged subcatchments'),
                [QgsProcessing.TypeVectorPolygon],
                defaultValue=QgsProject.instance().mapLayersByName("Ungauged subcatch")[0].id() if QgsProject.instance().mapLayersByName("Ungauged subcatch") else None
            )
        )

        self.addParameter(
            QgsProcessingParameterFeatureSource(
                self.riverNetwork,
                self.tr('Fixed river network'),
                [QgsProcessing.TypeVectorLine],
                defaultValue=QgsProject.instance().mapLayersByName("Fixed river network")[0].id() if QgsProject.instance().mapLayersByName("Fixed river network") else None
            )
        )

        self.addParameter(
            QgsProcessingParameterFeatureSource(
                self.gaugingStations,
                self.tr('Gauging stations'),
                [QgsProcessing.TypeVectorPoint]
            )
        )

        # mean flow
        self.addParameter(
            QgsProcessingParameterField(
                self.meanFlow,
                description=self.tr('Select Mean Flow field'),
                parentLayerParameterName=self.gaugingStations,
                type=QgsProcessingParameterField.Any
            )
        )

        # mean low flow
        self.addParameter(
            QgsProcessingParameterField(
                self.MNQ,
                description=self.tr('Select Mean Low Flow field'),
                parentLayerParameterName=self.gaugingStations,
                type=QgsProcessingParameterField.Any
            )
        )

        # output related to gauged subcatchments
        self.addParameter(
            QgsProcessingParameterFeatureSink(
                self.OUTPUT_gauged,
                self.tr('Gauged subcatch'),
                QgsProcessing.TypeVectorPolygon
            )
        )

    def processAlgorithm(self, parameters, context, feedback):
        '''loading the subcatchments'''
        feedback.setProgressText(self.tr("Loading subcatchments..\n "))
        subcatch = self.parameterAsVectorLayer(parameters, self.catchmentAreas, context)
        if subcatch is None:
            raise QgsProcessingException(self.invalidSourceError(parameters, self.catchmentAreas))
        river_layer = self.parameterAsVectorLayer(parameters, self.riverNetwork, context)
        MQ_field = self.parameterAsString(parameters, self.meanFlow, context)
        MNQ_field = self.parameterAsString(parameters, self.MNQ, context)

        """
        The river network file can present multiple river sections within a subcatchment.
        Every river section needs to be associated with one subcatchment only and a subcatchment needs to be associated with one river section only.
        """
        # fix subcatchment geometries
        geos_version_str = Qgis.geosVersion()
        major, minor = (int(x) for x in geos_version_str.split('.')[:2])
        method = 1 if (major > 3 or (major == 3 and minor >= 10)) else 0
        feedback.pushInfo(f"GEOS version: {geos_version_str}")

        subcatch_fixed = processing.run("native:fixgeometries", {
            'INPUT': subcatch,
            'METHOD': method,
            'OUTPUT': 'TEMPORARY_OUTPUT'},
            context=context, feedback=feedback)["OUTPUT"]
        context.temporaryLayerStore().addMapLayer(subcatch_fixed)

        '''loading the network'''
        feedback.setProgressText(self.tr("Loading network..\n "))
        waternet = river_layer

        '''loading the gauging stations'''
        gaug_stat = self.parameterAsVectorLayer(parameters, self.gaugingStations, context)
        if gaug_stat is None or gaug_stat.featureCount() == 0:
            raise QgsProcessingException("No gauging stations found. Please provide a valid gauging station layer.")

        # Field indices for the network data array.
        # DataArr layout: [NET_ID, NET_ID, NET_TO, qgis_fid]
        #   col 0 = segment id (NET_ID)
        #   col 1 = same as col 0 (used as MARKER during traversal)
        #   col 2 = downstream target (NET_TO)
        #   col 3 = QGIS feature id
        id_field = "NET_ID"
        to_field = "NET_TO"

        idxId = waternet.fields().indexFromName(id_field)
        idxTo = waternet.fields().indexFromName(to_field)

        if idxId == -1 or idxTo == -1:
            raise QgsProcessingException("Required fields (NET_ID, NET_TO) not found in river network.")

        subcat_layer = subcatch_fixed
        feedback.pushInfo(f"\nNumber of features in the subcat_layer: {subcat_layer.featureCount()}")

        # Identify CRS of subcatchment layer
        subcat_crs = subcat_layer.crs()
        feedback.pushInfo(f"Subcatchment layer CRS: {subcat_crs.authid()}")

        # Reproject gauging station layer to match subcatchment CRS
        gaug_reprojected = processing.run("native:reprojectlayer", {
            'INPUT': gaug_stat,
            'TARGET_CRS': subcat_crs,
            'CONVERT_CURVED_GEOMETRIES': False,
            'OUTPUT': 'TEMPORARY_OUTPUT'
        })
        gaug_stat = gaug_reprojected["OUTPUT"]
        context.temporaryLayerStore().addMapLayer(gaug_stat)
        feedback.pushInfo(f"Gauging stations reprojected to CRS: {gaug_stat.crs().authid()}")

        # we do the same with the gauging stations. So we have the same IDs to identify river network, gauging stations and subcatchments
        gaug_result = processing.run("native:joinattributesbylocation", {
            'INPUT': gaug_stat,
            'PREDICATE': [0],
            'JOIN': subcat_layer,
            'JOIN_FIELDS': ['CATCH_ID'],
            'METHOD': 0,
            'DISCARD_NONMATCHING': True,
            'PREFIX': '',
            'OUTPUT': 'TEMPORARY_OUTPUT'})
        gaug_id = gaug_result["OUTPUT"]
        context.temporaryLayerStore().addMapLayer(gaug_id)

        feedback.pushInfo(f"\nNumber of features in the gaug_id: {gaug_id.featureCount()}")

        gauged_fields = QgsFields(subcat_layer.fields())
        gauged_fields.append(QgsField("Mean_Flow", QVariant.Double))
        gauged_fields.append(QgsField("M_Low_Flow", QVariant.Double))

        # initialize the feature sink for gauged subcatchments
        (sink_gauged, dest_id_gauged) = self.parameterAsSink(
            parameters,
            self.OUTPUT_gauged,
            context,
            gauged_fields,
            subcat_layer.wkbType(),
            subcat_layer.sourceCrs()
        )

        def nextFtsSel(Sect, MARKER2):
            if Sect == 'U':
                clm_current = 1
                clm_search = 2
            if Sect == 'D':
                clm_current = 2
                clm_search = 1
            vtx_connect = DataArr[np.where(DataArr[:, 0] == MARKER2)[0].tolist(), clm_current][0]  # connecting vertex of actual segment
            rows_connect = np.where(DataArr[:, clm_search] == vtx_connect)[0].tolist()  # find rows in DataArr with matching vertices to vtx_connect
            unconnected_errors = [DataArr[x, 3] for x in rows_connect if DataArr[x, clm_current] == 'unconnected']  # this can only happen after manual editing
            if len(unconnected_errors) > 0:
                waternet.removeSelection()
                waternet.selectByIds(unconnected_errors, waternet.SelectBehavior(1))
                raise QgsProcessingException(
                    'The selected features in the flow are marked as \'unconnected\' '
                    + '(most likely because of manual editing). Please delete the columns with the network information ('
                    + id_field
                    + ', '
                    + to_field
                    + ') and run tool 1 \"Water Network Constructor\" again.'
                )
            return (rows_connect)

        def find_closest_river_section(outlet_point, spatial_index, river_map, feedback):
            '''
            Finds the closest river section to the gauging station
            '''
            # convert the outlet_point to QgsGeometry
            outlet_geometry = QgsGeometry.fromPointXY(outlet_point)
            nearest_ids = spatial_index.nearestNeighbor(outlet_geometry, 5)  # get the 5 nearest features
            closest_section = None
            min_distance = float("inf")

            # iterate through the closest matches and find the closest section
            for fid in nearest_ids:
                feature = river_map[fid]
                section_geom = feature.geometry()
                distance = section_geom.distance(outlet_geometry)

                if distance < min_distance:
                    min_distance = distance
                    closest_section = feature

            if closest_section:
                feedback.pushInfo(f"\nClosest section found: [NET_ID]: {closest_section['NET_ID']} \n Distance: {min_distance}")
            else:
                feedback.pushInfo("\nNo closest section found.")

            return closest_section

        # build a spatial index
        spatial_index = QgsSpatialIndex()
        river_map = {}

        for feature in waternet.getFeatures():
            fid = feature.id()
            river_map[fid] = feature
            spatial_index.addFeature(feature)

        '''Find upstream network for each gauging station'''
        feedback.setProgressText("Processing gauging stations...")
        river_crs = waternet.crs()
        outlet_crs = gaug_id.crs()

        if outlet_crs is not river_crs:
            feedback.pushInfo(f"CRS mismatch detected. Reprojecting gauging stations to the river network CRS: {river_crs}.")
            gaug_reproject = processing.run("native:reprojectlayer", {
                'INPUT': gaug_id,
                'TARGET_CRS': river_crs,
                'CONVERT_CURVED_GEOMETRIES': False,
                'OUTPUT': 'TEMPORARY_OUTPUT'
                })["OUTPUT"]
            context.temporaryLayerStore().addMapLayer(gaug_reproject)
        else:
            gaug_reproject = gaug_id

        # iterate over gauging stations and find contributing subcatchments for each
        for station in gaug_reproject.getFeatures():
            # little debugging
            feedback.pushInfo(f"\nProcessing gauging station ID: {station.id()}")

            outlet_point = station.geometry().asPoint()
            closest_feature = find_closest_river_section(outlet_point, spatial_index, river_map, feedback)

            # raise an error in case closest feature is none?

            '''getting the selected segment'''
            startF = closest_feature  # feature to start with
            if not startF:
                feedback.reportError(self.tr('{0}: No river network found close to the gauging station ').format(self.displayName()))
                raise QgsProcessingException()
            else:
                startId = startF.id()
                if startF.attributes()[idxId] is not None:
                    StartMarker = startF.attributes()[idxId]
                else:
                    feedback.reportError('This segment has an invalid ID (NULL)')
                    raise QgsProcessingException()
                if startF.attributes()[idxTo] == 'unconnected':
                    feedback.reportError(self.tr('{0}: Unconnected segment selected.').format(self.displayName()))
                    raise QgsProcessingException()

            '''selection: flow path upstream/downstream
            downstream: 1
            upstream: 0  # in this case, only upstream is interesting
            '''
            Section = 'U'
            Section_long = 'upstream'

            '''load data from layer "waternet" '''
            # DataArr columns: [0: NET_ID, 1: NET_ID (same, used as MARKER), 2: NET_TO, 3: qgis fid]
            Data = [[str(f.attribute(idxId)), str(f.attribute(idxId)), str(f.attribute(idxTo)), f.id()] for f in waternet.getFeatures()]
            DataArr = np.array(Data, dtype='object')
            feedback.setProgressText(self.tr("Data loaded\n Calculating {0}\n").format(str(Section_long)))
            feedback.setProgress(20)

            '''this was planned as an option: should the first selected segment be part of the final selection?
            at the moment it´s permanently part of the final selection'''
            first_in_selection = True
            if not first_in_selection:
                net_route = list()
            else:
                net_route = [startId]

            '''find flow path upstream or downstream'''
            MARKER = str(StartMarker)  # NET_ID of first segment
            safe = ["X"]  # a list to safe segments when the net separates; "X" indicates an empty list and works as a MARKER for the while loop below
            forks = []  # a list for forks in flow path...because forks are interesting....
            origins = []  # a list for origins/river heads upstream

            i = 1
            total = 70 / subcatch.featureCount() if subcatch.featureCount() else 0  # for feedback between 20% and 90%
            while str(MARKER) != 'X':
                if feedback.isCanceled():
                    break
                next_rows = nextFtsSel(Section, MARKER)
                if len(next_rows) > 0:  # sometimes segments are saved in net_route...then they are deleted
                    next_rows = [Z for Z in next_rows if DataArr[Z, 3] not in net_route]
                    net_route = net_route + DataArr[next_rows, 3].tolist()
                if len(next_rows) > 1:
                    if Section == 'D':
                        forks = forks + [MARKER]
                    MARKER = DataArr[next_rows[0], 0]  # change MARKER to the NET_ID of one of the next segments
                    safe = safe + DataArr[next_rows[1:], 0].tolist()
                if len(next_rows) == 1:
                    MARKER = DataArr[next_rows[0], 0]
                if len(next_rows) == 0:
                    if Section == 'U':
                        origins = origins + [MARKER]
                    MARKER = safe[-1]  # change MARKER to the last "saved" NET_ID
                    safe = safe[: -1]  # delete used NET_ID from "safe"-list
                feedback.setProgress(20+total*i)
                i += 1

            # little debugging
            feedback.pushInfo(f"\nPrint net_route: {net_route}")

            # convert net_route (feature IDs) to a set for a faster loop
            net_route_set = set(net_route)

            # extract corresponding CATCH_ID values
            net_id_values = []
            for feature in waternet.getFeatures():
                if feature.id() in net_route_set:
                    net_id_values.append(feature["CATCH_ID"])

            # little debugging
            feedback.pushInfo(f"Extracted CATCH_ID values: {net_id_values}")

            # construct the expression to filter the subcatchment based on the IDs stored in net_id_values
            net_id_str = ", ".join(map(str, net_id_values))  # convert IDs to a comma-separeted string
            expression = f'"CATCH_ID" IN ({net_id_str})'

            # extract upstream subcatchments
            upstream_catch_result = processing.run("native:extractbyexpression", {
                'INPUT': subcat_layer,
                'EXPRESSION': expression,
                'OUTPUT': 'TEMPORARY_OUTPUT'})
            upstream_catch = upstream_catch_result["OUTPUT"]
            context.temporaryLayerStore().addMapLayer(upstream_catch)

            # dissolve the contributing subcatchments into one polygon per station
            dissolve_result = processing.run("native:dissolve", {
                'INPUT': upstream_catch,
                'FIELD': [],
                'SEPARATE_DISJOINT': False,
                'OUTPUT': 'TEMPORARY_OUTPUT'
                })
            dissolve_layer = dissolve_result["OUTPUT"]
            feedback.pushInfo("\ndissolve_layer = done")

            # identify which subcatchment the gauging station sits in
            net_id_gaug = station["CATCH_ID"]

            # find the subcatchment with the same CATCH_ID
            matching_attributes = None
            for feature in subcat_layer.getFeatures():
                if feature["CATCH_ID"] == net_id_gaug:
                    matching_attributes = feature.attributes()
                    break

            if not matching_attributes:
                feedback.pushInfo(f"\nWarning: no subcatchment found with CATCH_ID {net_id_gaug}. Skipping.")
                continue

            # use the dissolved geometry with the attributes from the matching subcatchment
            dissolve_feature = next(dissolve_layer.getFeatures())
            dissolve_geom = dissolve_feature.geometry()

            # find the gauging station record and write to sink with flow attributes
            for gaug in gaug_reproject.getFeatures():
                if gaug["CATCH_ID"] == net_id_gaug:
                    gauged_feature = QgsFeature(gauged_fields)
                    gauged_feature.setGeometry(dissolve_geom)
                    gauged_feature.setAttributes(matching_attributes + [gaug[MQ_field], gaug[MNQ_field]])
                    sink_gauged.addFeature(gauged_feature)

        return {
            self.OUTPUT_gauged: dest_id_gauged,
            }

    def name(self):
        """
        Returns the algorithm name, used for identifying the algorithm. This
        string should be fixed for the algorithm, and must not be localised.
        The name should be unique within each provider. Names should contain
        lowercase alphanumeric characters only and no spaces or other
        formatting characters.
        """
        return '2 - Contributing area of gauging station'

    def displayName(self):
        """
        Returns the translated algorithm name, which should be used for any
        user-visible display of the algorithm name.
        """
        return self.tr(self.name())

    def group(self):
        """
        Returns the name of the group this algorithm belongs to. This string
        should be localised.
        """
        return self.tr(self.groupId())

    def groupId(self):
        """
        Returns the unique ID of the group this algorithm belongs to. This
        string should be fixed for the algorithm, and must not be localised.
        The group id should be unique within each provider. Group id should
        contain lowercase alphanumeric characters only and no spaces or other
        formatting characters.
        """
        return 'Hydro-Module'

    def helpUrl(self):
        # Return a URL or local file path to your documentation
        return "https://hosting-apriora-manual.readthedocs.io/en/latest/hydro_module/contributing_area.html"

    def tr(self, string):
        return QCoreApplication.translate('Processing', string)

    def createInstance(self):
        return UpstreamDownstream()
