# -*- coding: utf-8 -*-

"""
/***************************************************************************
 APRIORA
                                 A QGIS plugin
 Collection of APRIORA Plugins
 Generated by Plugin Builder: http://g-sherman.github.io/Qgis-Plugin-Builder/
                              -------------------
        begin                : 2024-06-13
        copyright            : (C) 2024 by Cristiano Guidi
        email                : cristiano.guidi2@uni-rostock.de
 ***************************************************************************/

/***************************************************************************
 *                                                                         *
 *   This program is free software; you can redistribute it and/or modify  *
 *   it under the terms of the GNU General Public License as published by  *
 *   the Free Software Foundation; either version 2 of the License, or     *
 *   (at your option) any later version.                                   *
 *                                                                         *
 ***************************************************************************/
"""

__author__ = 'Cristiano Guidi'
__date__ = '2024-06-13'
__copyright__ = '(C) 2024 by Cristiano Guidi'

# This will get replaced with a git SHA1 when you do a git archive

__revision__ = '$Format:%H$'

import pandas as pd
from qgis.PyQt.QtCore import QCoreApplication, QVariant
from qgis.core import (QgsFeature,
                       QgsFeatureSink,
                       QgsFields,
                       QgsField,
                       QgsProcessing,
                       QgsProcessingAlgorithm,
                       QgsProcessingParameterFeatureSource,
                       QgsProcessingParameterFeatureSink,
                       QgsProcessingParameterField,
                       QgsProcessingParameterMapLayer,
                       QgsProject
                       )


class EmissionLoads(QgsProcessingAlgorithm):

    # Constants used to refer to parameters and outputs. They will be
    # used when calling the algorithm from another algorithm, or when
    # calling from the QGIS console.

    emissionPoints = 'EmissionPoints'
    connInh = 'connInh'
    WWTPflow = 'WWTPflow'
    apiTable = "api_table"
    OUTPUT = 'OUTPUT'

    def shortHelpString(self):
        return self.tr("""
            This tool calculates the load of previously selected APIs (Active Pharmaceutical Ingredients) at each WWTP \
            (Waste Water Treatment Plant) within a catchment.
            IMPORTANT: Before using this tool, you MUST first run the '5 - API parameter selection' tool and click \
            'Export Table' to generate the API_parameters table.
            Workflow:
            1. First, open and configure the '5 - API parameter selection' tool to select your APIs and parameters.
            2. Click 'Export Table' in Tool 5 to generate and add the API_parameters layer to the project.
            3. Under 'Emission Points of WWTP' select the point shapefile containing the WWTPs.
            4. Select the 'Connected inhabitant field' from the WWTP layer.
            5. Optionally, select the 'WWTP annual effluent flow' field (used later for dilution ratio).
            6. Under 'API Parameters Table' select the table layer generated by Tool 5.
            7. Click on 'Run'.
        """)

    def initAlgorithm(self, config):
        self.addParameter(
            QgsProcessingParameterFeatureSource(
                self.emissionPoints,
                self.tr('Emission Points of WWTP'),
                [QgsProcessing.TypeVectorPoint]
            )
        )

        self.addParameter(
            QgsProcessingParameterField(
                self.connInh,
                self.tr("Connected inhabitant field"),
                parentLayerParameterName=self.emissionPoints,
                type=QgsProcessingParameterField.Any,
            )
        )

        self.addParameter(
            QgsProcessingParameterField(
                self.WWTPflow,
                self.tr("WWTP annual effluent flow [m³/a]"),
                parentLayerParameterName=self.emissionPoints,
                type=QgsProcessingParameterField.Any,
                optional=True
            )
        )

        # API parameters table (layer from Tool 5)
        self.addParameter(
            QgsProcessingParameterMapLayer(
                self.apiTable,
                description=self.tr('API Parameters Table'),
                types=[QgsProcessing.TypeVector],
                defaultValue=QgsProject.instance().mapLayersByName("API_parameters")[0].id() if QgsProject.instance().mapLayersByName("API_parameters") else None
            )
        )

        self.addParameter(
            QgsProcessingParameterFeatureSink(
                self.OUTPUT,
                self.tr('Emission Loads'),
                QgsProcessing.TypeVectorPoint
            )
        )

    def processAlgorithm(self, parameters, context, feedback):
        # get input parameters
        layer = self.parameterAsVectorLayer(parameters, self.emissionPoints, context)
        api_layer = self.parameterAsLayer(parameters, self.apiTable, context)
        conn_inh_field = self.parameterAsString(parameters, self.connInh, context)
        wwtp_flow_field = self.parameterAsString(parameters, self.WWTPflow, context)

        # read API parameters from the layer into a DataFrame
        try:
            field_names = [f.name() for f in api_layer.fields()]
            rows = []
            for feat in api_layer.getFeatures():
                rows.append([feat[fn] for fn in field_names])
            api_df = pd.DataFrame(rows, columns=field_names)
        except Exception as e:
            feedback.reportError(f"Could not read API parameters layer: {e}")
            return {}

        if len(api_df.columns) < 3:
            feedback.reportError("API parameters table must have at least 3 columns (ID, Name, Tech. Class).")
            return {}

        # The first 3 columns are always: ID field, Name field, Tech. Class field
        # Their names match the original shapefile field names chosen by the user in Tool 5
        id_col = api_df.columns[0]
        name_col = api_df.columns[1]
        tc_col = api_df.columns[2]
        feedback.pushInfo(f"Table structure: ID='{id_col}', Name='{name_col}', TC='{tc_col}'")

        # The ID column name in the table matches the shapefile field name
        id_field = id_col

        # Identify API columns: everything after the 3 fixed columns and before RR_ columns
        remaining = api_df.columns[3:]
        api_names = [c for c in remaining if not c.startswith("RR_")]
        feedback.pushInfo(f"APIs found in table: {api_names}")

        # build output fields: ID, name, optionally WWTP flow, then one field per API
        fields = QgsFields()
        fields.append(QgsField(id_field, layer.fields().field(id_field).type()))
        fields.append(QgsField(name_col, QVariant.String))
        if wwtp_flow_field:
            fields.append(QgsField('Q_WWTP', QVariant.Double))
        for api in api_names:
            fields.append(QgsField(f"{api[:4]}[kg/a]", QVariant.Double))

        # prepare output sink
        (sink, dest_id) = self.parameterAsSink(
            parameters, self.OUTPUT, context,
            fields, layer.wkbType(), layer.sourceCrs()
        )

        for feature in layer.getFeatures():
            wwtp_id = feature[id_field]
            geom = feature.geometry()

            # match row by ID column
            row = api_df[api_df[id_col].astype(str) == str(wwtp_id)]
            if row.empty:
                feedback.reportError(f"No match in API parameters table for {id_field} = {wwtp_id}")
                continue

            # get connected inhabitants from the WWTP layer
            try:
                inh = float(feature[conn_inh_field])
            except (TypeError, ValueError, KeyError):
                feedback.reportError(f"Connected inhabitants invalid for {id_field} = {wwtp_id}")
                inh = 0.0

            # get WWTP effluent flow if field was selected
            wwtp_flow_val = None
            if wwtp_flow_field:
                try:
                    wwtp_flow_val = float(feature[wwtp_flow_field])
                except (TypeError, ValueError, KeyError):
                    wwtp_flow_val = None

            # get WWTP name from the table
            wwtp_name = str(row.iloc[0].get(name_col, ""))

            feedback.pushInfo(f"Analyzing WWTP with id: {wwtp_id}, name: {wwtp_name}")

            new_attrs = [feature[id_field], wwtp_name]
            if wwtp_flow_field:
                new_attrs.append(wwtp_flow_val)

            for api in api_names:
                try:
                    input_val = float(row.iloc[0][api])
                except (TypeError, ValueError):
                    input_val = 0.0
                # Strip unit suffix (e.g. " [mg/inh./a]") to match RR column name
                base_api = api.split(" [")[0] if " [" in api else api
                rr_col = f"RR_{base_api}"
                try:
                    rr = float(row.iloc[0][rr_col]) if rr_col in row.columns else 0.0
                except (TypeError, ValueError):
                    rr = 0.0

                adjusted_load = input_val * inh * (1 - rr) / 1_000_000
                new_attrs.append(adjusted_load)
                feedback.pushInfo(
                    f"  {api}: input={input_val}, RR={rr}, "
                    f"inh={inh}, load={adjusted_load:.6f} kg/a"
                )

            feedback.pushInfo("")  # blank line between WWTPs

            new_feature = QgsFeature()
            new_feature.setGeometry(geom)
            new_feature.setAttributes(new_attrs)
            sink.addFeature(new_feature, QgsFeatureSink.FastInsert)

        return {self.OUTPUT: dest_id}

    def name(self):
        return '6 - Emission Loads'

    def displayName(self):
        return self.tr(self.name())

    def group(self):
        return self.tr(self.groupId())

    def groupId(self):
        return 'API emission'

    def helpUrl(self):
        # Return a URL or local file path to your documentation
        return "https://hosting-apriora-manual.readthedocs.io/en/latest/api_emission/Emission_Load.html"

    def tr(self, string):
        return QCoreApplication.translate('Processing', string)

    def createInstance(self):
        return EmissionLoads()
