# -*- coding: utf-8 -*-

"""
/***************************************************************************
 APRIORA
                                 A QGIS plugin
 Collection of APRIORA Plugins
 Generated by Plugin Builder: http://g-sherman.github.io/Qgis-Plugin-Builder/
                              -------------------
        begin                : 2024-06-13
        copyright            : (C) 2024 by Cristiano Guidi
        email                : cristiano.guidi2@uni-rostock.de
 ***************************************************************************/

/***************************************************************************
 *                                                                         *
 *   This program is free software; you can redistribute it and/or modify  *
 *   it under the terms of the GNU General Public License as published by  *
 *   the Free Software Foundation; either version 2 of the License, or     *
 *   (at your option) any later version.                                   *
 *                                                                         *
 ***************************************************************************/
"""

__author__ = 'Cristiano Guidi'
__date__ = '2024-06-13'
__copyright__ = '(C) 2024 by Cristiano Guidi'

# This will get replaced with a git SHA1 when you do a git archive

__revision__ = '$Format:%H$'

import os
import pandas as pd
import numpy as np
from qgis.PyQt.QtCore import QCoreApplication, QVariant
from qgis.core import (NULL,
                       QgsFeature,
                       QgsField,
                       QgsProcessing,
                       QgsProcessingAlgorithm,
                       QgsProcessingParameterEnum,
                       QgsProcessingParameterFeatureSink,
                       QgsProcessingParameterFeatureSource,
                       QgsProcessingParameterField,
                       QgsProcessingParameterMapLayer,
                       QgsProcessingUtils,
                       QgsProject,
                       QgsVectorLayer,
                       QgsWkbTypes)


class RiskAssessment(QgsProcessingAlgorithm):
    # Constants used to refer to parameters and outputs. They will be
    # used when calling the algorithm from another algorithm, or when
    # calling from the QGIS console.

    riverNetwork = 'RiverNetwork'
    selectedAPI = 'selectedAPI'
    fieldID = "fieldID"
    pnecTable = "pnec_table"
    raTypes = 'raTypes'
    OUTPUT = 'OUTPUT'
    dest_id = None

    # Risk assessment types and their corresponding PNEC column names and field prefixes
    RA_TYPE_CONFIG = [
        ('ERA',    'ERA_PNEC',    'era',  'eraL'),
        ('HHRA',   'HH_PNEC',    'hhra', 'hhraL'),
        ('AMR-RA', 'AMR_PNEC',   'amr',  'amrL'),
    ]

    def shortHelpString(self):
        return self.tr(
            """
            This tool calculates the final risk of different APIs for each river section. In addition to individual \
            PNEC calculations, a cumulative Risk Quotient (RQ) coefficient is calculated to provide an overall assessment \
            when multiple APIs are selected. This single value summarizes the combined risk from all tested substances in \
            each river section, giving the user a quick, comprehensive view of the situation.

            The tool supports both line-based river networks and polygon-based subcatchment networks (e.g., Finnish hydrological model output).

            Workflow:
            1. Choose river_accumulation.shp (or polygon accumulation output) as input for River accumulation
            2. Select the fields containing the concentration of APIs for the risk assessment. This selection should \
                include only columns containing concentrations in ng/L.
            3. Select the PNEC table layer generated by '5 - API parameter selection' tool (Print Table).
            4. Click on Run

            """)

    def initAlgorithm(self, config):

        self.addParameter(
            QgsProcessingParameterFeatureSource(
                self.riverNetwork,
                self.tr('River accumulation'),
                [QgsProcessing.TypeVectorLine, QgsProcessing.TypeVectorPolygon],
                defaultValue=QgsProject.instance().mapLayersByName("River accumulation")[0].id() if QgsProject.instance().mapLayersByName("River accumulation") else None
            )
        )

        self.addParameter(
            QgsProcessingParameterField(
                self.selectedAPI,
                self.tr('Select APIs for risk assessment'),
                parentLayerParameterName=self.riverNetwork,
                allowMultiple=True,
                type=QgsProcessingParameterField.Any,
                defaultValue=[
                    f.name() for f in QgsProject.instance().mapLayersByName("River accumulation")[0].fields() if (f.name().startswith("conc_") or f.name().startswith("conL_")) and f.name() not in ('conc_unit',)
                ] if QgsProject.instance().mapLayersByName("River accumulation") else []
            )
        )

        self.addParameter(
            QgsProcessingParameterField(
                self.fieldID,
                self.tr("ID Field"),
                parentLayerParameterName=self.riverNetwork,
                defaultValue='NET_ID',
                type=QgsProcessingParameterField.Any,
            )
        )

        # PNEC table (layer from Tool 5)
        self.addParameter(
            QgsProcessingParameterMapLayer(
                self.pnecTable,
                description=self.tr('PNEC Table'),
                types=[QgsProcessing.TypeVector],
                defaultValue=QgsProject.instance().mapLayersByName("PNEC")[0].id() if QgsProject.instance().mapLayersByName("PNEC") else None
            )
        )

        self.addParameter(
            QgsProcessingParameterEnum(
                self.raTypes,
                self.tr('Select risk assessment type(s)'),
                options=['ERA (Environmental)', 'HHRA (Human Health)', 'AMR-RA (Antimicrobial Resistance)'],
                allowMultiple=True,
                defaultValue=[0]
            )
        )

        self.addParameter(
            QgsProcessingParameterFeatureSink(
                self.OUTPUT,
                self.tr('Risk assessment'),
                QgsProcessing.TypeVectorAnyGeometry
            )
        )

    def processAlgorithm(self, parameters, context, feedback):
        river_layer_original = self.parameterAsVectorLayer(parameters, self.riverNetwork, context)
        try:
            selected_api_fields = self.parameterAsStrings(parameters, self.selectedAPI, context)
        except AttributeError:
            selected_api_fields = self.parameterAsFields(parameters, self.selectedAPI, context)
        id_field = self.parameterAsString(parameters, self.fieldID, context)
        pnec_layer = self.parameterAsLayer(parameters, self.pnecTable, context)
        selected_ra_indices = self.parameterAsEnums(parameters, self.raTypes, context)

        # Determine which RA types are selected
        selected_ra_types = [self.RA_TYPE_CONFIG[i] for i in selected_ra_indices]
        feedback.pushInfo(f"Selected risk assessment types: {[ra[0] for ra in selected_ra_types]}")

        # Read PNEC table from the layer into a DataFrame
        try:
            field_names = [f.name() for f in pnec_layer.fields()]
            rows = []
            for feat in pnec_layer.getFeatures():
                rows.append([feat[fn] for fn in field_names])
            df_PNEC = pd.DataFrame(rows, columns=field_names)
        except Exception as e:
            feedback.reportError(f"Could not read PNEC layer: {e}")
            return {}

        if "API name" not in df_PNEC.columns:
            feedback.reportError(f"PNEC table must contain an 'API name' column. Found: {list(df_PNEC.columns)}")
            return {}

        # Build short tag -> full API name mapping from the PNEC table
        API_map = {}
        for api_name in df_PNEC["API name"]:
            short_tag = str(api_name)[:4]
            API_map[short_tag] = str(api_name)
        feedback.pushInfo(f"API mapping from PNEC table: {API_map}")

        # Build a PNEC dict per RA type: { 'ERA': {api_name: pnec_value, ...}, ... }
        PNEC_dicts = {}
        for ra_label, pnec_col, _, _ in selected_ra_types:
            if pnec_col not in df_PNEC.columns:
                feedback.reportError(f"Column '{pnec_col}' not found in PNEC table. Available columns: {list(df_PNEC.columns)}")
                return {}
            ra_dict = {}
            for _, row in df_PNEC.iterrows():
                val = row[pnec_col]
                # skip missing / non-numeric values (na, -, empty)
                try:
                    numeric_val = float(val)
                    if numeric_val > 0:
                        ra_dict[row['API name']] = numeric_val
                except (ValueError, TypeError):
                    pass
            PNEC_dicts[ra_label] = ra_dict
            feedback.pushInfo(f"Loaded {len(ra_dict)} PNEC values for {ra_label}.")

        # create an independent copy of the river layer (supports both line and polygon)
        crs = river_layer_original.crs().authid()
        geom_type = QgsWkbTypes.displayString(river_layer_original.wkbType())
        feedback.pushInfo(f"\nInput layer geometry type: {geom_type}")
        feedback.pushInfo("Creating working copy of input layer...")
        river_layer = QgsVectorLayer(f"{geom_type}?crs={crs}", "river_layer_copy", "memory")
        provider = river_layer.dataProvider()

        # add the NET_ID field
        net_id_field = river_layer_original.fields().field(id_field)
        if net_id_field:
            provider.addAttributes([net_id_field])

        # add the selected concentration fields
        for field_name in selected_api_fields:
            orig_field = river_layer_original.fields().field(field_name)
            provider.addAttributes([orig_field])

        # add unit columns if they exist in the source layer
        unit_fields = []
        for uname in ('conc_unit',):
            if river_layer_original.fields().indexFromName(uname) != -1:
                unit_fields.append(uname)
                provider.addAttributes([river_layer_original.fields().field(uname)])
        river_layer.updateFields()

        # copy selected features
        for feat in river_layer_original.getFeatures():
            new_feat = QgsFeature(river_layer.fields())
            new_feat.setGeometry(feat.geometry())
            # copy the ID field if it exists
            if net_id_field:
                new_feat[id_field] = feat[id_field]
            for field in selected_api_fields:
                new_feat[field] = feat[field]
            for ufield in unit_fields:
                new_feat[ufield] = feat[ufield]
            provider.addFeature(new_feat)

        feedback.pushInfo(f"Copied {river_layer.featureCount()} features with {len(selected_api_fields)} concentration fields.")

        # add new fields for RQ - one per RA type per concentration field
        rq_field_entries = []  # list of (conc_field, rq_field_name, api_suffix, ra_label, pnec_col)
        for conc_field in selected_api_fields:
            # skip unit columns
            if conc_field in ('conc_unit', 'acc_unit'):
                continue
            api_suffix = conc_field[-4:]  # last 4 letters (e.g., Carb)
            is_low_flow = conc_field.startswith("conL_")
            is_normal = conc_field.startswith("conc_")
            if not is_normal and not is_low_flow:
                continue

            for ra_label, pnec_col, prefix_normal, prefix_low in selected_ra_types:
                prefix = prefix_low if is_low_flow else prefix_normal
                rq_field_name = f"{prefix}_{api_suffix}"
                provider.addAttributes([QgsField(rq_field_name, QVariant.Double)])
                rq_field_entries.append((conc_field, rq_field_name, api_suffix, ra_label, pnec_col))
        river_layer.updateFields()

        feedback.pushInfo(f"\nCalculating Risk Quotient (RQ = PEC/PNEC) for {len(rq_field_entries)} fields across {len(selected_ra_types)} RA type(s)...")

        # calculate RQ = PEC/PNEC for each RA type
        river_layer.startEditing()

        for conc_field, rq_field_name, api_suffix, ra_label, pnec_col in rq_field_entries:
            # map short tag to full API name
            full_api_name = API_map.get(api_suffix)
            if full_api_name is None:
                feedback.pushWarning(f"Skipping {api_suffix}: no mapping found in PNEC table")
                continue

            # get PNEC value for this RA type
            pnec = PNEC_dicts[ra_label].get(full_api_name)
            if pnec is None or pnec == 0:
                feedback.pushWarning(f"No valid {ra_label} PNEC value for {full_api_name} - skipping")
                continue

            # calculate RQ for all features
            for feat in river_layer.getFeatures():
                pec = feat[conc_field]
                if pec is None or pec == NULL:
                    continue
                rq_value = float(pec) / pnec
                feat[rq_field_name] = rq_value
                river_layer.updateFeature(feat)

        # commit changes
        river_layer.commitChanges()
        feedback.pushInfo("Risk Quotient calculation completed.")

        """
        Cumulative Combined Risk Index (CCRI)
        CCRI = log(RQ_sum + 1) * (1 + (RQ>1)_sum / RQ_sum)
        """

        feedback.pushInfo("\nCalculating Cumulative Combined Risk Index (CCRI)...")

        def cumulative_function(prefix, name):
            # check if we have RQ fields for this prefix
            fields = [f.name() for f in river_layer.fields()]
            rq_fields = [f for f in fields if f.startswith(prefix)]

            # add new field
            if rq_fields and name not in fields:
                provider.addAttributes([QgsField(name, QVariant.Double)])
                river_layer.updateFields()

            # iterate over all features (river sections)
            for feat in river_layer.getFeatures():
                if rq_fields:
                    rq_values = []
                    for rq_field in rq_fields:
                        rq_value = feat[rq_field]
                        # skip NULL or missing values
                        if rq_value is None or rq_value == NULL:
                            continue
                        rq_values.append(float(rq_value))

                    if not rq_values:
                        feat[name] = 0.0
                        river_layer.updateFeature(feat)
                        continue

                    # RQ_sum: sum of all RQ values
                    rq_sum = sum(rq_values)

                    if rq_sum == 0:
                        feat[name] = 0.0
                        river_layer.updateFeature(feat)
                        continue

                    # (RQ>1)_sum: sum of RQ values exceeding 1
                    rq_exceeding_sum = sum(v for v in rq_values if v > 1)

                    # CCRI = log(RQ_sum + 1) * (1 + (RQ>1)_sum / RQ_sum)
                    ccri = np.log(rq_sum + 1) * (1 + (rq_exceeding_sum / rq_sum))

                    feat[name] = float(ccri)
                    river_layer.updateFeature(feat)

        # start editing
        river_layer.startEditing()
        # Calculate CCRI for each selected RA type (normal + low flow)
        for ra_label, _, prefix_normal, prefix_low in selected_ra_types:
            cumulative_function(prefix=f"{prefix_normal}_", name=f"CCRI_{prefix_normal}")
            cumulative_function(prefix=f"{prefix_low}_", name=f"CCRI_{prefix_low}")
        # commit changes
        river_layer.commitChanges()
        feedback.pushInfo("Cumulative risk index calculation completed.")

        '''sink definition'''
        feedback.pushInfo("\nPreparing output layer...")
        (sink, self.dest_id) = self.parameterAsSink(
            parameters,
            self.OUTPUT,
            context,
            river_layer.fields(),
            river_layer.wkbType(),
            river_layer.sourceCrs()
        )

        # add to the sink
        for feature in river_layer.getFeatures():
            sink.addFeature(feature)

        return {self.OUTPUT: self.dest_id}

    def postProcessAlgorithm(self, context, feedback):
        feedback.setProgressText("\nApplying style to the output layer...")
        sink_layer = QgsProcessingUtils.mapLayerFromString(self.dest_id, context)

        if sink_layer:
            # Choose style based on geometry type
            if sink_layer.geometryType() == QgsWkbTypes.PolygonGeometry:
                style_path = os.path.join(os.path.dirname(__file__), 'styles/risk_assessment_ERA_polygon.qml')
            else:
                style_path = os.path.join(os.path.dirname(__file__), 'styles/risk_assessment_ERA_line.qml')
            sink_layer.loadNamedStyle(style_path)

            # Detect which field to drive the graduated renderer with.
            # Priority: era_ > amr_ > hhra_ > eraL_ > amrL_ > hhraL_
            field_names = [f.name() for f in sink_layer.fields()]
            target_field = None
            for prefix, exclude in [
                ('era_', 'eraL_'),
                ('amr_', 'amrL_'),
                ('hhra_',  'hhraL_'),
                ('eraL_', None),
                ('amrL_', None),
                ('hhraL_',  None),
            ]:
                candidates = [
                    n for n in field_names
                    if n.startswith(prefix) and (exclude is None or not n.startswith(exclude))
                ]
                if candidates:
                    target_field = candidates[0]
                    break

            # Replace the renderer's class attribute so Layer Properties shows
            # a plain field name (e.g. "era_Dicl") instead of the formula
            if target_field:
                renderer = sink_layer.renderer()
                if hasattr(renderer, 'setClassAttribute'):
                    renderer.setClassAttribute(target_field)
                    sink_layer.setRenderer(renderer)
                    feedback.pushInfo(f"Graduated style applied using field: {target_field}")
                else:
                    feedback.pushWarning(
                        "Renderer is not graduated; field could not be set automatically.")
            else:
                feedback.pushWarning(
                    "No era_/amr_/hhra_ field found; style loaded with default expression.")

            sink_layer.triggerRepaint()

        return {self.OUTPUT: self.dest_id}

    def name(self):
        return '8 - Risk Assessment'

    def displayName(self):
        return self.tr(self.name())

    def group(self):
        return self.tr(self.groupId())

    def groupId(self):
        return 'API emission'

    def helpUrl(self):
        # Return a URL or local file path to your documentation
        return "https://hosting-apriora-manual.readthedocs.io/en/latest/api_emission/Risk_assessment.html"

    def tr(self, string):
        return QCoreApplication.translate('Processing', string)

    def createInstance(self):
        return RiskAssessment()
