# -*- coding: utf-8 -*-

"""
/***************************************************************************
 APRIORA
                                 A QGIS plugin
 Collection of APRIORA Plugins
 Generated by Plugin Builder: http://g-sherman.github.io/Qgis-Plugin-Builder/
                              -------------------
        begin                : 2024-06-13
        copyright            : (C) 2024 by Universität Rostock
        email                : cristiano.guidi2@uni-rostock.de
 ***************************************************************************/

/***************************************************************************
 *                                                                         *
 *   This program is free software; you can redistribute it and/or modify  *
 *   it under the terms of the GNU General Public License as published by  *
 *   the Free Software Foundation; either version 2 of the License, or     *
 *   (at your option) any later version.                                   *
 *                                                                         *
 ***************************************************************************/
"""

__author__ = 'Cristiano Guidi'
__date__ = '2024-06-13'
__copyright__ = '(C) 2024 by Universität Rostock'

# This will get replaced with a git SHA1 when you do a git archive

__revision__ = '$Format:%H$'

import pandas as pd
import os
from qgis.PyQt.QtCore import (QCoreApplication, QVariant)
from qgis.core import ( QgsFeature,
                        QgsFeatureSink,
                        QgsFields,
                        QgsField,
                        QgsProcessing,
                        QgsProcessingAlgorithm,
                        QgsProcessingParameterFeatureSource,
                        QgsProcessingParameterFeatureSink,
                        QgsProcessingParameterField,
                        QgsProcessingParameterString,
                        QgsProcessingUtils,
                        QgsVectorLayer,
                        QgsWkbTypes                    
                        )


class EmissionLoads(QgsProcessingAlgorithm):

    # Constants used to refer to parameters and outputs. They will be
    # used when calling the algorithm from another algorithm, or when
    # calling from the QGIS console.

    emissionPoints = 'EmissionPoints'
    OUTPUT = 'OUTPUT'

    def shortHelpString(self):
        return self.tr(""" This tool calculates the emission load of certain APIs (Active Pharmaceutical Ingredients) at the WWTP (WasteWater Treatment Plant) emission points.
        """)

    #Init tool
    def initAlgorithm(self, config):
        """
        Here we define the inputs and output of the algorithm, along
        with some other properties.
        """
        self.addParameter(
            QgsProcessingParameterFeatureSource(
                self.emissionPoints,
                self.tr('Emission Points of WWTP'),
                [QgsProcessing.TypeVectorPoint]
            )
        )

        # id
        self.addParameter(
            QgsProcessingParameterField(
                name='field_id',
                description=self.tr('Select ID field'),
                parentLayerParameterName=self.emissionPoints,
                type=QgsProcessingParameterField.Any
            )
        )

        # inhabitants connected
        self.addParameter(
            QgsProcessingParameterField(
                name='field_inhabitants',
                description=self.tr('Select Inhabitants Connected field'),
                parentLayerParameterName=self.emissionPoints,
                type=QgsProcessingParameterField.Any
            )
        )

        # technology class
        self.addParameter(
            QgsProcessingParameterField(
                name='field_techclass',
                description=self.tr('Select Technology Class field'),
                parentLayerParameterName=self.emissionPoints,
                type=QgsProcessingParameterField.Any
            )
        )
        
        # show the user's selection
        # Read contents from the .txt file
        plugin_dir = os.path.dirname(__file__)
        file_path = os.path.join(plugin_dir, "user_selection.txt")

        try:
            with open(file_path, "r") as file:
                selection_text = file.read().strip()
        except Exception as e:
            selection_text = f"Could not load selection.txt: {e}"
        
        self.addParameter(
            QgsProcessingParameterString(
                name="USER_SELECTION_INFO",
                description=self.tr("Current API Selection"),
                defaultValue=selection_text.replace(",", ", ").replace("\n", "\n"),
            )
        )

        # We add a feature sink in which to store our processed features (this
        # usually takes the form of a newly created vector layer when the
        # algorithm is run in QGIS).
        self.addParameter(
            QgsProcessingParameterFeatureSink(
                self.OUTPUT,
                self.tr('Emission Loads'),
                QgsProcessing.TypeVectorPoint
            )
        )

    def processAlgorithm(self, parameters, context, feedback):
        """
        Here is where the processing itself takes place.
        """
        # retrieve the selection of the user
        plugin_dir = os.path.dirname(__file__)
        file_path = os.path.join(plugin_dir, "user_selection.txt")

        # read and show content
        if os.path.exists(file_path):
            try:
                with open(file_path, 'r') as file:
                    selection_data = file.read()

                # push to the panel
                feedback.pushInfo("User selection loaded:\n"+selection_data)

            except Exception as e:
                feedback.reportError(f"Error reading user_selection.txt: {e}")
                selection_data = None
        
        else:
            feedback.reportError("user_selection.txt not found")
            selection_data = None

        # retrieve the consumption data from our database
        excel_file = os.path.join(plugin_dir, "B2 input.xlsx")
        try:
            df = pd.read_excel(excel_file)
        except Exception as e:
            feedback.reportError(f"Could not read Excel file: {e}")
            return {}

        # load selection
        try:
            with open
        









        '''sink definition'''
        (sink, dest_id) = self.parameterAsSink(
            parameters,
            self.OUTPUT,
            context,
            out_fields, #change
            emission_point.wkbType(),
            emission_point.sourceCrs())

        return {self.OUTPUT: dest_id}

    
    
    def name(self):
        """
        Returns the algorithm name, used for identifying the algorithm. This
        string should be fixed for the algorithm, and must not be localised.
        The name should be unique within each provider. Names should contain
        lowercase alphanumeric characters only and no spaces or other
        formatting characters.
        """
        return '5 - Emission Loads'

    def displayName(self):
        """
        Returns the translated algorithm name, which should be used for any
        user-visible display of the algorithm name.
        """
        return self.tr(self.name())

    def group(self):
        """
        Returns the name of the group this algorithm belongs to. This string
        should be localised.
        """
        return self.tr(self.groupId())

    def groupId(self):
        """
        Returns the unique ID of the group this algorithm belongs to. This
        string should be fixed for the algorithm, and must not be localised.
        The group id should be unique within each provider. Group id should
        contain lowercase alphanumeric characters only and no spaces or other
        formatting characters.
        """
        return 'API emission'

    def tr(self, string):
        return QCoreApplication.translate('Processing', string)

    def createInstance(self):
        return EmissionLoads()