name: Draft PDF
on:
  push:
    paths:
      - 'joss_paper/**'
      - '.github/workflows/draft-paper.yml'

jobs:
  paper:
    runs-on: ubuntu-latest
    name: Paper Draft
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Build draft PDF
        uses: openjournals/openjournals-draft-action@master
        with:
          journal: joss
          # Path to the paper within your repo
          paper-path: joss_paper/paper.md

      - name: Commit PDF to repository
        uses: EndBug/add-and-commit@v9
        with:
          message: '(auto) Update JOSS draft PDF'
          # Path to the compiled PDF to commit back to the repo
          add: 'joss_paper/paper.pdf'
